import {ResourceLink} from './ResourcePicker.js';
import React,{useState,useEffect,useRef} from '../vendor/react.mjs';
import {store} from '../storage/database.js';
import {SUBJECTS} from './model.js';
import {dashboardCards,filterDashboard,DASHBOARD_ROWS} from './dashboard.js';
import type {DashboardCard} from './dashboard.js';
import {sharedFolders,taxonomyLabel} from './taxonomy.js';
import {updateCapture} from './content.js';
export function Dashboard({catalogue,workspace,session,onSession,onClose,onCapture,onOpen,onActions,onEdit}:any){
 const [expanded,setExpanded]=useState<Record<string,boolean>>({}),[done,setDone]=useState(false),[error,setError]=useState(''),root=useRef<HTMLElement|null>(null);
 const selectedItem=workspace.personal.dashboardItems?.find(x=>x.id===session.dashboardItemId);
 const all=dashboardCards(catalogue,workspace,done||selectedItem?.status==='done'),cards=filterDashboard(all,catalogue,workspace,session.dashboardSubject,session.dashboardFolder),folders=sharedFolders(catalogue,workspace.overlays).filter(f=>f.subject===session.dashboardSubject),subjects=SUBJECTS.filter(s=>!session.dashboardSubject||s.id===session.dashboardSubject);
 useEffect(()=>{if(!session.dashboardItemId)return;const el=root.current?.querySelector<HTMLElement>('[data-dashboard-item="'+CSS.escape(session.dashboardItemId)+'"]');el?.scrollIntoView({block:'center'});el?.focus();},[session.dashboardItemId]);
 function scope(subject?:string,folderId?:string){onSession(s=>{if(subject)s.dashboardSubject=subject;else delete s.dashboardSubject;if(folderId)s.dashboardFolder=folderId;else delete s.dashboardFolder;delete s.dashboardItemId;});}
 async function update(id:string,status:string){try{await store.personal(p=>updateCapture(p,id,{status:status as any}));}catch(e){setError((e as Error).message);}}
 function card(d:DashboardCard){return <article key={d.id} className={'dashboard-card '+(d.important?'important ':'')+(d.done?'done ':'')+(session.dashboardItemId===d.capture?'selected':'')} data-dashboard-item={d.capture??d.id} tabIndex={-1}>
  {d.target.kind==='url'?<a href={d.url} target="_blank" rel="noopener noreferrer">{d.title}</a>:<button className="dashboard-card-title" onClick={()=>d.capture?onEdit(workspace.personal.dashboardItems.find(i=>i.id===d.capture)):onOpen(d.target)}>{d.title}</button>}
  {d.important&&<small className="important-label">Important</small>}{d.dueAt!==undefined&&<time dateTime={new Date(d.dueAt).toISOString()}>Due {new Date(d.dueAt).toISOString().slice(0,10)}</time>}{d.note&&<p>{d.note}</p>}<small>{taxonomyLabel(d.taxonomy,catalogue,workspace.overlays)}</small>
  <div className="dashboard-card-actions">{d.url&&d.target.kind!=='url'&&<a href={d.url} target="_blank" rel="noopener noreferrer">Open link</a>}{d.source&&<ResourceLink target={d.source} label={'Source for '+d.title} onOpen={onOpen}/>}{d.capture&&d.row==='To-do'&&<button aria-label={(d.done?'Reopen ':'Complete ')+d.title} onClick={()=>void update(d.capture!,d.done?'open':'done')}>{d.done?'Reopen':'Done'}</button>}{d.capture&&<button aria-label={'Archive '+d.title} onClick={()=>void update(d.capture!,'archived')}>Archive</button>}<button aria-label={'Actions for '+d.title} onClick={e=>onActions(d.target,d.title,e)}>...</button></div></article>;}
 function cell(entries:DashboardCard[],key:string){const special=entries.find(x=>x.capture===session.dashboardItemId),show=expanded[key]?entries:entries.slice(0,3);if(special&&!show.includes(special))show.push(special);return <>{show.map(card)}{!entries.length&&<span className="dashboard-empty">Nothing here</span>}{entries.length>3&&<button className="text-button show-more" onClick={()=>setExpanded(p=>({...p,[key]:!p[key]}))}>{expanded[key]?'Show less':'Show more ('+entries.length+')'}</button>}</>;}
 return <main ref={root} className="dashboard-page" aria-label="Dashboard"><header className="hub-surface-header"><div><small>SHARED CAPTURES AND READING LISTS</small><h1>Dashboard</h1><p>Five subjects. Your reader stays where you left it.</p></div><div className="button-row"><button onClick={onCapture}>Quick Capture</button><button onClick={onClose}>Return to reader</button></div></header><div className="dashboard-scope"><button aria-pressed={!session.dashboardSubject} onClick={()=>scope()}>All subjects</button>{SUBJECTS.map(s=><button key={s.id} aria-pressed={session.dashboardSubject===s.id} onClick={()=>scope(s.id)}>{s.label}</button>)}{session.dashboardSubject&&<label>Scope<select aria-label="Dashboard folder scope" value={session.dashboardFolder??''} onChange={e=>scope(session.dashboardSubject,e.target.value)}><option value="">All folders in this subject</option>{folders.map(f=><option key={f.id} value={f.id}>{f.path.join(' / ')}</option>)}</select></label>}<label className="inline-check"><input type="checkbox" checked={done} onChange={e=>setDone(e.target.checked)}/>Include completed</label></div>
 {session.dashboardSubject&&<div className="dashboard-subfolders" aria-label="Subject subcategories">{folders.filter(f=>!f.parentId||f.parentId===session.dashboardFolder).slice(0,20).map(f=><button key={f.id} onClick={()=>scope(f.subject,f.id)}>{f.title}</button>)}</div>}
 {selectedItem?.status==='archived'&&<section className="revision-warning" role="status"><strong>Archived capture: {selectedItem.text}</strong><p>This target is retained, not reassigned.</p><button onClick={()=>void update(selectedItem.id,selectedItem.kind==='task'?'open':'inbox')}>Restore this capture</button></section>}<p className="dashboard-mobile-hint secondary">Choose a subject for a single-column view, or scroll the overview horizontally.</p><div className={'dashboard-grid '+(subjects.length===1?'scoped':'')}><table aria-label="Subjects and capture categories"><thead><tr><th scope="col" className="dashboard-column-head empty">Category</th>{subjects.map(s=><th scope="col" className="dashboard-column-head" key={s.id}><button onClick={()=>scope(s.id)}>{s.label}</button></th>)}</tr></thead><tbody>{DASHBOARD_ROWS.map(row=><tr key={row}><th scope="row" className="dashboard-row-label">{row}</th>{subjects.map(s=><td className="dashboard-cell" key={s.id+row} aria-label={s.label+' '+row}>{cell(cards.filter(d=>d.taxonomy?.subject===s.id&&d.row===row),s.id+row)}</td>)}</tr>)}</tbody></table></div>
 {!session.dashboardSubject&&all.some(d=>!d.taxonomy)&&<section className="dashboard-unclassified"><h2>Unclassified</h2><p>Assign a subject when useful. Captures without classification are retained here.</p><div className="dashboard-unfiled-cards">{cell(all.filter(d=>!d.taxonomy),'unclassified')}</div></section>}{error&&<p role="alert">{error}</p>}</main>;
}
