import {ResourceLink} from './ResourcePicker.js';
import React,{useState,useEffect,useRef} from '../vendor/react.mjs';
import {store} from '../storage/database.js';
import {SUBJECTS} from './model.js';
import {dashboardCards,filterDashboard,DASHBOARD_ROWS} from './dashboard.js';
import type {DashboardCard,DashboardRow} from './dashboard.js';
import {sharedFolders,taxonomyLabel} from './taxonomy.js';
import {updateCapture} from './content.js';
export function Dashboard({catalogue,workspace,session,onSession,onClose,onCapture,onOpen,onActions,onEdit,onAddReading,onDemo}:any){
 const [expanded,setExpanded]=useState<Record<string,boolean>>({}),[done,setDone]=useState(false),[error,setError]=useState(''),root=useRef<HTMLElement|null>(null);
 const selectedItem=workspace.personal.dashboardItems?.find(x=>x.id===session.dashboardItemId);
 const all=dashboardCards(catalogue,workspace,done||selectedItem?.status==='done'),cards=filterDashboard(all,catalogue,workspace,session.dashboardSubject,session.dashboardFolder),folders=sharedFolders(catalogue,workspace.overlays).filter(f=>f.subject===session.dashboardSubject);
 useEffect(()=>{if(!session.dashboardItemId)return;const el=root.current?.querySelector<HTMLElement>('[data-dashboard-item="'+CSS.escape(session.dashboardItemId)+'"]');el?.scrollIntoView({block:'center'});el?.focus();},[session.dashboardItemId]);
 function scope(subject?:string,folderId?:string){onSession(s=>{if(subject)s.dashboardSubject=subject;else delete s.dashboardSubject;if(folderId)s.dashboardFolder=folderId;else delete s.dashboardFolder;delete s.dashboardItemId;});}
 async function update(id:string,status:string){try{await store.personal(p=>updateCapture(p,id,{status:status as any}));}catch(e){setError((e as Error).message);}}
 function add(row:DashboardRow){if(row==='Bookmarks'||row==='Read later')onAddReading(row==='Bookmarks'?'bookmark':'later');else onCapture(row==='To-do'?'task':row==='Quick notes'?'note':'link');}
 function dataRow(d:DashboardCard,row:DashboardRow){return <tr key={d.id} className={'dashboard-data-row '+(d.done?'done ':'')} data-dashboard-item={d.capture??d.id} tabIndex={-1}>
  <td><article className={'dashboard-card '+(d.important?'important ':'')+(session.dashboardItemId&&session.dashboardItemId===d.capture?'selected':'')}>
   {d.target.kind==='url'?<a href={d.url} target="_blank" rel="noopener noreferrer">{d.title}</a>:<button className="dashboard-card-title" onClick={()=>d.capture?onEdit(workspace.personal.dashboardItems.find(i=>i.id===d.capture)):onOpen(d.target)}>{d.title}</button>}
   {d.note&&<small className="dashboard-note">{d.note}</small>}
   <div className="dashboard-card-actions">{d.url&&d.target.kind!=='url'&&<a href={d.url} target="_blank" rel="noopener noreferrer">Open link</a>}{d.source&&<ResourceLink target={d.source} label={'Source for '+d.title} onOpen={onOpen}/>}</div>
  </article></td>
  <td className="dashboard-classification" title={taxonomyLabel(d.taxonomy,catalogue,workspace.overlays)}>{SUBJECTS.find(s=>s.id===d.taxonomy?.subject)?.label??'Unclassified'}</td>
  <td className="dashboard-status">{d.important&&<small className="important-label">Important</small>}{d.dueAt!==undefined&&<time dateTime={new Date(d.dueAt).toISOString()}>Due {new Date(d.dueAt).toISOString().slice(0,10)}</time>}{d.done&&<small>Completed</small>}</td>
  <td><div className="dashboard-row-actions">{d.capture&&d.row==='To-do'&&<button aria-label={(d.done?'Reopen ':'Complete ')+d.title} onClick={()=>void update(d.capture!,d.done?'open':'done')}>{d.done?'Reopen':'Done'}</button>}{d.capture&&<button aria-label={'Archive '+d.title} title="Archive this capture" onClick={()=>void update(d.capture!,'archived')}>Archive</button>}<button aria-label={'Actions for '+d.title} onClick={e=>onActions(d.target,d.title,e)}>...</button><button className="dashboard-add" aria-label={'Add to '+row} title={'Add to '+row} onClick={()=>add(row)}>+</button></div></td>
 </tr>;}
 function miniTable(row:DashboardRow){const entries=cards.filter(c=>c.row===row),special=entries.find(x=>x.capture===session.dashboardItemId),visible=expanded[row]?[...entries]:entries.slice(0,3);if(special&&!visible.includes(special))visible.push(special);
  return <section key={row} className="dashboard-mini-table" aria-label={row+' table'}><header><h2>{row} <small>{entries.length}</small></h2><button aria-label={'Add to '+row} title={'Add to '+row} onClick={()=>add(row)}>+</button></header><div className="mini-table-scroll"><table aria-label={row}><thead><tr><th scope="col">{row==='To-do'?'Task':row==='Quick notes'?'Note':'Item'}</th><th scope="col">Subject</th><th scope="col">{row==='To-do'?'Due / priority':'Status'}</th><th scope="col"><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map(d=>dataRow(d,row))}{Array.from({length:Math.max(0,3-visible.length)},(_,i)=><tr key={'empty-'+i} className="dashboard-empty-slot" data-empty-slot="true"><td><span>No item</span></td><td aria-label="No subject">-</td><td/><td><button className="dashboard-add" aria-label={'Add to '+row} title={'Add to '+row} onClick={()=>add(row)}>+</button></td></tr>)}</tbody></table></div>{entries.length>3&&<button className="text-button show-more" onClick={()=>setExpanded(p=>({...p,[row]:!p[row]}))}>{expanded[row]?'Show less':'Show more ('+entries.length+')'}</button>}</section>;
 }
 return <main ref={root} className="dashboard-page" aria-label="Dashboard"><header className="hub-surface-header"><div><small>SHARED CAPTURES AND READING LISTS</small><h1>Dashboard</h1><p>Your next actions and saved reading. Your reader stays where you left it.</p></div><div className="button-row"><button onClick={()=>onCapture('link')}>Quick Capture</button><button onClick={onClose}>Return to reader</button></div></header>
 <div className="dashboard-scope"><button aria-pressed={!session.dashboardSubject} onClick={()=>scope()}>All subjects</button>{SUBJECTS.map(s=><button key={s.id} aria-pressed={session.dashboardSubject===s.id} onClick={()=>scope(s.id)}>{s.label}</button>)}{session.dashboardSubject&&<label>Scope<select aria-label="Dashboard folder scope" value={session.dashboardFolder??''} onChange={e=>scope(session.dashboardSubject,e.target.value)}><option value="">All folders in this subject</option>{folders.map(f=><option key={f.id} value={f.id}>{f.path.join(' / ')}</option>)}</select></label>}<label className="inline-check"><input type="checkbox" checked={done} onChange={e=>setDone(e.target.checked)}/>Include completed</label></div>
 {session.dashboardSubject&&<div className="dashboard-subfolders" aria-label="Subject subcategories">{folders.filter(f=>!f.parentId||f.parentId===session.dashboardFolder).slice(0,20).map(f=><button key={f.id} onClick={()=>scope(f.subject,f.id)}>{f.title}</button>)}</div>}
 {selectedItem?.status==='archived'&&<section className="revision-warning" role="status"><strong>Archived capture: {selectedItem.text}</strong><p>This target is retained, not reassigned.</p><button onClick={()=>void update(selectedItem.id,selectedItem.kind==='task'?'open':'inbox')}>Restore this capture</button></section>}
 <div className="dashboard-tables">{DASHBOARD_ROWS.map(miniTable)}</div>
 {onDemo&&<details className="demo-controls"><summary>Optional demo / test data</summary><p>Loads a named demonstration set locally. Nothing is fetched. Cleanup keeps edited items and sources referenced by your own saved work.</p><div className="button-row"><button onClick={()=>onDemo('load')}>Load demo data</button><button onClick={()=>onDemo('remove')}>Reset/remove demo data</button></div></details>}
 {error&&<p role="alert">{error}</p>}</main>;
}
