import React,{useState} from '../vendor/react.mjs';
import {Modal,Field} from '../components/Modal.js';
import {store} from '../storage/database.js';
import {uid} from '../core/workspace.js';
import type {ArticleSource,TaxonomyRef,QcmDocument} from './model.js';
import {parseContentJSON,validateArticleSource,validateQcm} from './validation.mjs';
import {articlePage,articleExport,qcmPage,putContent,captureRows,downloadJSON,updateReference,removeReference,updateCapture} from './content.js';
import {TaxonomyPicker} from './TaxonomyPicker.js';
import {taxonomyLabel} from './taxonomy.js';

export const qcmTemplate=():QcmDocument=>({schemaVersion:1,id:uid('qcm'),title:'New QCM set',questions:[{id:'q1',prompt:'Replace this prompt with your question.',options:[{id:'a',text:'First option',explanation:'Explain why this option is correct.'},{id:'b',text:'Second option',explanation:'Explain why this option is incorrect.'}],correctOptionIds:['a'],explanation:'Add the reasoning here.',followUp:'Add an optional follow-up.'}]});
export function ContentEditor({kind,page,catalogue,initialSource,initialTaxonomy,onClose,onOpen,notify}:any){
 const editing=!!page;const initial=kind==='qcm'?(page?.qcm??qcmTemplate()):(page?.article?articleExport(page):{id:uid('article'),title:'',sourceType:'link',status:'inbox',...(initialTaxonomy?{taxonomy:initialTaxonomy}:{}),...(initialSource??{})});
 const [source,setSource]=useState<any>(initial),[raw,setRaw]=useState(JSON.stringify(initial,null,2)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[jsonMode,setJsonMode]=useState(kind==='qcm'),[replaceBody,setReplaceBody]=useState(!initial.blocks?.length||initial.blocks.length===1&&initial.blocks[0].type==='markdown');
 const [text,setText]=useState(initial.text??(initial.blocks?.length===1&&initial.blocks[0].type==='markdown'?initial.blocks[0].text:''));
 function change(k:string,v:any){setSource(s=>({...s,[k]:v}));}
 async function load(file?:File){if(!file)return;try{if(file.size>4*1024*1024)throw Error('JSON file exceeds 4 MiB.');const value=await file.text();setRaw(value);setJsonMode(true);setError('');}catch(e){setError((e as Error).message);}}
 async function save(e:any){e.preventDefault();setBusy(true);setError('');try{
  let value:any=jsonMode?parseContentJSON(raw):{...source};
  if(!jsonMode){for(const key of ['url','publisher','note'])if(!value[key])delete value[key];if(replaceBody){delete value.blocks;if(text.trim())value.text=text;else delete value.text;}}
  if(editing&&value.id!==page.id)throw Error('An edit cannot change the resource ID. Import a new copy instead.');
  if(kind==='articles'){validateArticleSource(value);if(editing)value.updatedAt=Date.now();}else validateQcm(value);
  const result=kind==='qcm'?qcmPage(value):articlePage(value);
  await store.overlays(o=>putContent(o,result,catalogue,editing));onClose();onOpen(result.id);notify((editing?'Saved ':'Created ')+result.title+'.');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal wide title={(editing?'Edit ':'New/import ')+(kind==='qcm'?'QCM':'article')} onClose={onClose}><form onSubmit={save} className="hub-editor"><p className="secondary">Private local content. Web addresses are references only; AtlasNote does not fetch or embed external articles.</p><Field label="Import JSON file"><input type="file" aria-label="Content JSON file" accept=".json,application/json" onChange={e=>void load(e.target.files?.[0])}/></Field>{kind==='articles'&&<label className="inline-check"><input type="checkbox" checked={jsonMode} onChange={e=>{if(e.target.checked){const v={...source};if(replaceBody){delete v.blocks;v.text=text;}setRaw(JSON.stringify(v,null,2));}else{try{const v=parseContentJSON(raw);validateArticleSource(v);setSource(v);setText(v.text??(v.blocks?.length===1&&v.blocks[0].type==='markdown'?v.blocks[0].text:''));setReplaceBody(!v.blocks?.length||v.blocks.length===1&&v.blocks[0].type==='markdown');}catch(ex){setError((ex as Error).message);return;}}setJsonMode(e.target.checked);}}/>Edit canonical JSON</label>}
 {jsonMode?<Field label={kind==='qcm'?'QCM JSON':'Article JSON'}><textarea aria-label={kind==='qcm'?'QCM JSON':'Article JSON'} spellCheck={false} rows={18} value={raw} onChange={e=>setRaw(e.target.value)}/></Field>:<><div className="hub-form-grid"><Field label="Title"><input required maxLength={200} value={source.title} onChange={e=>change('title',e.target.value)}/></Field><Field label="Source URL"><input type="url" value={source.url??''} onChange={e=>change('url',e.target.value)}/></Field><Field label="Publisher"><input value={source.publisher??''} onChange={e=>change('publisher',e.target.value)}/></Field><Field label="Source type"><select aria-label="Source type" value={source.sourceType??'article'} onChange={e=>change('sourceType',e.target.value)}>{['link','article','transcript','documentation'].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Article status"><select aria-label="Article status" value={source.status??'inbox'} onChange={e=>change('status',e.target.value)}>{['inbox','unread','reading','finished'].map(t=><option key={t}>{t}</option>)}</select></Field><label className="inline-check"><input type="checkbox" checked={source.important??false} onChange={e=>change('important',e.target.checked)}/>Important</label></div><TaxonomyPicker catalogue={catalogue} overlays={store.state.overlays} value={source.taxonomy} onChange={v=>{const next={...source};if(v)next.taxonomy=v;else delete next.taxonomy;setSource(next);}}/><Field label="Personal article note"><textarea aria-label="Personal article note" rows={2} value={source.note??''} onChange={e=>change('note',e.target.value)}/></Field>{initial.blocks?.length>0&&!replaceBody?<p>This article has structured blocks. They will be preserved. Use canonical JSON to edit them, or <button type="button" onClick={()=>setReplaceBody(true)}>Replace body with pasted text</button>.</p>:<Field label="Pasted article or transcript"><textarea aria-label="Pasted article or transcript" rows={12} value={text} onChange={e=>setText(e.target.value)} placeholder="Paste text or safe Markdown. No remote HTML is fetched."/></Field>}</>}
 {error&&<p role="alert" className="error-message">{error}</p>}<div className="dialog-actions"><button type="button" onClick={onClose}>Cancel</button>{editing&&<button type="button" onClick={()=>downloadJSON(kind==='qcm'?page.qcm:articleExport(page),page.id+'.json')}>Export source</button>}<button type="submit" className="primary" disabled={busy}>{editing?'Save content':'Import local content'}</button></div></form></Modal>;
}
export function QuickCapture({catalogue,contextTarget,suggestion,onClose,notify,onArticle}:any){
 const [mode,setMode]=useState<'link'|'task'|'note'|'article'|'transcript'>('link'),[rows,setRows]=useState([{text:'',url:'',due:'',important:false}]),[taxonomy,setTaxonomy]=useState<TaxonomyRef|undefined>(undefined),[attach,setAttach]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:any){e.preventDefault();setBusy(true);try{await store.personal(p=>captureRows(p,mode as any,rows,taxonomy,attach?contextTarget:undefined));notify('Saved to the shared Dashboard.');onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function choose(m:any){if(m==='article'||m==='transcript'){onArticle({sourceType:m,...(taxonomy?{taxonomy}:{}),...(attach&&contextTarget?{contextTarget}:{})});return;}setMode(m);setError('');}
 return <Modal wide title="Quick Capture" onClose={onClose}><form onSubmit={save}><div className="capture-modes" role="group" aria-label="Capture type">{['link','task','note','article','transcript'].map(m=><button type="button" key={m} aria-pressed={mode===m} onClick={()=>choose(m)}>{m[0].toUpperCase()+m.slice(1)}</button>)}</div><p className="secondary">Up to five rows, one save. Empty rows are ignored. Shared across all five workspaces.</p><div className="capture-rows">{rows.map((row,i)=><div className="capture-row" key={i}><label>{mode==='link'?'Label or URL':mode==='task'?'Task':'Note'} {i+1}<input aria-label={'Capture text '+(i+1)} maxLength={10000} value={row.text} onChange={e=>setRows(r=>r.map((x,n)=>n===i?{...x,text:e.target.value}:x))}/></label>{mode==='link'&&<label>URL<input aria-label={'Capture URL '+(i+1)} type="url" value={row.url} onChange={e=>setRows(r=>r.map((x,n)=>n===i?{...x,url:e.target.value}:x))}/></label>}{mode==='task'&&<label>Due<input aria-label={'Task due '+(i+1)} type="date" value={row.due} onChange={e=>setRows(r=>r.map((x,n)=>n===i?{...x,due:e.target.value}:x))}/></label>}<label className="inline-check"><input type="checkbox" aria-label={'Important row '+(i+1)} checked={row.important} onChange={e=>setRows(r=>r.map((x,n)=>n===i?{...x,important:e.target.checked}:x))}/>Important</label><button type="button" aria-label={'Remove capture row '+(i+1)} disabled={rows.length===1} onClick={()=>setRows(r=>r.filter((_,n)=>n!==i))}>Remove</button></div>)}</div><button type="button" disabled={rows.length>=5} onClick={()=>setRows([...rows,{text:'',url:'',due:'',important:false}])}>Add row</button><TaxonomyPicker catalogue={catalogue} overlays={store.state.overlays} value={taxonomy} onChange={setTaxonomy}/>{suggestion&&<button type="button" className="text-button" onClick={()=>setTaxonomy(suggestion)}>Use current classification: {taxonomyLabel(suggestion,catalogue,store.state.overlays)}</button>}<label className="inline-check"><input type="checkbox" checked={attach} disabled={!contextTarget} onChange={e=>setAttach(e.target.checked)}/>Attach current reading context</label>{contextTarget?<code className="capture-context">{JSON.stringify(contextTarget)}</code>:<p className="secondary">No active reading target.</p>}{error&&<p role="alert" className="error-message">{error}</p>}<div className="dialog-actions"><button type="button" onClick={onClose}>Cancel</button><button disabled={busy} className="primary">Save captures</button></div></form></Modal>;
}
export function ReferenceEditor({reference,catalogue,onClose,notify}:any){const [title,setTitle]=useState(reference.title),[taxonomy,setTaxonomy]=useState<TaxonomyRef|undefined>(reference.taxonomy),[error,setError]=useState('');return <Modal title="Edit Notebook reference" onClose={onClose}><p>Only this reference will change. The original resource is retained.</p><Field label="Reference title"><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200}/></Field><TaxonomyPicker catalogue={catalogue} overlays={store.state.overlays} value={taxonomy} onChange={setTaxonomy} required/>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><button onClick={()=>void store.overlays(o=>removeReference(o,reference.id)).then(()=>{notify('Reference removed. Original content retained.');onClose();}).catch(e=>setError(e.message))}>Remove reference only</button><button disabled={!taxonomy} onClick={()=>void store.overlays(o=>updateReference(o,reference.id,title,taxonomy!)).then(onClose).catch(e=>setError(e.message))}>Save reference</button></div></Modal>;}
export function CaptureEditor({item,catalogue,onClose}:any){const [text,setText]=useState(item.text),[taxonomy,setTaxonomy]=useState<TaxonomyRef|undefined>(item.taxonomy),[error,setError]=useState('');return <Modal title="Edit captured item" onClose={onClose}><Field label="Captured text"><textarea value={text} onChange={e=>setText(e.target.value)}/></Field><TaxonomyPicker catalogue={catalogue} overlays={store.state.overlays} value={taxonomy} onChange={setTaxonomy}/>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><button onClick={()=>void store.personal(p=>{const patch:any={text};if(taxonomy)patch.taxonomy=taxonomy;updateCapture(p,item.id,patch);if(!taxonomy)delete p.dashboardItems!.find(x=>x.id===item.id)!.taxonomy;}).then(onClose).catch(e=>setError(e.message))}>Save captured item</button></div></Modal>;}
