import React,{useState} from '../vendor/react.mjs';
import {Modal,Field} from '../components/Modal.js';
import {store} from '../storage/database.js';
import {uid} from '../core/workspace.js';
import type {ArticleSource,TaxonomyRef,QcmDocument} from './model.js';
import {parseContentJSON,validateArticleSource,validateQcm,validateTaxonomy} from './validation.mjs';
import {articlePage,articleExport,qcmPage,putContent,captureRows,downloadJSON,updateReference,removeReference,updateCapture} from './content.js';
import {QcmFields} from './QcmFields.js';
import {qcmAnswerModes,validateQcmDraftModes} from './qcm-draft.js';
import {contextLabel} from './context-label.js';
import {TaxonomyPicker} from './TaxonomyPicker.js';
import {dueAtFromDate} from './planning.js';
import {taxonomyLabel} from './taxonomy.js';
import {newCaptureDraft,removeDraftRow,appendDraftRow} from '../stabilization/capture-draft.js';
import type {CaptureDraft} from '../stabilization/capture-draft.js';
import {prepareSourceReplacement,sourceIdentity} from '../stabilization/resource-source.js';
export const qcmTemplate=():QcmDocument=>({schemaVersion:1,id:uid('qcm'),title:'New QCM set',questions:[{id:'q1',prompt:'Replace this prompt with your question.',options:[{id:'a',text:'First option',explanation:'Explain why this option is correct.'},{id:'b',text:'Second option',explanation:'Explain why this option is incorrect.'}],correctOptionIds:['a'],explanation:'Add the reasoning here.',followUp:'Add an optional follow-up.'}]});
export function ContentEditor({kind,page,catalogue,initialSource,initialTaxonomy,onClose,onOpen,notify,onBack}:any){
 const editing=!!page;
 const [originalIdentity]=useState(()=>page?sourceIdentity(catalogue,store.state,page):undefined);
 const [initial]=useState<any>(()=>kind==='qcm'?(page?.qcm??{...qcmTemplate(),...(initialTaxonomy?{taxonomy:initialTaxonomy}:{})}):(page?.article?articleExport(page):{id:uid('article'),title:'',sourceType:'article',status:'inbox',...(initialTaxonomy?{taxonomy:initialTaxonomy}:{}),...(initialSource??{})}));
 const [source,setSource]=useState<any>(initial),[raw,setRaw]=useState(JSON.stringify(initial,null,2)),[error,setError]=useState(''),[busy,setBusy]=useState(false),[jsonMode,setJsonMode]=useState(false),[replaceBody,setReplaceBody]=useState(!initial.blocks?.length||initial.blocks.length===1&&initial.blocks[0].type==='markdown');
 const [text,setText]=useState(initial.text??(initial.blocks?.length===1&&initial.blocks[0].type==='markdown'?initial.blocks[0].text:''));
 const [multiple,setMultiple]=useState<Record<string,boolean>>(()=>kind==='qcm'?qcmAnswerModes(initial):{});
 function change(k:string,v:any){setSource(s=>({...s,[k]:v}));}
 // In JSON mode the picker projects and edits the same draft that Save consumes.
 let taxonomySource=source,taxonomyError='';
 if(jsonMode&&kind==='articles'){try{taxonomySource=parseContentJSON(raw);if(!taxonomySource||typeof taxonomySource!=='object'||Array.isArray(taxonomySource))throw Error('Article JSON must be an object.');if(taxonomySource.taxonomy!==undefined)validateTaxonomy(taxonomySource.taxonomy);}catch{taxonomyError='Fix the Article JSON object and classification before using the visual classification picker.';}}
 function changeTaxonomy(value?:TaxonomyRef){const next={...taxonomySource};if(value)next.taxonomy=value;else delete next.taxonomy;if(jsonMode)setRaw(JSON.stringify(next,null,2));else setSource(next);}
 function visualSource(){if(kind==='qcm')return structuredClone(source);const v={...source};for(const k of ['url','publisher','note'])if(!v[k])delete v[k];if(replaceBody){delete v.blocks;delete v.text;if(text.length)v.text=text;}return v;}
 function changeMode(checked:boolean){try{if(checked){if(kind==='qcm')validateQcmDraftModes(source,multiple);setRaw(JSON.stringify(visualSource(),null,2));}else{const v=parseContentJSON(raw);if(kind==='qcm'){validateQcm(v);setMultiple(qcmAnswerModes(v));}else validateArticleSource(v);setSource(v);setText(v.text??(v.blocks?.length===1&&v.blocks[0].type==='markdown'?v.blocks[0].text:''));setReplaceBody(!v.blocks?.length||v.blocks.length===1&&v.blocks[0].type==='markdown');}setJsonMode(checked);setError('');}catch(e){setError((e as Error).message);}}
 async function load(file?:File){if(!file)return;try{if(file.size>4*1024*1024)throw Error('JSON file exceeds 4 MiB.');setRaw(await file.text());setJsonMode(true);setError('');}catch(e){setError((e as Error).message);}}
 async function save(e:any){e.preventDefault();setBusy(true);setError('');try{
  if(kind==='qcm'&&!jsonMode)validateQcmDraftModes(source,multiple);
  const value:any=jsonMode?parseContentJSON(raw):visualSource();
  if(editing&&value.id!==page.id)throw Error('An edit cannot change the resource ID. Import a new copy instead.');
  if(kind==='articles'){validateArticleSource(value);if(editing)value.updatedAt=Date.now();}else validateQcm(value);
  const result=kind==='qcm'?qcmPage(value):articlePage(value);
  if(editing){const next=prepareSourceReplacement(catalogue,store.state,page.id,JSON.stringify(value),originalIdentity);await store.overlays(o=>Object.assign(o,next));}
  else await store.overlays(o=>putContent(o,result,catalogue,false));
  onClose();onOpen(result.id);notify((editing?'Saved ':'Created ')+result.title+'.');
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const jsonField=<Field label={kind==='qcm'?'QCM JSON':'Article JSON'}><textarea aria-label={kind==='qcm'?'QCM JSON':'Article JSON'} spellCheck={false} rows={18} value={raw} onChange={e=>setRaw(e.target.value)}/></Field>;
 return <Modal wide title={(editing?'Edit ':'New/import ')+(kind==='qcm'?'QCM':'article')} onClose={onClose}><form onSubmit={save} className="hub-editor">
 {onBack&&<button type="button" className="capture-back" onClick={()=>{let draft=visualSource();if(jsonMode){try{draft=parseContentJSON(raw);}catch{draft={...draft};}}onBack(draft);}}>Back to Quick Capture</button>}
 <p className="secondary">Private local content. Source URLs are links, never automatically fetched or embedded.</p>
 {kind==='qcm'?<>{!jsonMode&&<><QcmFields source={source} onChange={setSource} multiple={multiple} onModeChange={(id,value)=>setMultiple(m=>({...m,[id]:value}))}/><TaxonomyPicker catalogue={catalogue} overlays={store.state.overlays} value={source.taxonomy} onChange={v=>{const next={...source};if(v)next.taxonomy=v;else delete next.taxonomy;setSource(next);}}/></>}<label className="inline-check"><input type="checkbox" checked={jsonMode} onChange={e=>changeMode(e.target.checked)}/>Edit canonical JSON</label><Field label="Import JSON file"><input type="file" aria-label="Content JSON file" accept=".json,application/json" onChange={e=>void load(e.target.files?.[0])}/></Field>{jsonMode&&jsonField}</>:<>
 <div className="article-primary"><Field label="Title"><input aria-label="Title" required={!jsonMode} maxLength={200} value={source.title} disabled={jsonMode} onChange={e=>change('title',e.target.value)}/></Field><Field label="Source URL"><input aria-label="Source URL" type="url" value={source.url??''} disabled={jsonMode} onChange={e=>change('url',e.target.value)}/></Field>
 <TaxonomyPicker disabled={!!taxonomyError} catalogue={catalogue} overlays={store.state.overlays} value={taxonomyError?undefined:taxonomySource.taxonomy} onChange={changeTaxonomy}/>{taxonomyError&&<p className="secondary">{taxonomyError}</p>}
 {!jsonMode&&(initial.blocks?.length>0&&!replaceBody?<p>This article has structured blocks. They are preserved. Expand Advanced / JSON to edit them, or <button type="button" onClick={()=>setReplaceBody(true)}>Replace body with pasted text</button>.</p>:<Field label="Pasted article or transcript"><textarea aria-label="Pasted article or transcript" rows={12} value={text} onChange={e=>setText(e.target.value)} placeholder="Paste text or safe Markdown. No remote HTML is fetched."/></Field>)}
 </div>
 <details className="article-advanced" open={jsonMode||undefined}><summary>Advanced / JSON</summary>
 <div className="hub-form-grid"><Field label="Publisher"><input aria-label="Publisher" value={source.publisher??''} disabled={jsonMode} onChange={e=>change('publisher',e.target.value)}/></Field><Field label="Source type"><select aria-label="Source type" value={source.sourceType??'article'} disabled={jsonMode} onChange={e=>change('sourceType',e.target.value)}>{['link','article','transcript','documentation'].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Article status"><select aria-label="Article status" value={source.status??'inbox'} disabled={jsonMode} onChange={e=>change('status',e.target.value)}>{['inbox','unread','reading','finished'].map(t=><option key={t}>{t}</option>)}</select></Field><label className="inline-check"><input type="checkbox" checked={source.important??false} disabled={jsonMode} onChange={e=>change('important',e.target.checked)}/>Important</label></div>
 <Field label="Personal article note"><textarea aria-label="Personal article note" rows={2} value={source.note??''} disabled={jsonMode} onChange={e=>change('note',e.target.value)}/></Field>
 <Field label="Import JSON file"><input type="file" aria-label="Content JSON file" accept=".json,application/json" onChange={e=>void load(e.target.files?.[0])}/></Field><label className="inline-check"><input type="checkbox" checked={jsonMode} onChange={e=>changeMode(e.target.checked)}/>Edit canonical JSON</label>{jsonMode&&jsonField}
 </details></>}
 {error&&<p role="alert" className="error-message">{error}</p>}<div className="dialog-actions"><button type="button" onClick={onClose}>Cancel</button>{editing&&<button type="button" onClick={()=>downloadJSON(kind==='qcm'?page.qcm:articleExport(page),page.id+'.json')}>Export source</button>}<button type="submit" className="primary" disabled={busy}>{editing?'Save content':'Import local content'}</button></div>{onBack&&<small className="secondary">Back keeps the capture draft. Cancel discards this entire unsaved capture flow; nothing is saved until you submit.</small>}</form></Modal>;
}
export function QuickCapture({catalogue,contextTarget,suggestion,onClose,notify,onArticle,initialDraft}:any){
 const [draft,setDraft]=useState<CaptureDraft>(()=>structuredClone(initialDraft??newCaptureDraft())),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const {mode,rows,taxonomy,attach}=draft;
 function rowChange(i:number,patch:any){setDraft(d=>({...d,rows:d.rows.map((r,n)=>n===i?{...r,...patch}:r)}));}
 async function save(e:any){e.preventDefault();setBusy(true);try{await store.personal(p=>captureRows(p,mode,rows,taxonomy,attach?contextTarget:undefined));notify('Saved to the shared Dashboard.');onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function choose(m:any){if(m==='article'||m==='transcript'){onArticle({sourceType:m,...(taxonomy?{taxonomy}:{}),...(attach&&contextTarget?{contextTarget}:{})},structuredClone(draft));return;}setDraft(d=>({...d,mode:m}));setError('');}
 return <Modal wide title="Quick Capture" onClose={onClose}><form onSubmit={save}><div className="capture-modes" role="group" aria-label="Capture type">{['link','task','note','article','transcript'].map(m=><button type="button" key={m} aria-pressed={mode===m} onClick={()=>choose(m)}>{m[0].toUpperCase()+m.slice(1)}</button>)}</div><p className="secondary">Three to five draft rows, one save. Empty rows are ignored. Shared across all five workspaces.</p>
 <div className="capture-rows">{rows.map((row,i)=><div className="capture-row" key={i}><label>{mode==='link'?'Label or URL':mode==='task'?'Task':'Note'} {i+1}<input aria-label={'Capture text '+(i+1)} maxLength={10000} value={row.text} onChange={e=>rowChange(i,{text:e.target.value})}/></label>{mode==='link'&&<label>URL<input aria-label={'Capture URL '+(i+1)} type="url" value={row.url??''} onChange={e=>rowChange(i,{url:e.target.value})}/></label>}{mode==='task'&&<label>Due<input aria-label={'Task due '+(i+1)} type="date" value={row.due??''} onChange={e=>rowChange(i,{due:e.target.value})}/></label>}<label className="inline-check"><input type="checkbox" aria-label={'Important row '+(i+1)} checked={row.important??false} onChange={e=>rowChange(i,{important:e.target.checked})}/>Important</label><button type="button" aria-label={'Remove capture row '+(i+1)} disabled={rows.length<=3} onClick={()=>setDraft(d=>removeDraftRow(d,i))}>Remove</button></div>)}</div>
 <button type="button" disabled={rows.length>=5} onClick={()=>setDraft(appendDraftRow)}>Add row</button><TaxonomyPicker catalogue={catalogue} overlays={store.state.overlays} value={taxonomy} onChange={v=>setDraft(d=>{const next={...d};if(v)next.taxonomy=v;else delete next.taxonomy;return next;})}/>{suggestion&&<button type="button" className="text-button" onClick={()=>setDraft(d=>({...d,taxonomy:suggestion}))}>Use current classification: {taxonomyLabel(suggestion,catalogue,store.state.overlays)}</button>}<label className="inline-check"><input type="checkbox" checked={attach} disabled={!contextTarget} onChange={e=>setDraft(d=>({...d,attach:e.target.checked}))}/>Attach current reading context</label>{contextTarget?<p className="capture-context">{attach?'Attached: ':'Available context (not attached): '}{contextLabel(catalogue,store.state,contextTarget)}</p>:<p className="secondary">No active reading target.</p>}{error&&<p role="alert" className="error-message">{error}</p>}<div className="dialog-actions"><button type="button" onClick={onClose}>Cancel</button><button disabled={busy} className="primary">Save captures</button></div></form></Modal>;
}
export function ReferenceEditor({reference,catalogue,onClose,notify}:any){const [title,setTitle]=useState(reference.title),[taxonomy,setTaxonomy]=useState<TaxonomyRef|undefined>(reference.taxonomy),[error,setError]=useState('');return <Modal title="Edit Notebook reference" onClose={onClose}><p>Only this reference will change. The original resource is retained.</p><Field label="Reference title"><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200}/></Field><TaxonomyPicker catalogue={catalogue} overlays={store.state.overlays} value={taxonomy} onChange={setTaxonomy} required/>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><button onClick={()=>void store.overlays(o=>removeReference(o,reference.id)).then(()=>{notify('Reference removed. Original content retained.');onClose();}).catch(e=>setError(e.message))}>Remove reference only</button><button disabled={!taxonomy} onClick={()=>void store.overlays(o=>updateReference(o,reference.id,title,taxonomy!)).then(onClose).catch(e=>setError(e.message))}>Save reference</button></div></Modal>;}
export function CaptureEditor({item,catalogue,onClose}:any){
 const [text,setText]=useState(item.text),[taxonomy,setTaxonomy]=useState<TaxonomyRef|undefined>(item.taxonomy),[due,setDue]=useState<string>(item.dueAt!==undefined?new Date(item.dueAt).toISOString().slice(0,10):''),[important,setImportant]=useState<boolean>(!!item.important),[error,setError]=useState('');
 // Due date and priority reuse the capture's own dueAt/important fields; clearing a date leaves the task unscheduled.
 // Promise.resolve keeps synchronous validation errors (bad date, secret guard) in the visible alert.
 function save(){void Promise.resolve().then(()=>store.personal(p=>{const patch:any={text};if(taxonomy)patch.taxonomy=taxonomy;if(item.kind==='task'&&due)patch.dueAt=dueAtFromDate(due);if(important)patch.important=true;updateCapture(p,item.id,patch);const saved=p.dashboardItems!.find(x=>x.id===item.id)!;if(!taxonomy)delete saved.taxonomy;if(item.kind==='task'&&!due)delete saved.dueAt;if(!important)delete saved.important;})).then(onClose).catch(e=>setError(e.message));}
 return <Modal title="Edit captured item" onClose={onClose}><Field label="Captured text"><textarea value={text} onChange={e=>setText(e.target.value)}/></Field>{item.kind==='task'&&<div className="capture-schedule"><label>Due date<input type="date" aria-label="Capture due date" value={due} onChange={e=>setDue(e.target.value)}/></label>{due&&<button type="button" onClick={()=>setDue('')}>Clear date</button>}</div>}<label className="inline-check"><input type="checkbox" aria-label="Capture important" checked={important} onChange={e=>setImportant(e.target.checked)}/>Important</label>{item.origin&&<p className="secondary">Imported from Power Ops ({item.origin.objectId}). Edits here are kept on the next import unless you choose to replace them.</p>}<TaxonomyPicker catalogue={catalogue} overlays={store.state.overlays} value={taxonomy} onChange={setTaxonomy}/>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><button onClick={save}>Save captured item</button></div></Modal>;
}
