import React,{useState,useEffect} from '../vendor/react.mjs';
import {store} from '../storage/database.js';
import {LIBRARY_TYPES,subjectFromCategory} from './model.js';
import type {TaxonomyRef} from './model.js';
import {removeLocalContent,libraryModeForPage,downloadJSON,addNotebookReference,currentResourceTarget} from './content.js';
import {resourceTaxonomy,sharedFolders,taxonomyLabel,scopeMatches,targetId} from './taxonomy.js';
import {targetForPage} from '../core/reading-lists.js';
import {isArchived,newLocation} from '../core/workspace.js';
import {TaxonomyPicker} from './TaxonomyPicker.js';
import {requireExact} from '../references/targets.js';
import {RESOURCE_DRAG_TYPE,encodeResourceDrag,parseResourceDrag,referenceDrop} from '../stabilization/resource-drag.js';
import {resourceSource,sourceIdentity,prepareSourceReplacement,SOURCE_JSON_LIMIT} from '../stabilization/resource-source.js';
/** Source management and explicit Notebook destinations are two views of the existing data, not copies. */
export function LibraryManager({catalogue,workspace,session,selectedResource,onSelectResource,onAdd,onEdit,onOpen,onActions,onClose,onPdfManage,notify}:any){
 const mode=session.libraryMode??'pdfs',subject=subjectFromCategory(session.categoryFilter),folders=sharedFolders(catalogue,workspace.overlays);
 const [selected,setSelected]=useState(selectedResource??''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[unfiled,setUnfiled]=useState(false),[archived,setArchived]=useState(false),[important,setImportant]=useState(false),[taxonomy,setTaxonomy]=useState<TaxonomyRef|undefined>(undefined),[destination,setDestination]=useState<TaxonomyRef|undefined>(undefined),[error,setError]=useState(''),[view,setView]=useState<'visual'|'json'>('visual'),[raw,setRaw]=useState(''),[loadedIdentity,setLoadedIdentity]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(selectedResource!==undefined)setSelected(selectedResource);},[selectedResource]);
 const pages=catalogue.pages.filter(p=>libraryModeForPage(catalogue,p.id)===mode).filter(p=>{
  const tax=resourceTaxonomy(catalogue,workspace.overlays,p.id);return (archived||!isArchived(p.id,catalogue,workspace.overlays))&&scopeMatches(tax,subject,session.libraryFolder,folders)&&(!query||p.title.toLowerCase().includes(query.toLowerCase()))&&(!status||(p.article?.status??'inbox')===status)&&(!important||p.article?.important)&&(!unfiled||!tax?.folderId||!folders.some(f=>f.id===tax.folderId));
 }).sort((a,b)=>(b.article?.addedAt??0)-(a.article?.addedAt??0));
 const page=catalogue.pages.find(p=>p.id===selected&&libraryModeForPage(catalogue,p.id)===mode),type=LIBRARY_TYPES.find(t=>t.id===mode)!;
 function loadJSON(){if(!page)return;setRaw(JSON.stringify(resourceSource(catalogue,workspace,page),null,2));setLoadedIdentity(sourceIdentity(catalogue,workspace,page));setError('');}
 useEffect(()=>{setTaxonomy(page?resourceTaxonomy(catalogue,workspace.overlays,page.id):undefined);loadJSON();},[page?.id]);
 async function run(fn:any,message?:string){try{setError('');await fn();if(message)notify(message);}catch(e){setError((e as Error).message);}}
 function target(){return page?currentResourceTarget(catalogue,newLocation(page.id))!:undefined;}
 function choose(id:string){setSelected(id);setError('');if(onSelectResource)onSelectResource(id);}
 function receive(e:any){e.preventDefault();e.stopPropagation();void run(()=>{const value=parseResourceDrag(e.dataTransfer.getData(RESOURCE_DRAG_TYPE),catalogue,store.state);choose(targetId(value.target));});}
 async function link(t:any,title:string,dest?:TaxonomyRef){if(!dest?.folderId||!folders.some(f=>f.id===dest.folderId&&f.subject===dest.subject))throw Error('Choose an existing Notebook folder destination.');requireExact(catalogue,store.state,t);await store.overlays(o=>{addNotebookReference(o,t,title,dest);});notify('Notebook reference added. Original resource unchanged.');}
 function folderDrop(e:any,folderId:string){e.preventDefault();e.stopPropagation();void run(async()=>{const drop=referenceDrop(e.dataTransfer.getData(RESOURCE_DRAG_TYPE),catalogue,store.state,folderId);await link(drop.target,drop.title,drop.taxonomy);});}
 function dragOver(e:any){if(e.dataTransfer.types.includes(RESOURCE_DRAG_TYPE)){e.preventDefault();e.dataTransfer.dropEffect='copy';}}
 async function importJSON(file?:File){if(!file)return;await run(async()=>{if(file.size>SOURCE_JSON_LIMIT)throw Error('Source JSON exceeds 4 MiB.');setRaw(await file.text());setView('json');});}
 async function applyJSON(){if(!page)return;setBusy(true);try{await run(async()=>{const next=prepareSourceReplacement(catalogue,store.state,page.id,raw,loadedIdentity);await store.overlays(o=>Object.assign(o,next));const changed=next.pages[page.id].page,nextC={...catalogue,pages:catalogue.pages.map(p=>p.id===page.id?changed:p),documents:catalogue.documents.map(d=>d.pageId===page.id?{...d,title:changed.title}:d)},nextWs={...store.state,overlays:next};setRaw(JSON.stringify(resourceSource(nextC,nextWs,changed),null,2));setLoadedIdentity(sourceIdentity(nextC,nextWs,changed));},'Validated source applied. Stable reference targets preserved.');}finally{setBusy(false);}}
 async function copyJSON(){await run(async()=>{if(!navigator.clipboard?.writeText)throw Error('Clipboard is unavailable here. Select the JSON text or use Export JSON.');await navigator.clipboard.writeText(raw);},'JSON copied.');}
 return <main className="library-management" aria-label={type.label+' management'}><header className="hub-surface-header"><div><small>SHARED TAXONOMY / LOCAL RESOURCES</small><h1>{type.label} library</h1><p>Drag a source from the left tree. Notebook placement creates a reference, never a duplicate.</p></div><div className="button-row"><button className="primary" onClick={()=>onAdd(mode)}>{type.add}</button><button onClick={onClose}>Return to reader</button></div></header>
 <div className="library-manager-layout">
 <section className="notebook-targets" aria-label="Notebook destination tree"><h2>Add to Notebook</h2><p>References keep the original source and its exact reading target.</p><TaxonomyPicker label="Reference destination" catalogue={catalogue} overlays={workspace.overlays} value={destination} onChange={setDestination}/><button disabled={!page||!destination?.folderId} onClick={()=>void run(()=>link(target(),page!.title,destination))}>Add reference to Notebook</button><nav aria-label="Notebook target folders">{folders.map(f=><button key={f.id} className="notebook-target-folder" style={{paddingLeft:12+Math.min(f.path.length-1,6)*12}} aria-pressed={destination?.folderId===f.id} onClick={()=>setDestination({subject:f.subject,folderId:f.id,path:[...f.path]})} onDragOver={dragOver} onDrop={e=>folderDrop(e,f.id)}>{f.path.length===1?f.subject.toUpperCase()+' / ':''}{f.title}</button>)}</nav>{!folders.length&&<p>Create a Notebook folder in a subject first.</p>}</section>
 <section className="resource-management" aria-label="Resource workspace" onDragOver={dragOver} onDrop={receive}>
 <details className="resource-browser"><summary>Choose resource</summary><div className="management-filters"><label>Find resource<input aria-label="Find library resource" value={query} onChange={e=>setQuery(e.target.value)}/></label>{mode==='articles'&&<><label>Status<select aria-label="Filter article status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['inbox','unread','reading','finished'].map(s=><option key={s}>{s}</option>)}</select></label><label className="inline-check"><input type="checkbox" checked={important} onChange={e=>setImportant(e.target.checked)}/>Important only</label></>}<label className="inline-check"><input type="checkbox" checked={unfiled} onChange={e=>setUnfiled(e.target.checked)}/>Unfiled only</label><label className="inline-check"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived</label></div><p className="secondary">{pages.length} matching resources.</p><label>Browse<select aria-label="Selected library resource" value={pages.some(p=>p.id===selected)?selected:''} onChange={e=>choose(e.target.value)}><option value="">Choose a resource</option>{pages.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label></details>
 {page?<article className="managed-resource" data-resource-id={page.id} draggable onDragStart={e=>{if((e.target as HTMLElement).closest('textarea,input,select,button')){e.preventDefault();return;}e.dataTransfer.setData(RESOURCE_DRAG_TYPE,encodeResourceDrag(targetForPage(catalogue,page.id),page.title));e.dataTransfer.effectAllowed='copy';}}><header><small className="resource-kind-badge">{type.label}</small><h2>{page.title}</h2>{isArchived(page.id,catalogue,workspace.overlays)&&<p className="secondary">Archived resource - existing references are retained.</p>}<code className="resource-stable-id">{page.id}</code></header><div className="resource-mode-switch" role="group" aria-label="Resource editing mode"><button aria-pressed={view==='visual'} onClick={()=>setView('visual')}>Visual</button><button aria-pressed={view==='json'} onClick={()=>setView('json')}>JSON</button></div>
 {view==='json'?<section className="resource-json"><p className="secondary">{mode==='pdfs'?'Metadata and companion only. PDF binary, source identity and rights are read-only.':'Canonical source JSON. Changes are validated before a single atomic update.'}</p><label>Canonical source<textarea aria-label="Resource source JSON" rows={20} spellCheck={false} value={raw} onChange={e=>setRaw(e.target.value)}/></label><div className="button-row"><button onClick={()=>void copyJSON()}>Copy JSON</button><button onClick={()=>void run(()=>{const value=JSON.parse(raw);downloadJSON(value,page.id+'.json');})}>Export JSON</button><label className="json-import-label">Import / Replace JSON<input type="file" aria-label="Import / Replace resource JSON" accept=".json,application/json" onChange={e=>void importJSON(e.target.files?.[0])}/></label><button disabled={busy} className="primary" onClick={()=>void applyJSON()}>Apply validated JSON</button><button onClick={()=>{if(confirm('Discard this JSON draft and reload the current source?'))loadJSON();}}>Reload source JSON</button></div></section>:<section className="resource-visual"><p>{page.summary}</p><p>{taxonomyLabel(resourceTaxonomy(catalogue,workspace.overlays,page.id),folders)}</p>
 {page.article&&<><p>Source: {page.article.publisher??'Not supplied'}</p>{page.article.url&&<a href={page.article.url} target="_blank" rel="noopener noreferrer">Open original link</a>}<p>{page.article.note}</p><label>Reading status<select aria-label="Managed article status" value={page.article.status??'inbox'} onChange={e=>void run(()=>store.overlays(o=>{const p=structuredClone(o.pages[page.id]?.page??page);p.article!.status=e.target.value as any;p.article!.updatedAt=Date.now();o.pages[page.id]={...o.pages[page.id],page:p};}))}>{['inbox','unread','reading','finished'].map(s=><option key={s}>{s}</option>)}</select></label><p>{page.blocks.find(b=>b.type==='markdown')?.text?.slice(0,700)}</p></>}
 {page.qcm&&<div className="resource-questions">{page.qcm.questions.slice(0,3).map(q=><details key={q.id}><summary>{q.prompt}</summary><p>{q.explanation}</p><ul>{q.options.map(o=><li key={o.id}>{o.text} <small>{o.explanation}</small></li>)}</ul></details>)}</div>}
 {page.cheatsheet&&<div className="resource-sheet-list">{page.cheatsheet.pages.map((p,i)=><div key={p.id}><strong>Page {i+1}</strong><span>{p.title??p.id}</span><small>{p.blocks.length} structured blocks</small></div>)}</div>}
 {mode==='pdfs'&&<p>{catalogue.documents.find(d=>d.pageId===page.id)?.pageCount??'Unknown count of'} physical pages. Rendering and page navigation remain in the PDF reader.</p>}
 <TaxonomyPicker catalogue={catalogue} overlays={workspace.overlays} value={taxonomy} onChange={setTaxonomy}/><button onClick={()=>void run(()=>store.overlays(o=>{o.taxonomy??={};o.taxonomy[page.id]=taxonomy?structuredClone(taxonomy):null;}),'Classification saved without changing source metadata.')}>Save classification</button></section>}
 <div className="button-row resource-source-actions"><button onClick={()=>onOpen(target())}>Read resource</button><button onClick={e=>onActions(target(),page.title,e)}>Reading actions</button><button onClick={()=>mode==='pdfs'?onPdfManage(catalogue.documents.find(d=>d.pageId===page.id)):onEdit(page)}>Edit / details</button><button onClick={()=>downloadJSON(resourceSource(catalogue,workspace,page),page.id+'.json')}>{mode==='pdfs'?'Export PDF metadata':'Export source'}</button><button onClick={()=>void run(()=>store.overlays(o=>{o.archived=isArchived(page.id,catalogue,o)?o.archived.filter(id=>id!==page.id):[...new Set([...o.archived,page.id])];}),'Archive status updated. Content and references retained.')}>{isArchived(page.id,catalogue,workspace.overlays)?'Restore resource':'Archive resource'}</button>{['articles','qcm'].includes(mode)&&workspace.overlays.pages[page.id]&&!catalogue.packs.some(pack=>pack.pages.some(p=>p.id===page.id))&&<button className="danger" onClick={()=>{if(confirm('Remove this local source? Bookmarks, Notebook references and attempt history will remain as unavailable targets. Export a backup first.'))void run(()=>store.overlays(o=>removeLocalContent(o,catalogue,page.id)),'Source removed; shared history retained.');}}>Remove local source</button>}</div></article>:<div className="resource-drop-empty"><h2>Drop a resource from the tree</h2><p>Drag a {type.label.toLowerCase()} here, use a tree row's Manage button, or expand Choose resource. Source files stay in their library.</p></div>}
 {error&&<p className="error-message" role="alert">{error}</p>}</section></div></main>;
}
