import React,{useState,useEffect} from '../vendor/react.mjs';
import {store} from '../storage/database.js';
import {LIBRARY_TYPES,subjectFromCategory} from './model.js';
import type {TaxonomyRef} from './model.js';
import {removeLocalContent,libraryModeForPage,articleExport,downloadJSON,addNotebookReference,currentResourceTarget} from './content.js';
import {resourceTaxonomy,sharedFolders,taxonomyLabel,scopeMatches} from './taxonomy.js';
import {targetForPage} from '../core/reading-lists.js';
import {isArchived,newLocation} from '../core/workspace.js';
import {TaxonomyPicker} from './TaxonomyPicker.js';
import {validateReadingTarget} from '../storage/reading-validation.mjs';
/** Management data and a destination Notebook tree, not two competing library trees. */
export function LibraryManager({catalogue,workspace,session,onAdd,onEdit,onOpen,onActions,onClose,onPdfManage,notify}:any){
 const mode=session.libraryMode??'pdfs',subject=subjectFromCategory(session.categoryFilter),folders=sharedFolders(catalogue,workspace.overlays),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[unfiled,setUnfiled]=useState(false),[archived,setArchived]=useState(false),[important,setImportant]=useState(false),[taxonomy,setTaxonomy]=useState<TaxonomyRef|undefined>(undefined),[destination,setDestination]=useState<TaxonomyRef|undefined>(undefined),[error,setError]=useState('');
 const pages=catalogue.pages.filter(p=>libraryModeForPage(catalogue,p.id)===mode).filter(p=>{
  const tax=resourceTaxonomy(catalogue,workspace.overlays,p.id);return (archived||!isArchived(p.id,catalogue,workspace.overlays))&&scopeMatches(tax,subject,session.libraryFolder,folders)&&(!query||p.title.toLowerCase().includes(query.toLowerCase()))&&(!status||(p.article?.status??'inbox')===status)&&(!important||p.article?.important)&&(!unfiled||!tax?.folderId||!folders.some(f=>f.id===tax.folderId));
 }).sort((a,b)=>(b.article?.addedAt??0)-(a.article?.addedAt??0));
 const page=pages.find(p=>p.id===selected)??pages[0],type=LIBRARY_TYPES.find(t=>t.id===mode)!;
 useEffect(()=>{setTaxonomy(page?resourceTaxonomy(catalogue,workspace.overlays,page.id):undefined);},[page?.id,workspace.overlays.taxonomy]);
 async function run(fn:any,message?:string){try{setError('');await fn();if(message)notify(message);}catch(e){setError((e as Error).message);}}
 function target(){return page?currentResourceTarget(catalogue,newLocation(page.id))!:undefined;}
 async function link(t:any,title:string,dest?:TaxonomyRef){if(!dest?.folderId)throw Error('Choose a Notebook folder destination.');validateReadingTarget(t);await store.overlays(o=>{addNotebookReference(o,t,title,dest);});notify('Notebook reference added. Original resource unchanged.');}
 function sourceExport(){if(!page)return;if(page.qcm)downloadJSON(page.qcm,page.id+'.json');else if(page.article)downloadJSON(articleExport(page),page.id+'.json');else if(page.cheatsheet)downloadJSON(page.cheatsheet,page.id+'.json');else {const doc=catalogue.documents.find(d=>d.pageId===page.id);if(doc)downloadJSON(doc,page.id+'-metadata.json');}}
 return <main className="library-management" aria-label={type.label+' management'}><header className="hub-surface-header"><div><small>SHARED TAXONOMY / LOCAL RESOURCES</small><h1>{type.label} library</h1><p>Manage this content type, then place explicit references in your Notebook.</p></div><div className="button-row"><button className="primary" onClick={()=>onAdd(mode)}>{type.add}</button><button onClick={onClose}>Return to reader</button></div></header><div className="library-manager-layout"><section className="resource-management"><div className="management-filters"><label>Find resource<input aria-label="Find library resource" value={query} onChange={e=>setQuery(e.target.value)}/></label>{mode==='articles'&&<><label>Status<select aria-label="Filter article status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['inbox','unread','reading','finished'].map(s=><option key={s}>{s}</option>)}</select></label><label className="inline-check"><input type="checkbox" checked={important} onChange={e=>setImportant(e.target.checked)}/>Important only</label></>}<label className="inline-check"><input type="checkbox" checked={unfiled} onChange={e=>setUnfiled(e.target.checked)}/>Unfiled only</label><label className="inline-check"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived</label></div><p className="secondary">{pages.length} resources. Articles are ordered newest first.</p><label className="field"><span>Selected resource</span><select aria-label="Selected library resource" value={page?.id??''} onChange={e=>setSelected(e.target.value)}>{!pages.length&&<option value="">No matching resource</option>}{pages.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>{page?<article className="managed-resource" draggable onDragStart={e=>{e.dataTransfer.setData('application/x-atlas-resource',JSON.stringify({target:target(),title:page.title}));e.dataTransfer.effectAllowed='copy';}}><h2>{page.title}</h2><small className="resource-kind-badge">{type.label}</small><p>{page.summary}</p><p>{taxonomyLabel(resourceTaxonomy(catalogue,workspace.overlays,page.id),folders)}</p>{page.article&&<><p>Source: {page.article.publisher??'Not supplied'} / Added {new Date(page.article.addedAt).toLocaleDateString()}</p>{page.article.url&&<a href={page.article.url} target="_blank" rel="noopener noreferrer">Open original link</a>}<p>{page.article.note}</p><label>Reading status<select aria-label="Managed article status" value={page.article.status??'inbox'} onChange={e=>void run(()=>store.overlays(o=>{const p=structuredClone(o.pages[page.id]?.page??page);p.article!.status=e.target.value as any;p.article!.updatedAt=Date.now();o.pages[page.id]={...o.pages[page.id],page:p};}))}>{['inbox','unread','reading','finished'].map(s=><option key={s}>{s}</option>)}</select></label></>}
 <TaxonomyPicker catalogue={catalogue} overlays={workspace.overlays} value={taxonomy} onChange={setTaxonomy}/><button onClick={()=>void run(()=>store.overlays(o=>{o.taxonomy??={};if(taxonomy)o.taxonomy[page.id]=structuredClone(taxonomy);else o.taxonomy[page.id]=null;}),'Classification saved without changing the source metadata.')}>Save classification</button><div className="button-row"><button onClick={()=>onOpen(target())}>Read resource</button><button onClick={e=>onActions(target(),page.title,e)}>Reading actions</button><button onClick={()=>mode==='pdfs'?onPdfManage(catalogue.documents.find(d=>d.pageId===page.id)):onEdit(page)}>Edit / details</button><button onClick={sourceExport}>{mode==='pdfs'?'Export PDF metadata':'Export source'}</button><button onClick={()=>void run(()=>store.overlays(o=>{o.archived=isArchived(page.id,catalogue,o)?o.archived.filter(id=>id!==page.id):[...new Set([...o.archived,page.id])];}),'Archive status updated. Content and references retained.')}>{isArchived(page.id,catalogue,workspace.overlays)?'Restore resource':'Archive resource'}</button>{['articles','qcm'].includes(mode)&&workspace.overlays.pages[page.id]&&!catalogue.packs.some(pack=>pack.pages.some(p=>p.id===page.id))&&<button className="danger" onClick={()=>{if(confirm('Remove this local source? Bookmarks, Notebook references and attempt history will be retained as unavailable targets. Export a backup first.'))void run(()=>store.overlays(o=>removeLocalContent(o,catalogue,page.id)),'Source removed; references and shared personal history retained.');}}>Remove local source</button>}</div></article>:<div className="empty-state"><h2>No matching {type.label.toLowerCase()} resources</h2><p>Add a source or change the subject/filter. Unmatched legacy resources remain under Unfiled.</p></div>}{error&&<p className="error-message" role="alert">{error}</p>}</section>
 <section className="notebook-targets" aria-label="Notebook destination tree"><h2>Add to Notebook</h2><p>A reference points to its original source. Drag the resource onto a folder, or choose a destination below.</p><TaxonomyPicker label="Reference destination" catalogue={catalogue} overlays={workspace.overlays} value={destination} onChange={setDestination}/><button disabled={!page||!destination?.folderId} onClick={()=>void run(()=>link(target(),page!.title,destination))}>Add reference to Notebook</button><nav aria-label="Notebook target folders">{folders.map(f=><button key={f.id} className="notebook-target-folder" style={{paddingLeft:12+Math.min(f.path.length-1,6)*12}} aria-pressed={destination?.folderId===f.id} onClick={()=>setDestination({subject:f.subject,folderId:f.id,path:[...f.path]})} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';}} onDrop={e=>{e.preventDefault();void run(async()=>{const raw=e.dataTransfer.getData('application/x-atlas-resource');if(raw.length>20000)throw Error('Invalid dropped reference.');const v=JSON.parse(raw);validateReadingTarget(v.target);await link(v.target,v.title,{subject:f.subject,folderId:f.id,path:[...f.path]});});}}>{f.path.length===1?f.subject.toUpperCase()+' / ':''}{f.title}</button>)}</nav>{!folders.length&&<p>Create a Notebook folder in a subject first.</p>}</section></div></main>;
}
