import React,{useEffect,useState} from '../vendor/react.mjs';
import type {DocumentEntry,Location} from '../core/model.js';import {Icon} from '../components/Icon.js';
/** The offline build never mislabels an iframe as an integrated PDF engine.
 * The optional separately installed engine is injected by the Vite online entry. */
export function PdfReader({document:doc,location,onLocation,resolve,fetchBytes}: {document:DocumentEntry;location:Location;onLocation:any;resolve:(key:string)=>string|undefined;fetchBytes:(key:string)=>Promise<Uint8Array>}){
 const [adapter,setAdapter]=useState<any>(null),[error,setError]=useState(''),[consent,setConsent]=useState(false),[show,setShow]=useState(false),[url,setUrl]=useState<string|undefined>(undefined);
 useEffect(()=>{let active=true;if(window.atlasPdfLoader)window.atlasPdfLoader().then(m=>{if(active)setAdapter(()=>m.PdfEngine);}).catch(e=>setError('Optional PDF engine failed to load: '+e.message));return()=>{active=false;};},[]);
 useEffect(()=>{setUrl(doc.assetKey?resolve(doc.assetKey):undefined);setShow(false);setConsent(false);},[doc.id,doc.sha256]);
 const external=doc.source.kind==='https'||doc.source.kind==='external-link';
 if(adapter){const Component=adapter;return <Component document={doc} location={location} onLocation={onLocation} url={external?(consent?doc.source.url:undefined):url} requestExternal={()=>setConsent(true)}/>;}
 return <div className="pdf-reader"><div className="pdf-intro"><div className="eyebrow">PDF DOCUMENT</div><h1>{doc.title}</h1><p>{doc.rights.attribution}</p><div className="pdf-engine-notice" role="status"><Icon name="help"/><div><strong>Browser preview only in this offline build</strong><p>The integrated PDF engine is not bundled. Atlas page navigation, selectable-text search, rotation and physical-page spreads are unavailable here. Your original PDF bytes are preserved in imports and backups.</p></div></div>{error&&<p role="alert">{error}</p>}
 {external&&!consent?<div className="callout"><p>Opening this PDF contacts its external host. The full URL is shown before any request.</p><code>{doc.source.url}</code><button onClick={()=>{setConsent(true);setUrl(doc.source.url);}}>Allow external PDF reference</button></div>:url?<div className="button-row"><button className="primary" onClick={()=>setShow(v=>!v)}>{show?'Hide browser preview':'Show browser PDF preview'}</button><a className="button" href={url} target="_blank" rel="noopener noreferrer">Open original PDF</a><a className="button" href={url} download={doc.title+'.pdf'}>Download original</a></div>:<div className="callout warning"><strong>PDF bytes are unavailable</strong><p>This document is a reference to a local library file that has not been imported. Import the original PDF through Settings. Atlas does not invent its pages.</p></div>}
 <details className="pdf-metadata"><summary>Document identity &amp; provenance</summary><dl><dt>Visibility</dt><dd>{doc.visibility}</dd><dt>Document ID</dt><dd>{doc.id}</dd><dt>SHA-256 revision</dt><dd><code>{doc.sha256??'External reference - no verified local bytes'}</code></dd><dt>Rights</dt><dd>{doc.rights.status}</dd><dt>Bytes</dt><dd>{doc.bytes??'Not imported'}</dd></dl></details></div>
 {show&&url&&<iframe className="pdf-fallback" src={url} title={'Browser PDF preview: '+doc.title} referrerPolicy="no-referrer"/>}
 </div>;
}
