import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {validateCheatsheet,validateCheatsheetPage,visitCheatsheetBlocks} from '../src/cheatsheets/validation.mjs';
import {renderCheatsheetPage,edgeEndpoint,CALM_TOKENS} from '../src/cheatsheets/renderer.mjs';
import {layoutRich,plainText,cheatsheetText,cheatsheetAnchor} from '../src/cheatsheets/text-layout.mjs';
import {cheatsheetPage,parseCheatsheetSource,sheetGroup,sheetPosition,sheetPagePatch} from '../src/cheatsheets/content.mjs';
import {readWorkspace,loadSchemas} from '../src/core/packs.mjs';import {readFiles} from '../tools/fs.mjs';
import {validateSchema,validateRelations} from '../src/core/validation.mjs';
import {validateState} from '../src/storage/state-validation.mjs';import {validatePersonal} from '../src/storage/personal-validation.mjs';
import {validateReadingTarget} from '../src/storage/reading-validation.mjs';
import {makeBackup,readBackup,unzipBounded} from '../src/storage/archives.mjs';
import {exportRepositoryWorkspace} from '../src/core/export-pack.mjs';
import {blankWorkspace,newView,current,compose,searchCatalog,exportText} from '../dist-offline/app/core/workspace.js';
import {activeSession,migratePersonal,selectWorkspace} from '../dist-offline/app/core/workspace-slots.js';
import {openReadingTarget} from '../dist-offline/app/core/reading-navigation.js';
import {addReadingBookmark,addReadLater,targetForPage} from '../dist-offline/app/core/reading-lists.js';
import {saveReadingState,restoreReadingState} from '../dist-offline/app/core/saved-states.js';
import {documentBlockMatches} from '../dist-offline/app/core/document-context.js';
const clone=structuredClone;
const schemas=await loadSchemas(n=>fs.readFile('src/content/schemas/'+n,'utf8'));
const standalone=JSON.parse(await fs.readFile('src/content/schemas/cheatsheet-v1.schema.json','utf8'));
const source=await readWorkspace(await readFiles('content'),schemas),built={packs:source.packs,groups:source.workspace.groups,assets:source.assets,releaseId:'126-unit'};
const native=source.packs.find(p=>p.manifest.id==='atlas.cheatsheet-samples'),docs=native.pages.map(p=>p.cheatsheet),sql=docs.find(d=>d.id==='sql-analytics'),page=native.pages.find(p=>p.cheatsheet.id===sql.id);
const catalogue=compose(built,blankWorkspace());
function minimal(block={id:'block.one',type:'text',text:'A safe reference'}){return {schemaVersion:'1.1',id:'test-sheet',title:'Test',pageSize:{width:1200,height:1600},pages:[{id:'test.p1',title:'One',blocks:[block],frames:{[block.id]:{x:80,y:100,width:1000,height:1200}},outline:[]}]};}
function setup(){const w=blankWorkspace();w.personal=migratePersonal(w.personal);const v=newView('page.atlas.layouts');w.personal.session.panes[0].views=[v];w.personal.session.panes[0].active=v.id;w.personal.session.screen='reader';return w;}
const target=(n=2)=>({kind:'cheatsheet-page',pageId:page.id,documentId:sql.id,sheetPage:n,anchor:{sheetPage:n,sheetId:sql.pages[n-1].id}});
const location=p=>{const s=activeSession(p),pane=s.panes.find(x=>x.id===s.activePane);return current(pane.views.find(v=>v.id===pane.active));};
const bundle=p=>({schemaVersion:2,title:'Test',pages:[p],projects:[],glossary:[],groups:[]});

for(const doc of docs)test('1.2.6 canonical two-page fixture/schema/renderer: '+doc.id,()=>{
 assert.equal(doc.pages.length,2);assert.equal(doc.pages.flatMap(p=>p.outline).length,8);validateCheatsheet(doc);validateSchema(doc,standalone);
 for(let i=1;i<=2;i++){const result=renderCheatsheetPage(doc,i);assert.deepEqual(result.diagnostics,[]);assert.equal(renderCheatsheetPage(doc,i).svg,result.svg);assert.match(result.svg,/viewBox="0 0 1200 1600"/);assert.doesNotMatch(result.svg,/<(?:foreignObject|script|image|canvas)\b/i);assert.match(result.svg,/<text\b/);}
});
test('1.2.6 reconstructed inventory is explicitly 150 blocks, 8 diagrams, zero drawing fallbacks',()=>{const counts={};for(const d of docs)for(const p of d.pages)visitCheatsheetBlocks(p.blocks,b=>counts[b.type]=(counts[b.type]??0)+1);assert.equal(Object.values(counts).reduce((a,b)=>a+b,0),150);assert.equal(counts.diagram,8);assert.equal(counts.drawing??0,0);});
test('1.2.6 original-preview gaps are recorded, never passed off as exact source JSON',()=>{const adf=docs.find(d=>d.id==='azure-data-factory');assert.match(adf.meta.provenance,/reconstruct|author/i);assert.ok(docs.every(d=>d.meta.provenance));});
test('1.2.6 wrapper requires native kind and empty notebook blocks, without PDF disguise',()=>{validateCheatsheetPage(page);validateSchema(bundle(page),schemas.v2);assert.equal(catalogue.documents.some(d=>d.pageId===page.id),false);for(const mutate of [p=>delete p.kind,p=>delete p.cheatsheet,p=>p.blocks=[{id:'a',type:'markdown',text:'Not native'}]]){const p=clone(page);mutate(p);assert.throws(()=>validateCheatsheetPage(p));}});
test('1.2.6 JSON grammar definitions are identical in standalone and embedded import schemas',()=>{for(const key of Object.keys(standalone.$defs)){assert.deepEqual(schemas.v2.$defs[key],standalone.$defs[key],key);const pageSchema=JSON.parse(requireText('src/content/schemas/page-v2.schema.json'));assert.deepEqual(pageSchema.$defs[key],standalone.$defs[key],key);}});
// Synchronous file access here is limited to immutable schema comparisons.
import {readFileSync} from 'node:fs';function requireText(path){return readFileSync(path,'utf8');}
for(const [label,mutate] of [
 ['unknown document field',d=>d.svg='<svg/>'],['unsupported version',d=>d.schemaVersion='9.0'],['wrong fixed page size',d=>d.pageSize.width=900],['invalid stable ID',d=>d.pages[0].id='bad id'],['duplicate block',d=>d.pages[0].blocks.push(clone(d.pages[0].blocks[0]))],['orphan frame',d=>d.pages[0].frames.orphan={x:0,y:0,width:5,height:5}],['frame outside page',d=>d.pages[0].frames['block.one'].width=1200],['missing frame',d=>delete d.pages[0].frames['block.one']],['unknown block kind',d=>d.pages[0].blocks[0].type='svg'],['event handler',d=>d.pages[0].blocks[0].onload='evil'],['outline missing target',d=>d.pages[0].outline=[{id:'a',label:'Missing',blockId:'absent'}]],['outline collision',d=>d.pages[0].outline=[{id:'block.one',label:'Ambiguous',blockId:'block.one'}]],['invalid color',d=>d.theme={name:'atlas-calm',tokens:{primary:'url(https://evil)'}}],['non-finite coordinates',d=>d.pages[0].frames['block.one'].x=NaN],['subminimum font',d=>d.pages[0].blocks[0].style={fontSize:2}],['raw HTML tag field',d=>d.pages[0].blocks[0].html='<img>'],['1.0 has no audience extension',d=>{d.schemaVersion='1.0';d.meta={audience:'Readers'};}]
])test('1.2.6 rejects '+label,()=>{const d=minimal();mutate(d);assert.throws(()=>validateCheatsheet(d));});
test('1.2.6 version 1.0 core and version 1.1 audience/goal both supported',()=>{const d=minimal();d.meta={audience:'Data engineers',goal:'Understand grain'};validateCheatsheet(d);d.schemaVersion='1.0';delete d.meta;validateCheatsheet(d);});
test('1.2.6 reserved keys, cycles, oversized JSON and malformed JSON fail closed',()=>{assert.throws(()=>parseCheatsheetSource('{'));assert.throws(()=>parseCheatsheetSource(' '.repeat(4*1024*1024+1)));assert.throws(()=>validateCheatsheet(JSON.parse('{"__proto__":{}}')));const d=minimal();d.loop=d;assert.throws(()=>validateCheatsheet(d));});
test('1.2.6 source import keeps exact whitespace and never converts SVG into source',()=>{const d=minimal({id:'block.one',type:'text',text:[{text:'before '},{text:'bold',marks:['bold']},{text:' after\n  indented\u200bword'}]});const parsed=parseCheatsheetSource(JSON.stringify(d));assert.deepEqual(parsed,d);const svg=renderCheatsheetPage(parsed,1).svg;assert.match(svg,/>before <\/tspan>/);assert.match(svg,/> after\n  indentedword<\/tspan>|> after\n<\/tspan>/);assert.doesNotMatch(svg,/\u200b/);});
test('1.2.6 SVG text is escaped in body, code, table, diagram labels and accessibility titles',()=>{const evil='<script>alert("x")</script> & <img onerror="bad">';const variants=[{id:'block.one',type:'text',text:evil},{id:'block.one',type:'code',code:evil,language:'sql',title:evil},{id:'block.one',type:'table',columns:[evil],rows:[[evil]]},{id:'block.one',type:'diagram',family:'sequence',preset:'steps',direction:'vertical',items:[evil,'safe']}];for(const b of variants){const d=minimal(b);d.pages[0].title=evil;const svg=renderCheatsheetPage(d,1).svg;assert.doesNotMatch(svg,/<script>|<img /);assert.match(svg,/&lt;script&gt;/);}});
test('1.2.6 instance scope rejects attributes/URLs and namespaced IDs cannot collide with title or marker',()=>{const d=minimal({id:'title',type:'text',text:'Safe'}),a=renderCheatsheetPage(d,1,{scope:'pane-a'}).svg,b=renderCheatsheetPage(d,1,{scope:'pane-b'}).svg;assert.throws(()=>renderCheatsheetPage(d,1,{scope:'a" onload="evil'}));const ids=s=>[...s.matchAll(/ id="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids(a)).size,ids(a).length);assert.ok(ids(a).every(x=>!ids(b).includes(x)));});
test('1.2.6 inline whitespace, tabs and zero-width hints have deterministic layout',()=>{const text=[{text:'left '},{text:'keyword',marks:['key']},{text:' right\n\tvalue\u200b.field'}];const lay=layoutRich(text,80,20);assert.equal(lay.lines.flatMap(l=>l.fragments.map(f=>f.text)).join(''),'left keyword right\n    value.field');assert.equal(plainText(text),'left keyword right\n\tvalue.field');});
for(const kind of ['clip','shrink','error'])test('1.2.6 declared text overflow mode '+kind,()=>{const d=minimal({id:'block.one',type:'text',text:'Long text '.repeat(100),style:{fontSize:30,minFontSize:20,overflow:kind}});d.pages[0].frames['block.one'].height=40;if(kind==='error')assert.throws(()=>renderCheatsheetPage(d,1),/overflow/);else assert.ok(renderCheatsheetPage(d,1).diagnostics.length>0);});
test('1.2.6 modest overflow shrinks within its explicit floor',()=>{const d=minimal({id:'block.one',type:'text',text:'Two\nLines',style:{fontSize:30,minFontSize:12,lineHeight:1,overflow:'shrink'}});d.pages[0].frames['block.one'].height=40;const r=renderCheatsheetPage(d,1);assert.deepEqual(r.diagnostics,[]);assert.match(r.svg,/font-size="20"/);});
test('1.2.6 calm theme uses no fluorescent rectangles or slogan/footer content',()=>{assert.equal(CALM_TOKENS.primary,'#183f68');const svg=renderCheatsheetPage(sql,1).svg;assert.match(svg,/font-style="italic"/);assert.doesNotMatch(svg,/#ff00ff|#ffff00|#ff69b4/i);});
for(const shape of ['rect','circle','diamond'])test('1.2.6 arrows land on actual '+shape+' bounds',()=>{const from={x:10,y:20,width:200,height:100},to={x:410,y:20,width:200,height:100};assert.deepEqual(edgeEndpoint(from,to,shape),{x:210,y:70});assert.deepEqual(edgeEndpoint(to,from,shape),{x:410,y:70});const down={x:10,y:320,width:200,height:100};assert.deepEqual(edgeEndpoint(from,down,shape),{x:110,y:120});});
for(const direction of ['horizontal','vertical'])for(const preset of ['steps','array','stack','queue','linked_list'])test('1.2.6 sequence '+preset+' '+direction,()=>{const d=minimal({id:'block.one',type:'diagram',family:'sequence',preset,direction,items:['A','B','C']}),svg=renderCheatsheetPage(d,1).svg;assert.equal((svg.match(/data-diagram-edge/g)||[]).length,2);assert.equal((svg.match(/data-pointer-compartment/g)||[]).length,preset==='linked_list'?3:0);});
test('1.2.6 impossible sequence geometry rejected before negative node widths can render',()=>{const d=minimal({id:'block.one',type:'diagram',family:'sequence',preset:'steps',direction:'horizontal',items:['A','B','C']});d.pages[0].frames['block.one'].width=50;assert.throws(()=>validateCheatsheet(d),/geometry/);});
test('1.2.6 graph validates node frames, endpoint identities and registered icons',()=>{const d=minimal({id:'block.one',type:'diagram',family:'graph',layout:'manual',nodes:[{id:'a',label:'A',assetKey:'atlas.database'},{id:'b',label:'B'}],nodeFrames:{a:{x:10,y:10,width:150,height:80},b:{x:10,y:200,width:150,height:80}},edges:[{from:'a',to:'b',label:'go'}]});assert.match(renderCheatsheetPage(d,1).svg,/data-diagram-edge/);d.pages[0].blocks[0].edges[0].to='c';assert.throws(()=>validateCheatsheet(d),/endpoint/);});
test('1.2.6 drawing, icons and registry-local image remain typed bounded primitives',()=>{for(const b of [{id:'block.one',type:'drawing',shapes:[{type:'line',x1:0,y1:0,x2:100,y2:100},{type:'rect',x:0,y:0,width:40,height:30},{type:'ellipse',x:50,y:0,width:40,height:30}]},{id:'block.one',type:'icon',assetKey:'atlas.cloud',alt:'Cloud'},{id:'block.one',type:'image',assetKey:'atlas.brand',alt:'AtlasNote'}])assert.deepEqual(renderCheatsheetPage(minimal(b),1).diagnostics,[]);});
for(const key of ['https://evil/image.svg','javascript:evil','data:image/svg+xml,<svg/>','../../private','atlas.unknown'])test('1.2.6 unregistered asset rejected '+key,()=>assert.throws(()=>validateCheatsheet(minimal({id:'block.one',type:'image',assetKey:key,alt:'No'}))));
test('1.2.6 tables require equal row arity and proportional column widths',()=>{const d=minimal({id:'block.one',type:'table',columns:['A','B'],rows:[['1','2']],widths:[.5,.5]});validateCheatsheet(d);d.pages[0].blocks[0].widths=[.2,.2];assert.throws(()=>validateCheatsheet(d));delete d.pages[0].blocks[0].widths;d.pages[0].blocks[0].rows[0].pop();assert.throws(()=>validateCheatsheet(d));});
test('1.2.6 nested box children keep global coordinates and cannot escape their parent frame',()=>{const d=minimal({id:'block.one',type:'box',children:[{id:'child',type:'text',text:'Nested'}]});d.pages[0].frames.child={x:90,y:120,width:300,height:100};validateCheatsheet(d);d.pages[0].frames.child.x=10;assert.throws(()=>validateCheatsheet(d),/outside box/);});
for(const mode of ['single','spread','grid'])test('1.2.6 page groups preserve identities without fabricated duplicates: '+mode,()=>{assert.deepEqual(sheetGroup(sql,{sheetPage:2,sheetMode:mode}).pages,mode==='single'?[2]:[1,2]);assert.equal(sheetGroup(sql,{sheetPage:3,sheetMode:mode}).available,false);});
test('1.2.6 a four-page source renders four different physical pages in a 2x2 group',()=>{const d=minimal();for(let i=2;i<=5;i++){const p=clone(d.pages[0]);p.id='test.p'+i;p.blocks[0].id='block.'+i;p.frames={[p.blocks[0].id]:{x:80,y:100,width:1000,height:1200}};d.pages.push(p);}validateCheatsheet(d);assert.deepEqual(sheetGroup(d,{sheetPage:3,sheetMode:'grid'}).pages,[1,2,3,4]);assert.deepEqual(sheetGroup(d,{sheetPage:5,sheetMode:'grid'}).pages,[5]);});
test('1.2.6 physical page and block anchors survive page reorder; missing pages are not silently retargeted',()=>{const d=clone(sql),a={sheetPage:2,anchor:{sheetPage:2,sheetId:d.pages[1].id}};d.pages.reverse();assert.equal(sheetPosition(d,a).page,1);d.pages.shift();assert.equal(sheetPosition(d,a).available,false);const original=sql.pages[1].outline[0].blockId;assert.equal(sheetPosition(sql,{sheetPage:1,anchor:{blockId:original}}).page,2);assert.equal(cheatsheetAnchor(sql,sql.pages[1].outline[0].id).blockId,original);});
test('1.2.6 location changes omit undefined optionals and clear stale scroll',()=>{assert.deepEqual(sheetPagePatch(2),{sheetPage:2,anchor:{sheetPage:2},scroll:0});for(const n of [0,-1,1.5,65,NaN])assert.throws(()=>sheetPagePatch(n));});
test('1.2.6 native text participates in global/document search and text export',()=>{const text=cheatsheetText(sql);assert.match(text,/GROUP BY/);assert.ok(documentBlockMatches(page,'DENSE_RANK').every(x=>x.title.startsWith('p.2')));assert.ok(documentBlockMatches(page,'DENSE_RANK').length>0);const hits=searchCatalog(catalogue,'DENSE_RANK');assert.ok(hits.pages.some(h=>h.page.id===page.id));const out=exportText(page,{english:true,answers:true});assert.match(out,/DENSE_RANK/);});
test('1.2.6 explicit interview links exist without altering interview pages',()=>{assert.equal(page.related.length,5);assert.ok(page.related.every(id=>catalogue.pages.some(p=>p.id===id&&p.tags.includes('interview'))));validateRelations(source.packs);});
for(const dest of ['here','tab','pane',1,2,3,4,5])test('1.2.6 native physical-page actions preserve other views and route to '+dest,()=>{const w=setup(),before=clone(w.personal.session);openReadingTarget(w.personal,catalogue,w.overlays,target(),dest);assert.equal(location(w.personal).sheetPage,2);assert.equal(location(w.personal).anchor.sheetId,sql.pages[1].id);if(typeof dest==='number'&&dest!==1)assert.deepEqual(w.personal.session,before);else if(dest!=='here')assert.deepEqual(w.personal.session.panes[0].views[0],before.panes[0].views[0]);validatePersonal(w.personal);});
test('1.2.6 unavailable physical-page action is atomic and retains existing saves',()=>{const w=setup(),before=clone(w.personal);for(const t of [{...target(),sheetPage:3,anchor:{sheetPage:3}}, {...target(),documentId:'unknown'},{...target(),anchor:{sheetPage:2,sheetId:'deleted.page'}}])assert.throws(()=>openReadingTarget(w.personal,catalogue,w.overlays,t,5),/unavailable/);assert.deepEqual(w.personal,before);});
for(const mutate of [t=>t.sheetPage=0,t=>t.sheetPage=2.5,t=>t.sheetPage=65,t=>t.anchor.sheetPage=1,t=>t.anchor.pdfPage=1,t=>t.anchor.sheetId='bad id',t=>t.documentId='../bad',t=>t.extra='bad'])test('1.2.6 malformed reading identity refused '+mutate.toString(),()=>{const t=target();mutate(t);assert.throws(()=>validateReadingTarget(t));});
for(const [key,value] of [['sheetPage',65],['sheetPage',0],['sheetMode','continuous'],['sheetZoom',0.1],['sheetFit','stretch']])test('1.2.6 personal state rejects invalid '+key+'='+value,()=>{const w=setup();location(w.personal)[key]=value;assert.throws(()=>validatePersonal(w.personal));});
test('1.2.6 pane A/B mode, page, fit, zoom and chrome restore independently in all-workspace saves',()=>{const w=setup(),p=w.personal;openReadingTarget(p,catalogue,w.overlays,target(1),'here');Object.assign(location(p),{sheetMode:'single',sheetFit:'width',sheetZoom:1.5,scroll:150});openReadingTarget(p,catalogue,w.overlays,target(2),'pane');Object.assign(location(p),{sheetMode:'grid',sheetFit:'page',sheetZoom:.75,scroll:0});p.session.panes[0].readerChromeCollapsed=true;p.session.panes[1].readerChromeCollapsed=false;for(let i=2;i<=5;i++)openReadingTarget(p,catalogue,w.overlays,target(i%2+1),i);selectWorkspace(p,1);const snapshot=clone({session:p.session,slots:p.workspaceSlots});const save=saveReadingState(p,'all','Native all five');Object.assign(location(p),{sheetPage:1,sheetMode:'spread'});restoreReadingState(p,save);assert.deepEqual({session:p.session,slots:p.workspaceSlots},snapshot);validatePersonal(p);});
test('1.2.6 exact backup preserves native source, stable anchors, notes, bookmarks, queue and saved states',async()=>{const w=setup(),p=w.personal,privatePage=cheatsheetPage(clone(sql),{pageId:'page.local.sheet'});privatePage.cheatsheet.pages[1].blocks.find(b=>b.type==='text').text='Locally edited title';w.overlays.pages[privatePage.id]={page:privatePage};w.overlays.projects.push({id:'project.local.sheet',title:'Private',icon:'grid',description:'Local',nodes:[{id:'node.local.sheet',title:'Private source',pageId:privatePage.id}]});openReadingTarget(p,catalogue,w.overlays,target(),'here');const anchor=clone(location(p).anchor);p.notes[page.id+'::sheet:'+anchor.sheetId]={pageId:page.id,anchor,text:'My page-specific reflection',updatedAt:123};addReadingBookmark(p,target(),'Return to SQL p.2','informatics');addReadLater(p,target(),'Re-read ranking','informatics');saveReadingState(p,'all','With native source');const before=clone(w);const backup=await makeBackup(w,built,async key=>source.assets.find(a=>a.key===key));const restored=await readBackup((await unzipBounded(backup.bytes)).files,schemas);assert.deepEqual(restored.workspace.personal,before.personal);assert.deepEqual(restored.workspace.overlays,before.overlays);validateState(restored.workspace,schemas);});
test('1.2.6 repository export retains structured JSON, physical page IDs and private classification',async()=>{const w=setup(),local=cheatsheetPage(sql,{pageId:'page.local.source'});w.overlays.pages[local.id]={page:local};w.overlays.projects.push({id:'project.local.native',title:'Private native',icon:'grid',description:'',nodes:[{id:'node.local.native',title:'Source',pageId:local.id}]});const result=await exportRepositoryWorkspace(compose(built,w),w,async key=>source.assets.find(a=>a.key===key));const reread=await readWorkspace((await unzipBounded(result.bytes)).files,schemas);const exported=reread.packs.find(p=>p.pages.some(x=>x.id===local.id));assert.equal(exported.manifest.visibility,'private');assert.deepEqual(exported.pages.find(p=>p.id===local.id).cheatsheet,sql);});
test('1.2.6 malicious canonical source hidden inside an overlay fails backup validation',()=>{const w=setup();w.overlays.pages[page.id]={page:clone(page)};w.overlays.pages[page.id].page.cheatsheet.pages[0].blocks[0].svg='<script/>';assert.throws(()=>validateState(w,schemas));});
test('1.2.6 per-page bookmarks use native typed targets while legacy notebook bookmarks stay unchanged',()=>{assert.equal(targetForPage(catalogue,page.id,target().anchor).kind,'cheatsheet-page');assert.deepEqual(targetForPage(catalogue,'page.atlas.layouts',{blockId:'block.atlas.layouts.0'}),{kind:'page',pageId:'page.atlas.layouts',anchor:{blockId:'block.atlas.layouts.0'}});});
