import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {readFiles} from '../tools/fs.mjs';import {readWorkspace,loadSchemas} from '../src/core/packs.mjs';
import {validateState} from '../src/storage/state-validation.mjs';import {validatePersonal} from '../src/storage/personal-validation.mjs';
import {makeBackup,readBackup,unzipBounded} from '../src/storage/archives.mjs';import {validateSchema} from '../src/core/validation.mjs';
import {validateReadingTarget} from '../src/storage/reading-validation.mjs';
import {parseContentJSON,validateQcm,validateArticleSource,validateHubPage,validateHubPersonal,validateHubOverlays} from '../src/content-hub/validation.mjs';
import {blankWorkspace,compose,newView,newLocation,current,searchCatalog} from '../dist-offline/app/core/workspace.js';
import {activeSession,selectWorkspace,migratePersonal,CATEGORIES} from '../dist-offline/app/core/workspace-slots.js';
import {openReadingTarget} from '../dist-offline/app/core/reading-navigation.js';import {addReadingBookmark,addReadLater} from '../dist-offline/app/core/reading-lists.js';
import {saveReadingState,restoreReadingState} from '../dist-offline/app/core/saved-states.js';
import * as content from '../dist-offline/app/content-hub/content.js';import * as taxonomy from '../dist-offline/app/content-hub/taxonomy.js';import * as surface from '../dist-offline/app/content-hub/surfaces.js';
import {dashboardCards,filterDashboard} from '../dist-offline/app/content-hub/dashboard.js';
import {makeCheatsheetPreset} from '../dist-offline/app/cheatsheets/presets.js';import {renderCheatsheetPage} from '../src/cheatsheets/renderer.mjs';
import {documentBlockMatches} from '../dist-offline/app/core/document-context.js';
const schemas=await loadSchemas(n=>fs.readFile('src/content/schemas/'+n,'utf8'));
const source=await readWorkspace(await readFiles('content'),schemas),built={packs:source.packs,groups:source.workspace.groups,assets:source.assets,releaseId:'127-unit'};
const article=JSON.parse(await fs.readFile('examples/content-hub/article-sample.json','utf8')),qcm=JSON.parse(await fs.readFile('examples/content-hub/qcm-sample.json','utf8'));
const clone=structuredClone;
function setup(){const ws=blankWorkspace();ws.personal=migratePersonal(ws.personal);const c=compose(built,ws);return {ws,c};}
function populated(){const {ws,c}=setup();content.putContent(ws.overlays,content.articlePage(article,100),c);content.putContent(ws.overlays,content.qcmPage(qcm),c);return {ws,c:compose(built,ws)};}
const location=p=>{const s=activeSession(p),pane=s.panes.find(x=>x.id===s.activePane);return current(pane.views.find(v=>v.id===pane.active));};
const allNodes=ps=>{const list=[];function visit(ns){for(const n of ns){list.push(n);visit(n.children??[]);}}for(const p of ps)visit(p.nodes);return list;};

test('127 subjects and five modes are additive; default empty workspace is Dashboard',()=>{const {ws}=setup();assert.deepEqual(CATEGORIES.map(x=>x.label),['IT','Cloud','Job','KPI','Norsk']);assert.equal(ws.personal.session.surface,'dashboard');for(const mode of ['notes','pdfs','cheatsheets','articles','qcm']){ws.personal.session.libraryMode=mode;validatePersonal(ws.personal);}});
test('127 source fixtures preserved exactly in article/QCM wrappers',()=>{const {ws,c}=populated();const a=c.pages.find(x=>x.id===article.id),q=c.pages.find(x=>x.id===qcm.id);assert.equal(a.article.addedAt,100);assert.equal(a.blocks[0].text,article.text);assert.deepEqual(q.qcm,qcm);assert.equal(q.blocks.length,0);validateState(ws,schemas);});
test('127 capture ignores blank rows, supports five tasks and exact opt-in source only',()=>{const {ws}=setup(),target={kind:'qcm',setId:qcm.id,questionId:'q2'};const rows=[{text:'one'},{text:' '},{text:'two',due:'2026-09-20',important:true}];const items=content.captureRows(ws.personal,'task',rows,undefined,undefined,100);assert.equal(items.length,2);assert.ok(items.every(i=>!i.contextTarget&&!i.taxonomy));const next=content.captureRows(ws.personal,'note',Array.from({length:5},(_,i)=>({text:'n'+i})),{subject:'it'},target,101);assert.equal(next.length,5);assert.deepEqual(next[0].contextTarget,target);validatePersonal(ws.personal);});
for(const [name,fn] of [
 ['six captures',(p)=>content.captureRows(p,'note',Array.from({length:6},()=>({text:'x'})))],
 ['invalid URL batch',(p)=>content.captureRows(p,'link',[{text:'https://example.com'},{text:'javascript:alert(1)'}])],
 ['invalid date',(p)=>content.captureRows(p,'task',[{text:'x',due:'2026-02-30'}])],
 ['empty captures',(p)=>content.captureRows(p,'note',[{text:' '}])],
 ['invalid subject',(p)=>content.captureRows(p,'note',[{text:'x'}],{subject:'unknown'})],
 ['unsafe context',(p)=>content.captureRows(p,'note',[{text:'x'}],undefined,{kind:'url',url:'data:text/html,bad'})]
])test('127 '+name+' is atomic',()=>{const {ws}=setup(),before=clone(ws.personal);assert.throws(()=>fn(ws.personal));assert.deepEqual(ws.personal,before);});
test('127 optional date timestamp and importance survive update and done/reopen/archive',()=>{const {ws}=setup(),item=content.captureRows(ws.personal,'task',[{text:'A',due:'2026-10-01',important:true}],{subject:'kpi'},undefined,100)[0];for(const status of ['done','open','archived'])content.updateCapture(ws.personal,item.id,{status},102);assert.equal(ws.personal.dashboardItems[0].important,true);assert.equal(new Date(item.dueAt).toISOString().slice(0,10),'2026-10-01');validatePersonal(ws.personal);});
for(const [name,mutate] of [
 ['zero questions',x=>x.questions=[]],['one option',x=>x.questions[0].options.splice(1)],['seven options',x=>x.questions[0].options=Array.from({length:7},(_,i)=>({id:'o'+i,text:'O'}))],['duplicate questions',x=>x.questions.push(clone(x.questions[0]))],['duplicate options',x=>x.questions[0].options[1].id=x.questions[0].options[0].id],['missing answer',x=>x.questions[0].correctOptionIds=['absent']],['duplicate answer',x=>x.questions[0].correctOptionIds=['c','c']],['empty answer',x=>x.questions[0].correctOptionIds=[]],['arbitrary markup field',x=>x.questions[0].html='<script/>'],['remote script link',x=>x.questions[0].links=[{label:'evil',target:{kind:'url',url:'javascript:alert(1)'}}]],['bad version',x=>x.schemaVersion=9],['oversized title',x=>x.title='a'.repeat(201)]
])test('127 QCM rejects '+name,()=>{const x=clone(qcm);mutate(x);assert.throws(()=>validateQcm(x));});
for(const [name,mutate] of [
 ['unsafe URL',x=>x.url='data:text/html,x'],['iframe block',x=>{delete x.text;x.blocks=[{id:'b',type:'iframe',src:'https://example.com'}];}],['both body forms',x=>x.blocks=[]],['event handler',x=>{delete x.text;x.blocks=[{id:'b',type:'markdown',text:'safe',onclick:'evil'}];}],['unsafe layout',x=>{delete x.text;x.blocks=[{id:'b',type:'markdown',text:'safe',layout:{background:'url(evil)'}}];}],['wrong boolean',x=>{delete x.text;x.blocks=[{id:'b',type:'list',items:['x'],ordered:'yes'}];}],['unknown metadata',x=>x.script='evil'],['prototype pollution',x=>Object.assign(x,JSON.parse('{"__proto__":{"polluted":true}}'))]
])test('127 Article rejects '+name,()=>{const x=clone(article);mutate(x);assert.throws(()=>validateArticleSource(x));assert.equal({}.polluted,undefined);});
test('127 malformed/oversized/reserved JSON rejected without coercion',()=>{for(const v of ['{',' '.repeat(4194305),'{"constructor":{}}'])assert.throws(()=>parseContentJSON(v));assert.deepEqual(parseContentJSON(JSON.stringify(qcm)),qcm);});
test('127 pasted markup remains literal canonical text, not remote HTML',()=>{const x={...article,text:'<script>unsafe()</script>\n<img src=x onerror=unsafe()>\n  keep whitespace'};assert.equal(content.articlePage(x).blocks[0].text,x.text);});
test('127 article source collision needs explicit same-kind edit and retains related data',()=>{const {ws,c}=populated();const before=clone(ws.overlays);assert.throws(()=>content.putContent(ws.overlays,content.articlePage(article),c));assert.deepEqual(ws.overlays,before);const p=c.pages.find(x=>x.id===article.id);p.related=['page.atlas.welcome'];content.putContent(ws.overlays,content.articlePage({...article,title:'Edited'}),c,true);assert.deepEqual(ws.overlays.pages[article.id].page.related,p.related);assert.equal(ws.overlays.pages[article.id].page.title,'Edited');});
test('127 shared folder IDs stay stable across all five projected modes; no metadata mutation',()=>{const {ws,c}=populated(),before=clone({ws,c}),folder=taxonomy.sharedFolders(c,ws.overlays).find(f=>f.subject==='it');ws.overlays.taxonomy={};for(const p of c.pages)ws.overlays.taxonomy[p.id]={subject:'it',folderId:folder.id};const assigned=clone(ws.overlays);for(const mode of ['notes','pdfs','cheatsheets','articles','qcm'])assert.ok(taxonomy.projectLibrary(c,ws.overlays,mode,'it').some(p=>p.id===folder.projectId));assert.deepEqual(ws.overlays,assigned);assert.deepEqual(c,before.c);});
test('127 descendants use stable parent identities, not equal textual folder names',()=>{const folders=[{id:'a',subject:'it',path:['Same']},{id:'b',subject:'it',path:['Same']},{id:'child',parentId:'a',subject:'it',path:['Same','Child']}];assert.equal(taxonomy.scopeMatches({subject:'it',folderId:'child'},'it','a',folders),true);assert.equal(taxonomy.scopeMatches({subject:'it',folderId:'child'},'it','b',folders),false);});
test('127 unknown folder hints fall back to Unfiled without destroying stored source taxonomy',()=>{const {ws,c}=populated(),before=clone(c.pages.find(x=>x.id===article.id));const proj=taxonomy.projectLibrary(c,ws.overlays,'articles','norsk');assert.ok(proj.some(p=>p.id==='project.unfiled.norsk'));assert.deepEqual(c.pages.find(x=>x.id===article.id),before);});
test('127 explicit unclassification overrides source subject without destructive source rewrite',()=>{const {ws,c}=populated();ws.overlays.taxonomy={[article.id]:null};assert.equal(taxonomy.resourceTaxonomy(c,ws.overlays,article.id),undefined);assert.equal(c.pages.find(x=>x.id===article.id).article.taxonomy.subject,'norsk');validateState(ws,schemas);});
test('127 native Notebook projection contains no implicit PDF, cheatsheet, Article or QCM copies',()=>{const {ws,c}=populated(),nodes=allNodes(taxonomy.projectLibrary(c,ws.overlays,'notes'));for(const n of nodes.filter(n=>n.pageId))assert.equal(content.libraryModeForPage(c,n.pageId),'notes');});
test('127 Notebook references are deduplicated by target+destination and removal never alters source',()=>{const {ws,c}=populated(),folder=taxonomy.sharedFolders(c,ws.overlays)[0],target={kind:'qcm',setId:qcm.id,questionId:'q2'},original=clone(ws.overlays.pages);const a=content.addNotebookReference(ws.overlays,target,'Quiz',{subject:folder.subject,folderId:folder.id},100),b=content.addNotebookReference(ws.overlays,target,'Quiz',{subject:folder.subject,folderId:folder.id},101);assert.equal(a.id,b.id);assert.ok(allNodes(taxonomy.projectLibrary(c,ws.overlays,'notes')).some(n=>n.target?.questionId==='q2'));content.removeReference(ws.overlays,a.id);assert.deepEqual(ws.overlays.pages,original);assert.equal(ws.overlays.references.length,0);});
test('127 reference rename/move preserves target identity and supports a new subject destination',()=>{const {ws,c}=populated(),t={kind:'article',articleId:article.id},r=content.addNotebookReference(ws.overlays,t,'Read',{subject:'norsk'});content.updateReference(ws.overlays,r.id,'Revised',{subject:'job'});assert.equal(ws.overlays.references[0].title,'Revised');assert.deepEqual(ws.overlays.references[0].target,t);validateHubOverlays(ws.overlays);});
test('127 local source removal retains attempts, captures, bookmarks and references',()=>{const {ws,c}=populated();content.answerQuestion(ws.personal,qcm,'q1',['c']);content.addNotebookReference(ws.overlays,{kind:'qcm',setId:qcm.id},'Q',{subject:'it'});const personal=clone(ws.personal),refs=clone(ws.overlays.references);content.removeLocalContent(ws.overlays,c,qcm.id);assert.equal(ws.overlays.pages[qcm.id],undefined);assert.deepEqual(ws.personal,personal);assert.deepEqual(ws.overlays.references,refs);assert.throws(()=>openReadingTarget(ws.personal,compose(built,ws),ws.overlays,refs[0].target,'here'),/unavailable/);});
test('127 single/multiple answers use exact set equality, not subset or option order',()=>{const {ws}=setup();const a=content.answerQuestion(ws.personal,qcm,'q1',['c'],'Reason',false,100);assert.equal(a.correct,true);assert.equal(content.answerQuestion(ws.personal,qcm,'q2',['b','a','d'],'',false,101).correct,true);assert.equal(content.answerQuestion(ws.personal,qcm,'q2',['a','b'],'',false,102).correct,false);assert.equal(content.answerQuestion(ws.personal,qcm,'q1',['a'],'',false,103).correct,false);assert.equal(a.attemptNumber,1);validatePersonal(ws.personal);});
test('127 reveal is an attempt, never incorrectly scored as correct; draft selection persists',()=>{const {ws}=setup();content.saveResponse(ws.personal,qcm,'q1',['c'],'draft',50);const a=content.answerQuestion(ws.personal,qcm,'q1',['c'],'reflection',true,100);assert.equal(a.correct,false);assert.equal(a.revealed,true);content.reflectAttempt(ws.personal,a.id,'Revised reflection');assert.equal(ws.personal.qcmAttempts[0].reflection,'Revised reflection');assert.deepEqual(content.qcmProgress(ws.personal,qcm),{total:2,answered:1,correct:0,review:1});validatePersonal(ws.personal);});
test('127 invalid answer selections leave all attempts and response records unchanged',()=>{const {ws}=setup(),before=clone(ws.personal);for(const a of [[],['invalid'],['a','b'],['c','c']])assert.throws(()=>content.answerQuestion(ws.personal,qcm,'q1',a));assert.deepEqual(ws.personal,before);});
test('127 bounded AI review export includes every option and all relevant attempts',()=>{const {ws}=setup();content.answerQuestion(ws.personal,qcm,'q1',['a'],'First',false,1);content.answerQuestion(ws.personal,qcm,'q1',['c'],'Second',false,2);const e=content.qcmAiExport(ws.personal,qcm,1,1);assert.equal(e.questions[0].attempts.length,2);assert.deepEqual(e.questions[0].options,qcm.questions[0].options);assert.deepEqual(e.questions[0].correctOptionIds,['c']);assert.deepEqual(e.questions[0].selectedOptionIds,['c']);assert.equal(e.questions[0].reflection,'Second');assert.equal(e.questions[0].result,'correct');assert.throws(()=>content.qcmAiExport(ws.personal,qcm,0,2));assert.throws(()=>content.qcmAiExport(ws.personal,qcm,1,3));});
for(const target of [{kind:'article',articleId:article.id},{kind:'qcm',setId:qcm.id,questionId:'q2'}])for(const destination of ['here','tab','pane',5])test('127 typed '+target.kind+' routes to '+destination+' via shared router',()=>{const {ws,c}=populated();openReadingTarget(ws.personal,c,ws.overlays,target,destination);assert.equal(location(ws.personal).pageId,target.articleId??target.setId);if(target.questionId)assert.equal(location(ws.personal).anchor.questionId,target.questionId);assert.equal(activeSession(ws.personal).surface,undefined);validatePersonal(ws.personal);});
test('127 exact context targets retain PDF revision, cheatsheet page/block and QCM question',()=>{const {c}=populated(),pdf=c.documents[0],sheet=c.pages.find(p=>p.cheatsheet);for(const loc of [{...newLocation(pdf.pageId),pdfPage:2},{...newLocation(sheet.id),sheetPage:2,anchor:{sheetId:sheet.cheatsheet.pages[1].id,sheetPage:2,blockId:sheet.cheatsheet.pages[1].blocks[0].id}},{...newLocation(qcm.id),anchor:{questionId:'q2'}}]){const target=content.currentResourceTarget(c,loc);validateReadingTarget(target);if(target.kind==='pdf-page')assert.equal(target.pdfPage,2);if(target.kind==='cheatsheet-page')assert.equal(target.anchor.blockId,loc.anchor.blockId);if(target.kind==='qcm')assert.equal(target.questionId,'q2');}});
test('127 missing question refuses routing with no workspace/tab mutation',()=>{const {ws,c}=populated(),before=clone(ws.personal);assert.throws(()=>openReadingTarget(ws.personal,c,ws.overlays,{kind:'qcm',setId:qcm.id,questionId:'deleted'},5));assert.deepEqual(ws.personal,before);});
test('127 Dashboard target opens selected capture without replacing reader history',()=>{const {ws,c}=populated();openReadingTarget(ws.personal,c,ws.overlays,{kind:'qcm',setId:qcm.id,questionId:'q2'},'here');const before=clone(activeSession(ws.personal).panes);const [item]=content.captureRows(ws.personal,'note',[{text:'Capture'}],{subject:'it'});openReadingTarget(ws.personal,c,ws.overlays,{kind:'dashboard-item',itemId:item.id},'here');assert.equal(activeSession(ws.personal).surface,'dashboard');assert.deepEqual(activeSession(ws.personal).panes,before);surface.closeSurface(activeSession(ws.personal));assert.deepEqual(activeSession(ws.personal).panes,before);});
test('127 content-type switches preserve subject and independent expansion, not tabs',()=>{const {ws}=setup(),s=activeSession(ws.personal);s.categoryFilter='cloud';s.expanded=['folder.old'];const panes=clone(s.panes);surface.selectLibrary(s,'articles');s.expanded=['folder.articles'];surface.selectLibrary(s,'notes');assert.deepEqual(s.expanded,['folder.old']);surface.selectLibrary(s,'articles');assert.deepEqual(s.expanded,['folder.articles']);assert.equal(s.categoryFilter,'cloud');assert.deepEqual(s.panes,panes);validatePersonal(ws.personal);});
test('127 unused slot detection never resets a used reader or creates workspace six',()=>{const {ws}=setup();for(let n=1;n<=5;n++){selectWorkspace(ws.personal,n);const s=activeSession(ws.personal),v=newView('page.atlas.welcome');s.panes[0].views=[v];s.panes[0].active=v.id;}const before=clone(ws.personal);assert.equal(surface.openEmptyWorkspace(ws.personal),undefined);assert.deepEqual(ws.personal,before);});
test('127 dashboard derives bookmarks/read-later and scopes by shared folder; no duplicated stores',()=>{const {ws,c}=populated(),f=taxonomy.sharedFolders(c,ws.overlays).find(f=>f.subject==='it');ws.overlays.taxonomy={[qcm.id]:{subject:'it',folderId:f.id}};const target={kind:'qcm',setId:qcm.id,questionId:'q1'};addReadingBookmark(ws.personal,target,'Q bookmark','informatics');addReadLater(ws.personal,target,'Q queue','informatics');const before=clone(ws),cards=dashboardCards(c,ws);assert.equal(cards.filter(x=>x.row==='Bookmarks').length,1);assert.equal(cards.filter(x=>x.row==='Read later').length,1);assert.equal(filterDashboard(cards,c,ws,'it',f.id).length,2);assert.deepEqual(ws,before);});
test('127 older reading checkpoint cannot revert newer shared Article/QCM/capture/reference data',()=>{const {ws,c}=populated(),save=saveReadingState(ws.personal,'all','Before');content.captureRows(ws.personal,'note',[{text:'After'}]);content.answerQuestion(ws.personal,qcm,'q1',['c']);content.saveResponse(ws.personal,qcm,'q2',['a'],'Not checked');content.addNotebookReference(ws.overlays,{kind:'article',articleId:article.id},'Norsk',{subject:'norsk'});const shared=clone({attempts:ws.personal.qcmAttempts,responses:ws.personal.qcmResponses,captures:ws.personal.dashboardItems,overlays:ws.overlays});surface.openEmptyWorkspace(ws.personal);restoreReadingState(ws.personal,save);assert.deepEqual({attempts:ws.personal.qcmAttempts,responses:ws.personal.qcmResponses,captures:ws.personal.dashboardItems,overlays:ws.overlays},shared);validateState(ws,schemas);});
test('127 typed inline/Related/QCM explanation links validate and survive source records',()=>{const {ws,c}=populated(),target={kind:'qcm',setId:qcm.id,questionId:'q2'},page=clone(c.pages.find(p=>p.id==='page.atlas.welcome'));page.blocks.push({id:'native-link',type:'resource-link',label:'Question two',target});page.resourceLinks=[{label:'QCM',target}];validateHubPage(page);ws.overlays.pages[page.id]={page};validateState(ws,schemas);assert.ok(documentBlockMatches(c.pages.find(p=>p.id===qcm.id),'shuffle').some(h=>h.id==='q2'));});
for(const preset of ['summary','architecture','bilingual','vocabulary'])test('127 '+preset+' template uses unchanged native grammar and live SVG without overflow',()=>{const d=makeCheatsheetPreset(preset,'preset.'+preset);assert.equal(d.meta.preset,preset);const schema=JSON.parse(requireText('src/content/schemas/cheatsheet-v1.schema.json'));validateSchema(d,schema);for(let n=1;n<=d.pages.length;n++){const out=renderCheatsheetPage(d,n);assert.deepEqual(out.diagnostics,[]);assert.match(out.svg,/<text/);assert.doesNotMatch(out.svg,/<(?:script|foreignObject)/);}});
import {readFileSync} from 'node:fs';function requireText(p){return readFileSync(p,'utf8');}
test('127 old 1.2.6-shaped state and backups load without invented shared records',async()=>{const ws=blankWorkspace();delete ws.personal.session.surface;validateState(ws,schemas);const result=await makeBackup(ws,built,async k=>source.assets.find(a=>a.key===k));const decoded=await readBackup((await unzipBounded(result.bytes)).files,schemas);assert.deepEqual(decoded.workspace.personal,ws.personal);assert.equal(decoded.workspace.personal.qcmAttempts,undefined);assert.equal(decoded.workspace.overlays.references,undefined);});
test('127 full exact backup round trip includes all new sources, taxonomy, references, shared records and surface sessions',async()=>{const {ws,c}=populated();content.captureRows(ws.personal,'task',[{text:'Backup task',due:'2026-09-30',important:true}],{subject:'it'},{kind:'qcm',setId:qcm.id,questionId:'q2'});content.answerQuestion(ws.personal,qcm,'q2',['a','b','d'],'Grain');content.saveResponse(ws.personal,qcm,'q1',['a'],'Draft');content.addNotebookReference(ws.overlays,{kind:'article',articleId:article.id},'Norsk transcript',{subject:'norsk'});ws.overlays.taxonomy={[qcm.id]:null};activeSession(ws.personal).typeExpanded={articles:['folder.a'],qcm:['folder.q']};surface.selectLibrary(activeSession(ws.personal),'qcm');saveReadingState(ws.personal,'all','All new data');validateState(ws,schemas);const result=await makeBackup(ws,built,async key=>source.assets.find(a=>a.key===key));const decoded=await readBackup((await unzipBounded(result.bytes)).files,schemas);assert.deepEqual(decoded.workspace.personal,ws.personal);assert.deepEqual(decoded.workspace.overlays,ws.overlays);});

test('127 explicit unclassification wins over embedded source taxonomy',()=>{const {ws,c}=populated();ws.overlays.taxonomy={[qcm.id]:null};assert.equal(taxonomy.resourceTaxonomy(c,ws.overlays,qcm.id),undefined);assert.equal(taxonomy.targetTaxonomy(c,ws,{kind:'qcm',setId:qcm.id}),undefined);const cards=dashboardCards(c,ws);assert.equal(filterDashboard(cards,c,ws,'it').filter(x=>x.target?.setId===qcm.id).length,0);});
test('127 shared folder bookmarks participate in scoped Dashboard without copying a folder',()=>{const {ws,c}=populated(),folder=taxonomy.sharedFolders(c,ws.overlays).find(f=>f.subject==='it');const t={kind:'collection',collectionId:folder.id};addReadingBookmark(ws.personal,t,'Shared folder','informatics');assert.deepEqual(taxonomy.targetTaxonomy(c,ws,t),{subject:'it',folderId:folder.id,path:folder.path});const cards=filterDashboard(dashboardCards(c,ws),c,ws,'it',folder.id);assert.ok(cards.some(x=>x.title==='Shared folder'));});
test('127 native sibling order is stable in the Notebook projection',()=>{const {ws,c}=setup(),projects=taxonomy.projectLibrary(c,ws.overlays,'notes');function assertOrder(original,projected){const order=new Map(original.map((x,i)=>[x.id,i]));const indices=projected.filter(x=>order.has(x.id)).map(x=>order.get(x.id));assert.deepEqual(indices,[...indices].sort((a,b)=>a-b));for(const p of projected){const old=original.find(o=>o.id===p.id);if(old?.children&&p.children)assertOrder(old.children,p.children);}}for(const p of projects){const old=c.projects.find(x=>x.id===p.id);if(old)assertOrder(old.nodes,p.nodes);}});
