/** V2.3 functional/unit matrix. Pure plans and MemoryBackend are explicitly NOT
 * browser transaction/fault evidence; destructive compaction ships disabled. */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import JSZip from 'jszip';
import {built,schemas,provenance,demoWorkspace,withDemoBackend,resolveFor,compose,MemoryBackend,durabilityDemoDefinition,DEMO_PREFIX} from './v23/fixtures.mjs';
import {makeHistoryArchive,verifyHistoryArchive,planCompaction,liveAssetReachability,requiredRevisionAssets,resolveHistoryAssets,assertArchiveAttachment} from '../dist-offline/app/durability/archive.mjs';
import {validateDescriptor,descriptorIndex,revisionIdentity} from '../dist-offline/app/durability/descriptor.mjs';
import {attachArchive,detachArchive,clearArchiveAttachments,requireHistoricalRevision,archivedAsset,revisionIdentities,attachedPayload,isArchiveAttached} from '../dist-offline/app/durability/registry.js';
import {checkWorkspaceIntegrity,verifyBackupFile,createVerifiedBackup,createRecoveryBundle,verifyRecoveryBundle} from '../dist-offline/app/durability/recovery.js';
import {storageHealth,requestPersistence,preflightStorage,historyCapacity,capacityLevel} from '../dist-offline/app/durability/storage-health.mjs';
import {selectSavedArchive,consumeSavedSelection} from '../dist-offline/app/durability/ceremony.js';
import {removeDurabilityDemo,syntheticPdf} from '../dist-offline/app/durability/demo.js';
import {store,workspaceFromStoredRecords} from '../dist-offline/app/storage/database.js';
import {COMPACTION_BLOCKED} from '../dist-offline/app/durability/release-state.js';
import {unzipBounded,zipFiles,makeBackup,readBackup} from '../dist-offline/app/storage/archives.mjs';
import {validateHistory,HISTORY_LIMITS} from '../dist-offline/app/history/validation.mjs';
import {prepareWorkspaceHistory,assertProjection} from '../dist-offline/app/history/engine.js';
import {captureResources,resourceAdapters,historicalCatalogue} from '../dist-offline/app/history/adapters.js';
import {blankWorkspace,current} from '../dist-offline/app/core/workspace.js';
import {migratePersonal,activeSession} from '../dist-offline/app/core/workspace-slots.js';
import {createAgentInterface,getAgentCapabilities} from '../dist-offline/app/agent/service.js';
import {stable,sha256} from '../dist-offline/app/core/validation.mjs';
const encode=value=>new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value));
const decode=value=>JSON.parse(new TextDecoder().decode(value));
const ws=await demoWorkspace(),resolve=resolveFor(ws),resources=captureResources(compose(built,ws),ws);
const archive=await makeHistoryArchive(ws,provenance,resolve);
const proposed=await planCompaction(ws,archive,built.packs,resources,resolve);
const cold=proposed.workspace; // Detached in-memory model only. Nothing is written to IDB.
const keys=['notebook-page:demo.v23.notebook','article:demo.v23.article','cheatsheet:demo.v23.cheatsheet','qcm:demo.v23.qcm','pdf:demo.v23.document','notebook-tree:demo.v23.project'];
async function rewriteArchive(mutate,{reRoot=true}={}){
 const {files}=await unzipBounded(archive.bytes);files.delete('atlas-transfer.json');let manifest=decode(files.get('archive.json'));await mutate(files,manifest);
 if(reRoot){manifest.fileHashes={};for(const [name,bytes]of files)if(name!=='archive.json')manifest.fileHashes[name]=await sha256(bytes);const {rootHash,...descriptor}=manifest.descriptor;manifest.descriptor.rootHash=await sha256(stable({...manifest,descriptor}));}
 files.set('archive.json',encode(manifest));return zipFiles(files,'history-archive');
}
function rawOf(state){const rows=[state.history.meta,...state.history.heads,...state.history.revisions,...state.history.reviews,...(state.history.archives??[])],recordKey=r=>r.kind==='meta'?'meta':r.kind==='head'?'head:'+r.resourceKey:r.kind==='revision'?'revision:'+r.revisionId:r.kind==='review'?'review:'+r.id:'archive:'+r.archiveId;return {imports:{keys:state.imports.map(p=>p.manifest.id),values:structuredClone(state.imports)},overlays:{keys:['active'],values:[structuredClone(state.overlays)]},personal:{keys:['active'],values:[structuredClone(state.personal)]},assets:{keys:state.assets.map(a=>a.key),values:structuredClone(state.assets)},history:{keys:rows.map(recordKey),values:structuredClone(rows)}};}

test('V23 R: normal blank workspace has no demo and definitions are deterministic',async()=>{assert.equal(Object.keys(blankWorkspace().overlays.pages).length,0);assert.equal(stable(await durabilityDemoDefinition()),stable(await durabilityDemoDefinition()));assert.notDeepEqual(syntheticPdf(1),syntheticPdf(2));});
test('V23 R: optional demo has required versions, closed reviews, two PDF bytes and separate personal attempt',()=>{assert.deepEqual(keys.map(k=>ws.history.heads.find(h=>h.resourceKey===k).number),[8,5,4,4,4,5]);assert.deepEqual(ws.history.reviews.map(r=>r.status),['accepted','rejected','stale']);assert.equal(ws.assets.filter(a=>a.mediaType==='application/pdf').length,2);assert.equal(ws.personal.qcmAttempts.length,1);assert(ws.personal.bookmarks[0].target.historyRevisionId);});
test('V23 R: demo reloading is idempotent in the actual loader (unit backend)',async()=>withDemoBackend(async({load,backend})=>{await load();const first=stable(backend.state);await load();assert.equal(stable(backend.state),first);}));
test('V23 R: edited/colliding page is retained and installation refused',async()=>withDemoBackend(async({load,backend,store})=>{await load();backend.state.overlays.pages['demo.v23.article'].page.summary='User change';store.setLoaded(backend.state);const before=stable(backend.state);await assert.rejects(load,/retained|overwritten/);assert.equal(stable(backend.state),before);}));
test('V23 R: corrupt asset collision is refused before any demo write',async()=>withDemoBackend(async({load,backend,store})=>{const d=await durabilityDemoDefinition();backend.state.assets=[{...d.assets[0],bytes:encode('corrupt')}];store.setLoaded(backend.state);const before=stable(backend.state);await assert.rejects(load,/corrupt local asset/);assert.equal(stable(backend.state),before);}));
test('V23 R: safe removal keeps immutable history, audit and asset bytes',async()=>withDemoBackend(async({load,backend})=>{await load();const prior=structuredClone(backend.state),result=await removeDurabilityDemo(built);assert.equal(result.removed,5);assert.equal(Object.keys(backend.state.overlays.pages).filter(id=>id.startsWith(DEMO_PREFIX)).length,0);assert.deepEqual(backend.state.assets,prior.assets);for(const r of prior.history.revisions)assert.deepEqual(backend.state.history.revisions.find(x=>x.revisionId===r.revisionId),r);assert.deepEqual(backend.state.history.reviews,prior.history.reviews);}));
test('V23 R: removal retains a user bookmark and its current page and prunes only safe tree nodes',async()=>withDemoBackend(async({load,backend,store})=>{await load();backend.state.personal.bookmarks.push({id:'bookmark.user.keep',pageId:'demo.v23.notebook',title:'My bookmark',createdAt:100});store.setLoaded(backend.state);await removeDurabilityDemo(built);assert(backend.state.overlays.pages['demo.v23.notebook']);assert(backend.state.personal.bookmarks.some(b=>b.id==='bookmark.user.keep'));const c=compose(built,backend.state),walk=nodes=>nodes.forEach(n=>{if(n.pageId)assert(c.pages.some(p=>p.id===n.pageId),'dangling node '+n.pageId);if(n.children)walk(n.children);});walk(c.projects.find(p=>p.id==='demo.v23.project').nodes);}));
test('V23 R/N: personal QCM attempt edits create no authored QCM revision',async()=>{const backend=new MemoryBackend(structuredClone(ws));const before=stable(backend.state.history);await backend.personal(p=>p.qcmAttempts[0].reflection='A personal reflection');assert.equal(stable(backend.state.history),before);});

test('V23 B/E: strict stored-record reader preserves exactly five stores without writes',async()=>{const raw=rawOf(ws),before=stable(raw),read=workspaceFromStoredRecords(raw);assert.equal(stable(raw),before);assert.deepEqual(read.history,ws.history);await validateHistory(read.history,await resolveHistoryAssets(read.history.revisions,read.assets,resolveFor(read)),true);assert.equal(Object.keys(raw).length,5);});
for(const [label,mutate]of [
 ['wrong history key',r=>r.history.keys[0]='meta-copy'],['missing meta',r=>{r.history.keys.shift();r.history.values.shift();}],['unknown history record',r=>{r.history.keys.push('unknown');r.history.values.push({kind:'unknown'});}],['extra personal record',r=>{r.personal.keys.push('hidden');r.personal.values.push(r.personal.values[0]);}],['asset key mismatch',r=>r.assets.keys[0]='other-key'],['extra store',r=>r.surprise={keys:[],values:[]}]
])test('V23 E: stored '+label+' rejected without mutation',()=>{const raw=rawOf(ws);mutate(raw);const before=stable(raw);assert.throws(()=>workspaceFromStoredRecords(raw));assert.equal(stable(raw),before);});
test('V23 B: an empty fresh database remains empty during strict read-only normalization',()=>{const raw=Object.fromEntries(['imports','overlays','personal','assets','history'].map(n=>[n,{keys:[],values:[]}]));assert.equal(workspaceFromStoredRecords(raw).history.revisions.length,0);assert(raw.history.values.length===0);});

for(const [label,storage,expected]of [
 ['unsupported',{},'unsupported'],['estimate unavailable',{estimate:async()=>({})},'unavailable'],['estimate throws',{estimate:async()=>{throw Error('denied');}},'failed'],['estimate success',{estimate:async()=>({usage:10,quota:100})},'available']
])test('V23 C: '+label,async()=>assert.equal((await storageHealth(storage)).estimate.status,expected));
for(const [label,storage,expected]of [
 ['already persistent',{persisted:async()=>true,persist:async()=>{throw Error('must not request twice');}},'already-persistent'],['granted',{persisted:async()=>false,persist:async()=>true},'granted'],['denied',{persisted:async()=>false,persist:async()=>false},'denied'],['unsupported',{},'unsupported'],['failure',{persist:async()=>{throw Error('blocked');}},'failed']
])test('V23 C: persistence '+label,async()=>assert.equal((await requestPersistence(storage)).status,expected));
test('V23 C/D: preflight distinguishes enough, insufficient and unknown quota',async()=>{assert.equal((await preflightStorage(500,{estimate:async()=>({usage:0,quota:10000000})})).status,'estimated-enough');await assert.rejects(()=>preflightStorage(500,{estimate:async()=>({usage:9999000,quota:10000000})}),/Insufficient/);assert.equal((await preflightStorage(500,{})).status,'unknown');assert.equal((await preflightStorage(500,{estimate:async()=>{throw Error();}})).status,'unknown');await assert.rejects(()=>preflightStorage(-1,{}));await assert.rejects(()=>preflightStorage(Infinity,{}));});
test('V23 C/O: capacity warnings retain exact immutable limits',()=>{assert.deepEqual([.1,.7,.85,.95,1].map(capacityLevel),['healthy','watch','high','critical','critical']);const rows=historyCapacity(ws.history);assert.equal(rows.find(r=>r.name==='Live revisions').limit,HISTORY_LIMITS.totalRevisions);assert(rows.every(r=>Number.isFinite(r.ratio)));});

test('V23 G: archive generation freezes, serializes and verifies an oldest prefix without writing',async()=>{const before=stable(ws),a=await verifyHistoryArchive(archive.bytes);assert.equal(stable(ws),before);assert.deepEqual(a.descriptor,archive.descriptor);assert.equal(a.descriptor.counts.revisions,18);assert.equal(a.descriptor.counts.reviews,3);assert.equal(a.assets.length,3);for(const range of a.descriptor.ranges){assert.equal(range.revisions[0].number,1);assert(!range.revisions.some(r=>ws.history.heads.some(h=>h.revisionId===r.revisionId)));for(const r of range.revisions)assert.deepEqual(r,revisionIdentity(ws.history.revisions.find(x=>x.revisionId===r.revisionId)));}});
test('V23 G: one and multiple selected resources preserve exact requested ownership',async()=>{for(const selected of [[keys[0]],[keys[1],keys[3]]]){const a=await makeHistoryArchive(ws,provenance,resolve,{resourceKeys:selected,includeClosedReviews:false});assert.deepEqual(a.descriptor.ranges.map(r=>r.resourceKey).sort(),selected.sort());}});
test('V23 G: head-only selection and illegal retention cannot authorize an archive',async()=>{const fresh=await prepareWorkspaceHistory(built,blankWorkspace(),{source:'migration'});await assert.rejects(()=>makeHistoryArchive(fresh,provenance,resolveFor(fresh),{retain:1,includeClosedReviews:false}),/eligible/);for(const retain of [0,-1,1.5,2001])await assert.rejects(()=>makeHistoryArchive(ws,provenance,resolve,{retain}));});
test('V23 G: historical-only PDF and image bytes are present and immutable',async()=>{const d=await durabilityDemoDefinition();for(const i of [0,2,3]){const a=archive.assets.find(a=>a.key===d.assets[i].key);assert(a);assert.deepEqual(a.bytes,d.assets[i].bytes);assert.equal(await sha256(a.bytes),a.sha256);}assert(!archive.assets.some(a=>a.key===d.assets[1].key));});
test('V23 G/N: pending and live-spanning audit rows stay live in a proposed plan',async()=>{const next=structuredClone(ws);const staged=structuredClone(next.history.reviews[1]);staged.id='review.pending.v23';staged.plan.id=staged.id;staged.status='staged';delete staged.decidedAt;next.history.reviews.push(staged);const live=next.history.revisions.find(r=>r.revisionId===next.history.heads.find(h=>h.resourceKey===keys[0]).revisionId);live.changeSetId='review.span.v23';next.history.reviews.push({kind:'review',schemaVersion:1,id:'review.span.v23',status:'accepted',createdAt:1,decidedAt:2,plan:{schemaVersion:1,kind:'atlas-agent-changeset',id:'review.span.v23',operations:[]},revisionIds:[live.revisionId]});const a=await makeHistoryArchive(next,provenance,resolveFor(next));assert(!a.reviews.some(r=>['review.pending.v23','review.span.v23'].includes(r.id)));const p=await planCompaction(next,a,built.packs,captureResources(compose(built,next),next),resolveFor(next));assert(p.workspace.history.reviews.some(r=>r.id===staged.id));assert(p.workspace.history.reviews.some(r=>r.id==='review.span.v23'));});

test('V23 H: exact saved bytes verify, wrong or altered bytes do not',async()=>{assert.equal((await verifyHistoryArchive(archive.bytes,archive)).fileHash,archive.fileHash);const other=await makeHistoryArchive(ws,provenance,resolve);await assert.rejects(()=>verifyHistoryArchive(other.bytes,archive),/exact saved archive/);const corrupt=new Uint8Array(archive.bytes);corrupt[50]^=1;await assert.rejects(()=>verifyHistoryArchive(corrupt,archive));});
test('V23 H: valid repacking is not the exact independently saved candidate',async()=>{const zip=await JSZip.loadAsync(archive.bytes);zip.comment='Different outer ZIP';const bytes=await zip.generateAsync({type:'uint8array'});await verifyHistoryArchive(bytes);await assert.rejects(()=>verifyHistoryArchive(bytes,archive),/exact saved archive/);});
test('V23 H/I: no synthetic event, forged receipt, URL flag or direct method can enable destructive compaction',async()=>{assert.equal(COMPACTION_BLOCKED,true);await assert.rejects(()=>selectSavedArchive(new Event('change'),archive,ws,built,resolve),/file chooser/);assert.throws(()=>consumeSavedSelection({},new Event('click')),/Explicit confirmation/);const before=stable(store.state);await assert.rejects(()=>store.compactArchive({},new Event('click'),resolve),/disabled/);assert.equal(stable(store.state),before);const source=await fs.readFile('src/storage/database.ts','utf8');assert(!source.includes('history.delete('));assert(!source.includes('commitCompaction('));});
for(const [label,mutate]of [
 ['root tampering',(f,m)=>m.descriptor.rootHash='0'.repeat(64)],
 ['missing shard',(f,m)=>f.delete(m.revisionShards[0])],
 ['bad parent',(f,m)=>m.descriptor.ranges[0].revisions[0].parentRevisionId='revision.fake'],
 ['duplicate owner',(f,m)=>m.descriptor.ranges.push(structuredClone(m.descriptor.ranges[0]))],
 ['missing asset',(f,m)=>f.delete(m.descriptor.assets[0].path)],
 ['corrupt asset',(f,m)=>{const p=m.descriptor.assets[0].path,b=new Uint8Array(f.get(p));b[20]^=1;f.set(p,b);}],
 ['snapshot hash mismatch',(f,m)=>{const p=m.revisionShards[0],rows=decode(f.get(p));rows[0].snapshot.page.title+='bad';f.set(p,encode(rows));}],
 ['unsupported version',(f,m)=>m.archiveSchema=99],
 ['extra payload',(f,m)=>f.set('unowned.txt',encode('x'))]
])test('V23 G/J: archive '+label+' rejected even after outer transfer refresh',async()=>{const bytes=await rewriteArchive(mutate,{reRoot:label!=='root tampering'});await assert.rejects(()=>verifyHistoryArchive(bytes));});
test('V23 G: bad archive provenance rejected',async()=>{const bytes=await rewriteArchive((f,m)=>m.descriptor.provenance.sourceCommit='main');await assert.rejects(()=>verifyHistoryArchive(bytes));});

test('V23 J: proposed asset plan retains shared/current bytes and only names verified archived-only assets',async()=>{const d=await durabilityDemoDefinition();assert(proposed.preview.assetKeys.includes(d.assets[0].key));assert(proposed.preview.assetKeys.includes(d.assets[2].key));assert(!proposed.preview.assetKeys.includes(d.assets[1].key));assert(!proposed.preview.assetKeys.includes(d.assets[3].key));assert.equal(proposed.preview.assetBytes,860);assert.deepEqual(cold.history.heads,ws.history.heads);assert.deepEqual(cold.overlays,ws.overlays);assert.deepEqual(cold.personal,ws.personal);await assertProjection(compose(built,cold),cold);});
test('V23 J: imported, personal and same-SHA owners are conservatively retained',async()=>{const d=await durabilityDemoDefinition(),old=d.assets[0];for(const mutate of [w=>w.imports.push({assetKeys:[old.key],documents:[]}),w=>w.personal.notes['note.keep']={text:old.key,pageId:'demo.v23.notebook',updatedAt:1},w=>w.overlays.documents.push({assetKey:old.key,sha256:old.sha256})]){const w=structuredClone(ws);mutate(w);const r=liveAssetReachability(w,[],[],[]);assert(r.keys.has(old.key)||r.hashes.has(old.sha256));}const w=structuredClone(ws);w.assets.push({...old,key:'local-alias.pdf'});const r=liveAssetReachability(w,[],[],[{snapshot:{assetRefs:{alias:{key:'local-alias.pdf',sha256:old.sha256,mediaType:old.mediaType}}}}]);assert(r.hashes.has(old.sha256));});
test('V23 I (pure precondition only): stale history epoch or bytes reject the proposed plan',async()=>{for(const mutate of [w=>w.history.meta.epoch++,w=>w.history.revisions[0].summary+='changed']){const w=structuredClone(ws);mutate(w);const before=stable(w);await assert.rejects(()=>planCompaction(w,archive,built.packs,resources,resolve),/History changed/);assert.equal(stable(w),before);}});

test('V23 L: missing archive names exact ID/root and never substitutes current content',()=>{clearArchiveAttachments();const old=archive.revisions[0];assert.throws(()=>requireHistoricalRevision(cold.history,old.revisionId),new RegExp(archive.descriptor.archiveId));const missing=historicalCatalogue(compose(built,cold),cold,old.revisionId);assert(missing.warning.includes(archive.descriptor.archiveId));});
test('V23 L: exact attachment is session-only, immutable to callers and has no approval side effects',async()=>{clearArchiveAttachments();const before=stable(cold);await attachArchive(archive.bytes,cold.history);const r=requireHistoricalRevision(cold.history,archive.revisions[0].revisionId);r.summary='Caller mutation';assert.notEqual(requireHistoricalRevision(cold.history,r.revisionId).summary,r.summary);const asset=archivedAsset(cold.history,archive.assets[0].key);asset.bytes[0]^=1;assert.deepEqual(archivedAsset(cold.history,archive.assets[0].key).bytes,archive.assets[0].bytes);assert.equal(stable(cold),before);assert(isArchiveAttached(cold.history,archive.descriptor.archiveId));await assert.rejects(()=>attachArchive(archive.bytes,ws.history),/exact archive/);clearArchiveAttachments();});
for(const key of keys.slice(0,5))test('V23 K/L: '+key.split(':')[0]+' live and archived old A/current B keep stable identity regardless of prior active pane (unit backend)',async()=>{
 for(const archived of [false,true]){clearArchiveAttachments();const state=structuredClone(archived?cold:ws);if(archived)await attachArchive(archive.bytes,state.history);const backend=new MemoryBackend(state),api=createAgentInterface(built,backend),old=revisionIdentities(state.history).filter(r=>r.resourceKey===key).sort((a,b)=>a.number-b.number)[0];await api.compareRevisions(key,old.revisionId);await api.setAgentCompareState({enabled:true,pane:'B',mode:'b'});await api.compareRevisions(key,old.revisionId);const summary=api.getWorkspaceSummary().slots.find(s=>s.id===1);assert.equal(summary.compareMode,'changes');const [a,b]=summary.panes.map(p=>p.tabs.find(t=>t.id===p.activeTab));assert.equal(a.target.historyRevisionId,old.revisionId);assert.equal(b.target.historyRevisionId,undefined);assert.equal(api.getResource(key,old.revisionId).resourceId,api.getResource(key).resourceId);for(const mode of ['side-by-side','a','b','changes']){await api.setAgentCompareState({enabled:true,mode});assert.equal(api.getWorkspaceSummary().slots[0].compareMode,mode);}}
 clearArchiveAttachments();
});
test('V23 L: archived restore-as-new retains restoredFromRevisionId and restores needed historical bytes (unit backend)',async()=>{
 clearArchiveAttachments();const backend=new MemoryBackend(structuredClone(cold)),api=createAgentInterface(built,backend);await attachArchive(archive.bytes,backend.state.history);const r=archive.revisions.find(r=>r.resourceType==='pdf'),head=backend.state.history.heads.find(h=>h.resourceKey===r.resourceKey);const id='plan.v23.archived-restore';await api.stage({schemaVersion:1,kind:'atlas-agent-changeset',id,createdAt:Date.now(),source:'Synthetic archived restore unit test',operations:[{id:'operation.v23.restore',kind:'resource.restoreAsNewRevision',resourceKey:r.resourceKey,baseRevisionId:head.revisionId,payload:{revisionId:r.revisionId}}]});await api.accept(id);const h=backend.state.history.heads.find(h=>h.resourceKey===r.resourceKey),latest=backend.state.history.revisions.find(x=>x.revisionId===h.revisionId);assert.equal(latest.number,head.number+1);assert.equal(latest.restoredFromRevisionId,r.revisionId);assert.deepEqual(latest.snapshot,r.snapshot);assert(backend.state.assets.some(a=>a.key===r.snapshot.document.assetKey));await validateHistory(backend.state.history,await resolveHistoryAssets(backend.state.history.revisions,backend.state.assets,resolveFor(backend.state)),true);clearArchiveAttachments();
});
test('V23 M: repeated archive ranges do not overlap; one missing file never damages another',async()=>{const later=structuredClone(cold);later.overlays.pages['demo.v23.notebook'].page.summary='A later authored edit';const next=await prepareWorkspaceHistory(built,later,{source:'manual'});const second=await makeHistoryArchive(next,provenance,resolveFor(next),{retain:1,resourceKeys:[keys[0]],includeClosedReviews:false});const projected=await planCompaction(next,second,built.packs,captureResources(compose(built,next),next),resolveFor(next));descriptorIndex(projected.workspace.history.archives);assert(!second.revisions.some(r=>archive.revisions.some(a=>a.revisionId===r.revisionId)));clearArchiveAttachments();await attachArchive(second.bytes,projected.workspace.history);assert(requireHistoricalRevision(projected.workspace.history,second.revisions[0].revisionId));assert.throws(()=>requireHistoricalRevision(projected.workspace.history,archive.revisions[0].revisionId),/requires archive/);await attachArchive(archive.bytes,projected.workspace.history);detachArchive(second.descriptor.archiveId);assert(requireHistoricalRevision(projected.workspace.history,archive.revisions[0].revisionId));assert.throws(()=>requireHistoricalRevision(projected.workspace.history,second.revisions[0].revisionId),/requires archive/);clearArchiveAttachments();});
test('V23 N: Agent has no archive, compaction, delete-history or secret capability',()=>{const json=JSON.stringify(getAgentCapabilities());assert(!/history\.delete|archive\.compact|accessKey|sessionSecret/.test(json));const api=createAgentInterface(built,new MemoryBackend(structuredClone(ws)));for(const name of ['compactArchive','deleteHistory','archiveHistory','generateAccessKey'])assert.equal(api[name],undefined);});

const verifiedBackup=await createVerifiedBackup(ws,built,resolve,provenance,schemas);
async function rewriteBackup(mutate){const {files}=await unzipBounded(verifiedBackup.bytes);files.delete('atlas-transfer.json');const m=decode(files.get('backup.json'));await mutate(files,m);m.payloadHashes={};for(const [name,b]of files)if(name!=='backup.json')m.payloadHashes[name]=await sha256(b);const {rootHash,...unsigned}=m;m.rootHash=await sha256(stable(unsigned));files.set('backup.json',encode(m));return zipFiles(files,'backup');}
async function alterHistory(files,mutate){const index=decode(files.get('history/index.json'));const h={schemaVersion:1,meta:index.meta,heads:index.heads,...(index.archives!==undefined?{archives:index.archives}:{}),revisions:index.revisionShards.flatMap(p=>decode(files.get(p))),reviews:index.reviewShards.flatMap(p=>decode(files.get(p)))};await mutate(h);index.meta=h.meta;index.heads=h.heads;if(h.archives!==undefined)index.archives=h.archives;index.hash=await sha256(stable(h));let n=0;for(const p of index.revisionShards){const count=decode(files.get(p)).length;files.set(p,encode(h.revisions.slice(n,n+count)));n+=count;}files.set('history/index.json',encode(index));}

test('V23 E/F: healthy integrity and standalone verification are read-only',async()=>{const before=stable(ws),result=await checkWorkspaceIntegrity(ws,built,resolve,schemas,provenance);assert.equal(result.status,'PASS');assert.equal(stable(ws),before);assert.equal(verifiedBackup.summary.schema,5);assert.equal(verifiedBackup.summary.provenance.sourceCommit,provenance.sourceCommit);});
for(const schema of [2,3,4,5])test('V23 B/F: real backup schema '+schema+' verifies with the same restore validator',async()=>{let value=blankWorkspace();if(schema===3)value.personal=migratePersonal(value.personal);if(schema>=4)value=structuredClone(ws);const backup=await makeBackup(value,built,resolveFor(value),schema===5?provenance:undefined);const v=await verifyBackupFile(backup.bytes,built,schemas);assert.equal(v.backup.schemaVersion,schema);const {files}=await unzipBounded(backup.bytes),direct=await readBackup(files,schemas);assert.equal(direct.schemaVersion,schema);assert.equal(stable(value),stable(schema>=4?ws:value));});
for(const [label,mutate]of [
 ['bad parent',w=>w.history.revisions.find(r=>r.resourceKey===keys[0]&&r.number===2).parentRevisionId='revision.missing'],
 ['bad head',w=>w.history.heads[0].number++],
 ['snapshot hash mismatch',w=>w.history.revisions[0].contentHash='0'.repeat(64)],
 ['missing local asset',w=>w.assets.shift()],
 ['corrupt local asset',w=>w.assets[0].bytes[0]^=1],
 ['PDF provenance violation',w=>w.history.revisions.find(r=>r.resourceType==='pdf'&&r.resourceKey===keys[4]).snapshot.pdfProvenance.sha256='0'.repeat(64)],
 ['invalid descriptor',w=>w.history.archives=[{kind:'archive'}]]
])test('V23 E: '+label+' fails integrity with exact source-state equality',async()=>{const bad=structuredClone(ws);mutate(bad);const before=stable(bad);await assert.rejects(()=>checkWorkspaceIntegrity(bad,built,resolveFor(bad),schemas,provenance));assert.equal(stable(bad),before);});
for(const [label,mutate]of [
 ['missing shard',(files)=>files.delete(decode(files.get('history/index.json')).revisionShards[0])],
 ['history hash mismatch',(files)=>{const index=decode(files.get('history/index.json'));index.hash='0'.repeat(64);files.set('history/index.json',encode(index));}],
 ['asset SHA mismatch',(files,m)=>{const path=m.assetIndex[0].path,b=new Uint8Array(files.get(path));b[0]^=1;files.set(path,b);}],
 ['missing private PDF',(files,m)=>files.delete(m.assetIndex.find(a=>a.mediaType==='application/pdf').path)],
 ['bad head relationship',files=>alterHistory(files,h=>h.heads[0].number++)],
 ['canonical identity violation',files=>alterHistory(files,async h=>{const r=h.revisions.find(r=>r.resourceType==='article');r.snapshot.page.article.id='article.wrong';r.contentHash=await sha256(stable(r.snapshot));const head=h.heads.find(x=>x.revisionId===r.revisionId);if(head)head.contentHash=r.contentHash;})],
 ['PDF provenance violation',files=>alterHistory(files,async h=>{const r=h.revisions.find(r=>r.resourceType==='pdf');r.snapshot.pdfProvenance.commit='main';r.contentHash=await sha256(stable(r.snapshot));const head=h.heads.find(x=>x.revisionId===r.revisionId);if(head)head.contentHash=r.contentHash;})],
 ['bad projection',(files,m)=>m.workspace.overlays.pages['demo.v23.article'].page.summary='Unversioned change']
])test('V23 F: '+label+' backup rejected after fully refreshed envelope',async()=>{const bytes=await rewriteBackup(mutate);await assert.rejects(()=>verifyBackupFile(bytes,built,schemas));});
test('V23 F: corrupt JSON and traversal are rejected without executing or extracting files',async()=>{const {files}=await unzipBounded(verifiedBackup.bytes);files.delete('atlas-transfer.json');files.set('backup.json',encode('{truncated'));await assert.rejects(()=>zipFiles(files,'backup').then(b=>verifyBackupFile(b,built,schemas)));const zip=new JSZip();zip.file('../backup.json','{}');await assert.rejects(()=>zip.generateAsync({type:'uint8array'}).then(b=>verifyBackupFile(b,built,schemas)));});
test('V23 F: validators never open IndexedDB',async()=>{const previous=globalThis.indexedDB;let opened=0;globalThis.indexedDB={open(){opened++;throw Error('Validator must be read-only');}};try{await verifyBackupFile(verifiedBackup.bytes,built,schemas);await verifyHistoryArchive(archive.bytes);assert.equal(opened,0);}finally{if(previous===undefined)delete globalThis.indexedDB;else globalThis.indexedDB=previous;}});

test('V23 P: complete recovery requires every exact archive and restores detached projection/index/bytes',async()=>{await assert.rejects(()=>createRecoveryBundle(cold,built,resolveFor(cold),provenance,schemas,()=>undefined),/required archive/);const bundle=await createRecoveryBundle(cold,built,resolveFor(cold),provenance,schemas,id=>id===archive.descriptor.archiveId?archive.bytes:undefined);const verified=await verifyRecoveryBundle(bundle.bytes,built,schemas);assert.equal(verified.archives.length,1);assert.deepEqual(verified.backup.workspace.history,cold.history);assert.deepEqual(captureResources(compose(built,verified.backup.workspace),verified.backup.workspace),captureResources(compose(built,cold),cold));await assertProjection(compose(built,verified.backup.workspace),verified.backup.workspace);clearArchiveAttachments();await attachArchive(verified.archives[0].bytes,verified.backup.workspace.history);const old=archive.revisions.find(r=>r.resourceType==='pdf');assert.deepEqual(archivedAsset(verified.backup.workspace.history,old.snapshot.document.assetKey).bytes,ws.assets.find(a=>a.key===old.snapshot.document.assetKey).bytes);assert.equal((await checkWorkspaceIntegrity(verified.backup.workspace,built,resolveFor(verified.backup.workspace),schemas,provenance)).status,'PASS');clearArchiveAttachments();assert.throws(()=>requireHistoricalRevision(verified.backup.workspace.history,old.revisionId),/requires archive/);});
test('V23 P: tampered complete recovery payload fails before restore',async()=>{const bundle=await createRecoveryBundle(cold,built,resolveFor(cold),provenance,schemas,()=>archive.bytes),{files}=await unzipBounded(bundle.bytes);files.delete('atlas-transfer.json');const asset=[...files.keys()].find(k=>k.startsWith('archives/')&&k.endsWith('.pdf'));files.delete(asset);await assert.rejects(()=>zipFiles(files,'complete-recovery').then(b=>verifyRecoveryBundle(b,built,schemas)));});
test('V23 Q: save-safety state warns for pending/failure and clears only after real state is clear',()=>{const old={saving:store.saving,error:store.error};try{store.saving=0;store.error='';assert.equal(store.unsafeClose,false);store.saving=1;assert.equal(store.unsafeClose,true);store.saving=0;store.error='Write failed';assert.equal(store.unsafeClose,true);store.error='';assert.equal(store.unsafeClose,false);}finally{store.saving=old.saving;store.error=old.error;}});
test('V23 S: history and Read Later remain semantically distinct icons',async()=>{const history=await fs.readFile('src/history/HistoryMenuItems.tsx','utf8'),rail=await fs.readFile('src/components/ReaderRail.tsx','utf8'),icons=await fs.readFile('src/components/Icon.tsx','utf8');assert.match(history,/name="history"/);assert.match(rail,/Version History/);assert.match(icons,/history:/);assert.match(icons,/clock:/);});
test('V23 L/W: cached archive cannot serve a modified descriptor even with same ID/root',async()=>{clearArchiveAttachments();await attachArchive(archive.bytes,cold.history);const altered=structuredClone(cold.history);altered.archives[0].counts.assetBytes++;assert.equal(isArchiveAttached(altered,archive.descriptor.archiveId),false);assert.equal(attachedPayload(altered,archive.descriptor.archiveId),undefined);assert.throws(()=>requireHistoricalRevision(altered,archive.revisions[0].revisionId),/requires archive/);clearArchiveAttachments();});
test('V23 R: ordinary related-page references retain a demo page during cleanup',async()=>withDemoBackend(async({load,backend,store})=>{await load();const page=structuredClone(backend.state.overlays.pages['demo.v23.notebook'].page);page.id='user.notebook.links';page.related=['demo.v23.article'];backend.state.overlays.pages[page.id]={page};store.setLoaded(backend.state);await removeDurabilityDemo(built);assert(backend.state.overlays.pages['demo.v23.article']);assert(backend.state.overlays.pages['user.notebook.links']);}));
