import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateEdgeDeclarations} from '../tools/check-access-build.mjs';
import {config as auth} from '../netlify/edge-functions/atlas-auth.js';import {config as unlock} from '../netlify/edge-functions/atlas-unlock.js';import {config as lock} from '../netlify/edge-functions/atlas-lock.js';
import {V23_GATES,COMPACTION_FAULTS,CAPACITY_BOUNDARIES,releaseStatus} from '../tools/v23-release-contract.mjs';
import {compareBuildIdentity} from '../tools/check-v23-build.mjs';
const config={auth,unlock,lock},toml=fs.readFileSync('netlify.toml','utf8');
test('V23 exact reviewed routing declaration passes',()=>validateEdgeDeclarations(config,toml));
for(const [key,value] of Object.entries({method:'GET',header:{x:'y'},pattern:'/private',excludedPattern:'/assets',cache:'manual',onError:'continue'}))test('V23 routing restriction '+key+' cannot silently pass',()=>{const c=structuredClone(config);c.auth[key]=value;assert.throws(()=>validateEdgeDeclarations(c,toml));});
for(const name of ['auth','unlock','lock'])test('V23 rejects extra '+name+' routing predicates',()=>{const c=structuredClone(config);c[name].method='POST';assert.throws(()=>validateEdgeDeclarations(c,toml));});
for(const value of [toml.replace('publish = "dist"','publish = "public"'),toml+'\n[[edge_functions]]\npath="/*"',toml+'\n[context.production]\npublish="public"'])test('V23 rejects provider config shadow',()=>assert.throws(()=>validateEdgeDeclarations(config,value)));
const green=()=>V23_GATES.map(id=>({id,status:'PASS',exitCode:0,signal:null}));
test('V23 all required suites are needed',()=>assert.equal(releaseStatus(green()),'READY FOR COORDINATOR QA'));
for(const id of V23_GATES)test('V23 omitted '+id+' remains BLOCKED',()=>assert.equal(releaseStatus(green().filter(r=>r.id!==id)),'BLOCKED'));
for(const status of ['BLOCKED','FAIL','SKIP','AVAILABLE_NOT_PROVIDER_CERTIFICATION'])test('V23 '+status+' cannot mean PASS',()=>{const rows=green();rows[0].status=status;assert.equal(releaseStatus(rows),'BLOCKED');});
test('V23 rejects duplicate results',()=>{const rows=green();rows[0]=rows[1];assert.equal(releaseStatus(rows),'BLOCKED');});
test('V23 rejects timeout/nonzero exit relabeling',()=>{for(const change of [{signal:'SIGTERM'},{exitCode:2}]){const rows=green();Object.assign(rows[0],change);assert.equal(releaseStatus(rows),'BLOCKED');}});
test('V23 exact fault and capacity coverage checklist',()=>{assert.equal(new Set(COMPACTION_FAULTS).size,13);assert.equal(CAPACITY_BOUNDARIES.length,4);});
const source={sourceCommit:'candidate',sourceDirty:false},build={sourceCommit:'candidate',sourceHash:'hash',sourceDirty:false,buildKind:'integrated',appVersion:'2.3.0',databaseVersion:3,pdfAtlasCommit:'fa5e83f7825cdc837078f87c5e130cb012332195'};
test('V23 clean current integrated identity passes',()=>assert.deepEqual(compareBuildIdentity(build,source,'hash'),[]));
for(const change of [{sourceCommit:'old'},{sourceHash:'old'},{buildKind:'compatibility'},{sourceDirty:true},{databaseVersion:4},{pdfAtlasCommit:'other'}])test('V23 rejects incompatible build '+JSON.stringify(change),()=>assert(compareBuildIdentity({...build,...change},source,'hash').length));
test('V23 workflow runs mandatory aggregate before publishing build',()=>{const c=fs.readFileSync('.github/workflows/ci.yml','utf8');assert(c.includes('run: npm run test:v23:release'));assert(c.indexOf('run: npm run test:v23:release')<c.indexOf('name: atlasnote-integrated-production-dist'));assert(!c.includes('continue-on-error'));});
test('V23 aggregate commands all exist in package scripts',()=>{const p=JSON.parse(fs.readFileSync('package.json','utf8'));for(const id of V23_GATES)assert(p.scripts[id],id);});
import {secretRules} from '../tools/check-v23-secrets.mjs';
test('V23 secret scanner permits identifiers but not a plaintext key',()=>{assert.deepEqual(secretRules('ATLASNOTE_ACCESS_KEY_SHA256 and atlas1_ are format identifiers'),[]);assert(secretRules('atlas1_'+'q'.repeat(43)).includes('plaintext-access-key'));});
test('V23 secret scanner rejects literal verifier and private key without returning values',()=>{for(const text of ['ATLASNOTE_ACCESS_KEY_SHA256='+ 'f'.repeat(64),'-----BEGIN '+'PRIVATE KEY-----'])assert(secretRules(text).length);});
test('V23 secret scanner catches a client secret assignment',()=>assert(secretRules('VITE_ACCESS_TOKEN="'+'Z'.repeat(32)+'"').includes('vite-secret')));
test('V23 every inherited CI run command and its order is unchanged',()=>{const expected=JSON.parse(fs.readFileSync('tools/v23-inherited-ci.json','utf8')).commands;const actual=[...fs.readFileSync('.github/workflows/ci.yml','utf8').matchAll(/^      - run: (.*)$/gm)].map(m=>m[1]).filter(x=>x!=='npm run test:v23:release');assert.deepEqual(actual,expected);});
