"""V2.1 visual authoring on the production origin, real IndexedDB and fresh-profile backup restore."""
import json,os,traceback
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
from browser_support import ROOT,start_server,launch,close_panels,choose_library_resource,open_settings,show_reader_controls
from persistence_assertions import assert_personal_after_open

OUT=Path(os.environ.get('ATLAS_EVIDENCE',ROOT/'docs/evidence/final-polish/runtime'));OUT.mkdir(parents=True,exist_ok=True)
READ="""()=>new Promise((resolve,reject)=>{const r=indexedDB.open('knowledge-atlas');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const d=r.result,t=d.transaction(['personal','overlays'],'readonly'),p=t.objectStore('personal').get('active'),o=t.objectStore('overlays').get('active');t.oncomplete=()=>{d.close();resolve({personal:p.result,overlays:o.result});};};})"""
results=[];errors=[];phase='startup';base=start_server()
try:
 with sync_playwright() as pw:
  browser=launch(pw);ctx=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True);p=ctx.new_page();p.set_default_timeout(12000);p.on('pageerror',lambda e:errors.append(str(e)))
  def click(name):p.get_by_role('button',name=name,exact=True).last.click()
  def state():p.wait_for_timeout(300);return p.evaluate(READ)
  def record():results.append({'name':phase,'status':'PASS'});print('PASS',phase,flush=True)
  def search(title):
   close_panels(p);p.keyboard.press('Control+k');p.get_by_label('Search all pages and glossary',exact=True).fill(title);p.locator('.search-result').filter(has_text=title).first.click()
  def manager(kind,id):
   close_panels(p);click(kind+' content');choose_library_resource(p,id)
  def field(name,value):p.get_by_label(name,exact=True).fill(value)
  p.goto(base,wait_until='networkidle');assert p.title()=='AtlasNote V2.2';expect(p.locator('.atlas-app')).to_be_visible();record()
  phase='visual single and multiple authoring with invalid-state validation'
  click('QCM content');click('New/import QCM');expect(p.get_by_label('Set title',exact=True)).to_be_visible();assert not p.get_by_label('QCM JSON',exact=True).count()
  field('Set title','Visual regression QCM');field('Question 1 prompt','Which value is even?');field('Question 1 option 1','Two');field('Question 1 option 2','Three');field('Question 1 option 1 explanation','Two divides by two.');field('Question 1 option 2 explanation','Three is odd.');field('Question 1 global explanation','Even numbers divide by two.');field('Question 1 follow-up','What about four?')
  click('Add question');field('Question 2 prompt','Select the even values.');field('Question 2 option 1','Four');field('Question 2 option 2','Six');p.get_by_label('Question 2 answer mode',exact=True).select_option('multiple');click('Import local content');expect(p.locator('dialog[open]')).to_have_count(1);assert not (state().get('overlays') or {}).get('pages')
  p.get_by_label('Question 2 option 1 correct',exact=True).check();p.get_by_label('Question 2 option 2 correct',exact=True).check();field('Question 2 global explanation','Both are divisible by two.');p.get_by_label('Classification subject',exact=True).last.select_option('it')
  assert p.get_by_label('Question 1 option 1 explanation',exact=True).bounding_box()['width']>400;p.screenshot(path=str(OUT/'qcm-desktop.png'));p.set_viewport_size({'width':390,'height':844});p.screenshot(path=str(OUT/'qcm-narrow.png'));assert p.locator('dialog').evaluate('(e)=>e.scrollWidth<=e.clientWidth+2');p.set_viewport_size({'width':1440,'height':1000});click('Import local content');expect(p.locator('.qcm-reader')).to_be_visible();qcm=next(v['page']['qcm'] for v in state()['overlays']['pages'].values());assert len(qcm['questions'][0]['correctOptionIds'])==1;assert len(qcm['questions'][1]['correctOptionIds'])==2;record()
  phase='answer reveal explanations and stable visual edit'
  p.locator('.qcm-options input').first.check();click('Check answer');expect(p.locator('.qcm-explanation')).to_contain_text('Even numbers divide by two.');expect(p.locator('.qcm-options')).to_contain_text('Two divides by two.');click('Next question');click('Reveal answer');expect(p.locator('.qcm-explanation')).to_contain_text('Both are divisible by two.')
  manager('QCM',qcm['id']);click('Edit / details');field('Question 1 option 2','Five');field('Question 1 option 2 explanation','Five is odd.');p.get_by_label('Question 1 option 2 correct',exact=True).check();click('Save content');expect(p.locator('.qcm-reader')).to_be_visible();updated=state()['overlays']['pages'][qcm['id']]['page']['qcm'];assert updated['questions'][0]['options'][1]['id']==qcm['questions'][0]['options'][1]['id'];assert updated['questions'][0]['correctOptionIds']==[qcm['questions'][0]['options'][1]['id']];assert len(state()['personal']['qcmAttempts'])==2
  with p.expect_download() as dl:click('Export QCM set')
  dl.value.save_as(str(OUT/'qcm.json'));assert json.loads((OUT/'qcm.json').read_text())==updated;record()
  phase='Article import reclassification source edit and independent Notebook reference'
  click('Article content');click('Add article');field('Title','Coherent article');field('Pasted article or transcript','A stable article body.');p.get_by_label('Classification subject',exact=True).last.select_option('it');click('Import local content');expect(p.locator('dialog[open]')).to_have_count(0);article=next(v['page'] for v in state()['overlays']['pages'].values() if v['page'].get('article'));aid=article['id']
  manager('Article',aid);p.get_by_label('Reference destination subject',exact=True).select_option('it');folder=p.get_by_label('Reference destination folder',exact=True).locator('option').evaluate_all('(es)=>es.find(e=>e.value).value');p.get_by_label('Reference destination folder',exact=True).select_option(folder);click('Add reference to Notebook');pin=state()['overlays']['references'][0]
  p.get_by_label('Classification subject',exact=True).last.select_option('cloud');click('Save classification');click('Edit / details');expect(p.get_by_label('Classification subject',exact=True).last).to_have_value('cloud');p.get_by_label('Classification subject',exact=True).last.select_option('norsk');click('Save content');expect(p.locator('dialog[open]')).to_have_count(0);v=state();assert v['overlays']['pages'][aid]['page']['article']['taxonomy']==v['overlays']['taxonomy'][aid]=={'subject':'norsk'};assert v['overlays']['references'][0]==pin
  manager('Article',aid);click('JSON');value=json.loads(p.get_by_label('Resource source JSON').input_value());assert value['taxonomy']=={'subject':'norsk'};value['taxonomy']={'subject':'cloud'};field('Resource source JSON',json.dumps(value));click('Apply validated JSON');click('Visual');expect(p.get_by_label('Classification subject',exact=True)).to_have_value('cloud');p.get_by_label('Classification subject',exact=True).select_option('norsk');click('Save classification');assert state()['overlays']['references'][0]==pin;record()
  phase='readable exact context on and off'
  search('Coherent article');click('Quick Capture');click('Note');field('Capture text 1','Attached readable context');p.get_by_role('checkbox',name='Attach current reading context',exact=True).check();p.set_viewport_size({'width':390,'height':844});row=p.locator('.capture-row').first;box=row.locator('.inline-check').bounding_box();remove=row.get_by_role('button').bounding_box();assert box['x']+box['width']<=remove['x'];assert row.locator('input[type=checkbox]').bounding_box()['width']<30;p.screenshot(path=str(OUT/'capture-narrow.png'));p.set_viewport_size({'width':1440,'height':1000});expect(p.locator('.capture-context')).to_contain_text('Norsk');expect(p.locator('.capture-context')).to_contain_text('Coherent article');assert aid not in p.locator('.capture-context').inner_text();p.screenshot(path=str(OUT/'capture-desktop.png'));click('Save captures')
  click('Quick Capture');click('Note');field('Capture text 1','Global capture');expect(p.locator('.capture-context')).to_contain_text('not attached');click('Save captures');v=state();assert 'contextTarget' not in next(i for i in v['personal']['dashboardItems'] if i['text']=='Global capture');assert next(i for i in v['personal']['dashboardItems'] if i['text']=='Attached readable context')['contextTarget']['articleId']==aid;record()
  phase='capture Article round-trip respects context off'
  click('Quick Capture');p.get_by_role('checkbox',name='Attach current reading context',exact=True).check();click('Article');field('Title','Unlinked returned draft');field('Pasted article or transcript','Preserved unsaved body');click('Back to Quick Capture');p.get_by_role('checkbox',name='Attach current reading context',exact=True).uncheck();click('Article');expect(p.get_by_label('Title',exact=True)).to_have_value('Unlinked returned draft');click('Import local content');expect(p.locator('dialog[open]')).to_have_count(0);returned=next(v['page']['article'] for v in state()['overlays']['pages'].values() if v['page'].get('title')=='Unlinked returned draft');assert 'contextTarget' not in returned;record()
  phase='exact PDF capture and keyboard pane resize'
  search('PDF reading fixture');show_reader_controls(p);expect(p.locator('.active-pane [data-page-rendered=true] canvas').first).to_be_visible(timeout=20000);p.get_by_role('spinbutton',name='Physical PDF page number',exact=True).fill('3');p.get_by_role('spinbutton',name='Physical PDF page number',exact=True).press('Enter');expect(p.locator('.active-pane .physical-page[data-physical-page="3"] canvas')).to_be_visible(timeout=20000)
  click('Quick Capture');click('Note');field('Capture text 1','Exact PDF capture');p.get_by_role('checkbox',name='Attach current reading context',exact=True).check();expect(p.locator('.capture-context')).to_contain_text('Physical p.3');click('Save captures');pdfcapture=next(i for i in state()['personal']['dashboardItems'] if i['text']=='Exact PDF capture');assert pdfcapture['contextTarget']['pdfPage']==3
  click('Compare in two panes');divider=p.get_by_role('separator',name='Resize comparison panes');assert divider.bounding_box()['width']>=12;before=state()['personal']['session'];divider.press('ArrowLeft');after=state()['personal']['session'];assert after['ratio']<before['ratio'];assert after['panes']==before['panes'];divider.press('Home');assert state()['personal']['session']['ratio']==50;click('Compare in two panes');record()
  phase='reload and full backup fresh-profile restore'
  expected=state();p.reload(wait_until='networkidle');assert state()['overlays']==expected['overlays'];open_settings(p)
  with p.expect_download() as dl:click('Download workspace backup')
  backup=OUT/'polish.atlas-backup.zip';dl.value.save_as(str(backup));expected=state();ctx.close();ctx=browser.new_context(viewport={'width':390,'height':844},accept_downloads=True);p=ctx.new_page();p.set_default_timeout(12000);p.on('pageerror',lambda e:errors.append(str(e)));p.goto(base,wait_until='networkidle');open_settings(p);p.get_by_label('Restore workspace backup',exact=True).set_input_files(str(backup));p.get_by_role('checkbox',name='I understand that this replaces the current local workspace.',exact=True).check();click('Restore verified backup');expect(p.locator('dialog[open]')).to_have_count(0);p.reload(wait_until='networkidle');actual=state();(OUT/'restore-actual.json').write_text(json.dumps(actual,indent=2));(OUT/'restore-expected.json').write_text(json.dumps(expected,indent=2));assert actual['overlays']==expected['overlays'];assert_personal_after_open(actual['personal'],expected['personal']);p.screenshot(path=str(OUT/'restored-narrow.png'));record()
  phase='restored capture navigation and visible answer labels'
  click('Open Dashboard');click('Source for Attached readable context');expect(p.locator('.active-pane')).to_contain_text('A stable article body.');search('Visual regression QCM');expect(p.locator('.qcm-reader')).to_be_visible();assert p.locator('.qcm-options strong').all_text_contents()==['A.','B.'];assert not errors,errors;record();browser.close()
except Exception as e:
 results.append({'name':phase,'status':'FAIL','error':str(e)});traceback.print_exc()
report={'scope':__doc__,'checks':results,'errors':errors};(OUT/'results.json').write_text(json.dumps(report,indent=2));raise SystemExit(1 if errors or any(r['status']!='PASS' for r in results) else 0)
