import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {readWorkspace,loadSchemas,planImport} from '../src/core/packs.mjs';
import {sha256,stable} from '../src/core/validation.mjs';
import {unzipBounded,zipFiles,makeBackup,readBackup} from '../src/storage/archives.mjs';
import {blankWorkspace,newView,navigate,current,travel,compose,toggleCompare,locations,applyOperation,makeMarkdownPage,searchCatalog} from '../dist/app/core/workspace.js';
import {stepPhysicalPage,spreadPages} from '../src/pdf/physical-pages.mjs';
const schemas=await loadSchemas(n=>fs.readFile('src/content/schemas/'+n,'utf8'));
const fixtures=await Promise.all(['1.0.0','1.1.0'].map(async v=>readWorkspace((await unzipBounded(new Uint8Array(await fs.readFile('tests/fixtures/atlas-audit-stress-library-'+v+'.zip')))).files,schemas)));
const [v1,v2]=fixtures,blankBuilt={packs:[],assets:[],groups:[],releaseId:'synthetic-release'};
async function hash(pack){pack.hash=await sha256(stable({manifest:pack.manifest,projects:pack.projects,pages:pack.pages,glossary:pack.glossary,documents:pack.documents}));return pack;}
function withReadingState(){const ws=blankWorkspace();ws.imports=structuredClone(v1.packs);ws.assets=structuredClone(v1.assets);const long=ws.imports[0].pages.find(p=>p.id==='audit.page.long');
 const anchor={blockId:long.blocks.at(-1).id,offset:0};
 ws.personal.notes[long.id]={pageId:long.id,text:'Keep this personal remark exactly. Norsk: en merknad.',updatedAt:1700000000000};ws.personal.ratings[long.id]='orange';
 ws.personal.bookmarks=[{id:'bookmark.synthetic',pageId:long.id,title:'Deep saved place',anchor,createdAt:1700000000000}];
 const view=newView(long.id,anchor);current(view).presentation='book';view.english=false;view.collapsed[long.blocks[0].id]=false;ws.personal.session.panes[0].views=[view];ws.personal.session.panes[0].active=view.id;ws.personal.session.screen='reader';
 const page=makeMarkdownPage('My local addition','Local content that must survive imported revisions.');const project={id:'local.audit.notebook',title:'Local audit notebook',description:'User created',icon:'book',nodes:[{id:'local.audit.node',pageId:page.id,title:page.title}]};ws.overlays.projects.push(project);ws.overlays.pages[page.id]={page};ws.overlays.archived.push('audit.node.short');ws.overlays.groups=[{id:'group.local.audit',title:'My own group',projectIds:[project.id]}];
 return ws;
}

test('supplied v1 and v2 fixtures parse through the actual ZIP and schema validators',()=>{assert.equal(v1.validation.pages,5);assert.equal(v2.validation.pages,6);assert.equal(v1.validation.projects,2);assert.equal(v1.packs[0].manifest.id,v2.packs[0].manifest.id);});
test('supplied synthetic update preserves additions, remarks, flags, bookmarks, views and archive/group state exactly',()=>{
 const ws=withReadingState(),before=structuredClone(ws),plan=planImport(ws.imports,v2.packs,ws.overlays);assert.deepEqual(plan.conflicts,[]);assert(plan.moves.some(m=>m.id==='audit.page.long'));assert(plan.addedPages.includes('audit.page.new-in-1-1'));
 ws.imports=plan.candidate;const catalogue=compose(blankBuilt,ws);assert.equal(catalogue.pages.find(p=>p.id==='audit.page.long').summary,v2.packs[0].pages.find(p=>p.id==='audit.page.long').summary);
 assert.notEqual(catalogue.pages.find(p=>p.id==='audit.page.long').summary,before.imports[0].pages.find(p=>p.id==='audit.page.long').summary);
 assert.deepEqual(ws.personal,before.personal);assert.deepEqual(ws.overlays,before.overlays);assert(catalogue.pages.some(p=>p.title==='My local addition'));
 assert.notDeepEqual(locations(catalogue).get('audit.page.long').ancestors,locations(compose(blankBuilt,before)).get('audit.page.long').ancestors);
});
test('synthetic v1.1 reimport is idempotent without duplicate pages',()=>{const ws=withReadingState();ws.imports=v2.packs;const p=planImport(ws.imports,v2.packs,ws.overlays);assert.deepEqual(p.conflicts,[]);assert.equal(p.unchanged.length,1);assert.equal(p.addedPages.length,0);assert.equal(new Set(p.candidate.flatMap(p=>p.pages.map(p=>p.id))).size,6);});
test('same-version modified synthetic content is blocked without mutating the workspace',async()=>{const ws=withReadingState();ws.imports=structuredClone(v2.packs);const before=structuredClone(ws),p=structuredClone(v2.packs[0]);p.pages[0].summary+=' altered';await hash(p);assert.match(planImport(ws.imports,[p],ws.overlays).conflicts.join(' '),/same version, different bytes/);assert.deepEqual(ws,before);});
test('older synthetic pack is blocked',()=>assert.match(planImport(v2.packs,v1.packs,blankWorkspace().overlays).conflicts.join(' '),/older revision/));
test('omitted stable synthetic page IDs are never deletion instructions',async()=>{const pack=structuredClone(v2.packs[0]);pack.manifest.version='1.2.0';pack.pages=pack.pages.filter(p=>p.id!=='audit.page.short');await hash(pack);assert.match(planImport(v2.packs,[pack],blankWorkspace().overlays).conflicts.join(' '),/missing page IDs/);});
test('synthetic source edit collision requires explicit rebase',()=>{const ws=withReadingState(),p=structuredClone(v1.packs[0].pages.find(p=>p.id==='audit.page.long'));p.summary='A local source edit';ws.overlays.pages[p.id]={page:p,baseHash:v1.packs[0].hash};assert.match(planImport(v1.packs,v2.packs,ws.overlays).conflicts.join(' '),/Local edit rebase required/);});
test('complete synthetic backup restore round-trip is exact including a local PDF',async()=>{
 const ws=withReadingState();ws.imports=structuredClone(v2.packs);const bytes=new Uint8Array(await fs.readFile('content/packs/atlas.reader-guide/assets/atlas-reader-fixture.pdf')),digest=await sha256(bytes),key='local.pdf/'+digest+'.pdf';
 ws.assets.push({key,bytes,sha256:digest,mediaType:'application/pdf'});const page=makeMarkdownPage('Retained local PDF','PDF reference');ws.overlays.pages[page.id]={page};ws.overlays.documents.push({id:'doc.local.audit',pageId:page.id,title:page.title,source:{kind:'library-file',libraryId:'local.browser',path:'pdf/'+digest+'.pdf'},assetKey:key,sha256:digest,bytes:bytes.length,visibility:'private',rights:{status:'unreviewed',attribution:'Synthetic user import'}});
 const result=await makeBackup(ws,blankBuilt,async()=>undefined),unpacked=await unzipBounded(result.bytes),restored=(await readBackup(unpacked.files,schemas)).workspace;
 assert.deepEqual(restored.personal,ws.personal);assert.deepEqual(restored.overlays,ws.overlays);assert.deepEqual(restored.imports,ws.imports);assert.deepEqual(restored.assets[0].bytes,bytes);
 await fs.mkdir('docs/evidence/hardening',{recursive:true});await fs.writeFile('docs/evidence/hardening/synthetic-roundtrip.json',JSON.stringify({scope:'Real ZIP serialization/parser, not browser persistence',status:'PASS',original:bytes.length,restored:restored.assets[0].bytes.length,sha256:digest,packVersion:restored.imports[0].manifest.version,personalExact:true,overlaysExact:true,importsExact:true},null,2));
});
test('backup fails BEFORE download when imported-pack assets are absent',async()=>{const ws=withReadingState();ws.imports[0].assetKeys=['missing.imported.pdf'];await assert.rejects(makeBackup(ws,blankBuilt,async()=>undefined),/dependency unavailable/);});
test('backup fails BEFORE download when a local PDF is missing',async()=>{const ws=withReadingState();ws.overlays.documents.push({id:'doc.missing',assetKey:'missing.local.pdf'});await assert.rejects(makeBackup(ws,blankBuilt,async()=>undefined),/dependency unavailable/);});
test('backup rejects changed bytes under an unchanged attachment hash',async()=>{const ws=withReadingState();ws.imports[0].assetKeys=['corrupt.pdf'];ws.assets.push({key:'corrupt.pdf',bytes:new Uint8Array([1]),sha256:'0'.repeat(64),mediaType:'application/pdf'});await assert.rejects(makeBackup(ws,blankBuilt,async()=>undefined),/corrupt attachment/);});
for(const activeIndex of [0,1])test('Compare top-bar close preserves pane '+activeIndex+' losslessly',()=>{const ws=withReadingState(),s=ws.personal.session;toggleCompare(s);for(let i=0;i<4;i++)s.panes[activeIndex].views.push(newView('audit.page.short'));s.activePane=s.panes[activeIndex].id;s.panes[activeIndex].active=s.panes[activeIndex].views[3].id;s.ratio=65;const before=structuredClone(s.panes[activeIndex]);toggleCompare(s);assert.equal(s.panes.length,1);assert.deepEqual(s.panes[0],before);assert.equal(s.activePane,before.id);assert.equal(s.ratio,50);});
test('Compare copies independent deep state when opening',()=>{const ws=withReadingState(),s=ws.personal.session;toggleCompare(s);const left=s.panes[0].views[0],right=s.panes[1].views[0];assert.notEqual(left.id,right.id);assert.notEqual(left.history,right.history);assert.deepEqual(left.history,right.history);current(right).anchor.offset=77;right.english=true;right.collapsed.extra=true;assert.notEqual(current(left).anchor.offset,77);assert.equal(left.english,false);assert.equal(left.collapsed.extra,undefined);});
test('Compare can close even when its active pane is empty',()=>{const s=withReadingState().personal.session;toggleCompare(s);const right=s.panes[1];right.views=[];right.active='';s.activePane=right.id;assert(toggleCompare(s));assert.equal(s.panes[0].id,right.id);assert.equal(s.screen,'home');});
test('five tabs have independent mode, translation, source anchor and history',()=>{const views=Array.from({length:5},(_,i)=>{let v=newView('audit.page.short');v=navigate(v,'audit.page.long',{blockId:'audit.block.'+i,offset:i});current(v).presentation=['continuous','book','parallel'][i%3];v.english=i%2===0;return v;});const before=structuredClone(views);views[1]=travel(views[1],-1);assert.equal(current(views[1]).pageId,'audit.page.short');assert.deepEqual(views.filter((_,i)=>i!==1),before.filter((_,i)=>i!==1));views[1]=travel(views[1],1);assert.deepEqual(views,before);});
test('six nested folders plus a local root/deep page survive rename and cross-notebook move',()=>{const ws=withReadingState(),projects=structuredClone(v1.packs[0].projects);let parent;for(let depth=1;depth<=6;depth++){const id='local.depth.'+depth;applyOperation(projects,{kind:'add',nodeId:id,projectId:projects[0].id,parentId:parent,node:{id,title:'Local '+depth,children:[]}});parent=id;}applyOperation(projects,{kind:'add',nodeId:'local.deep.node',projectId:projects[0].id,parentId:parent,node:{id:'local.deep.node',title:'Deep page',pageId:'local.deep.page'}});applyOperation(projects,{kind:'rename',nodeId:'local.deep.node',title:'Renamed deep page'});let c={projects};assert.equal(locations(c).get('local.deep.page').ancestors.length,7);applyOperation(projects,{kind:'move',nodeId:'local.deep.node',projectId:projects[1].id});assert.equal(locations(c).get('local.deep.page').project.id,projects[1].id);assert.equal(locations(c).get('local.deep.page').path.at(-1),'Renamed deep page');});
for(const [name,query] of [['title','pagination stress'],['body','UniqueSearchToken_ATLAS_9472'],['code','row_04'],['tags','search-tag-unique-813'],['folder','Level 5'],['English','English example sentence'],['Norwegian','norsk eksempelsetning']])test('synthetic search: '+name,()=>{const c=compose(blankBuilt,withReadingState());const hits=searchCatalog(c,query);assert(hits.pages.length+hits.terms.length>0,query);});
for(const total of [1,2,3,4,5,10])for(const cover of [false,true])test('physical spread navigation covers every page once: '+total+' cover='+cover,()=>{let page=1,seen=[],guard=0;while(guard++<=total){const spread=spreadPages(page,total,cover);seen.push(...spread);if(spread.at(-1)===total)break;page=stepPhysicalPage(page,total,1,true,cover);}assert.deepEqual(seen,Array.from({length:total},(_,i)=>i+1));if(page>1){const before=stepPhysicalPage(page,total,-1,true,cover);assert(before<page);}});

for(const query of ['Glossary-only audit term','GlossaryDefinitionOnlyToken_7319','Parallellspr\u00e5k'])test('synthetic glossary label/definition/translation: '+query,()=>{assert(searchCatalog(compose(blankBuilt,withReadingState()),query).terms.length>0);});

test('backup also rejects corrupt orphan attachments retained in the workspace',async()=>{const ws=withReadingState();ws.assets.push({key:'orphan.pdf',bytes:new Uint8Array([1,2,3]),sha256:'0'.repeat(64),mediaType:'application/pdf'});await assert.rejects(makeBackup(ws,blankBuilt,async()=>undefined),/corrupt attachment/);});
