import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
import {built,setup,authoredFixtures,basePage,assetResolver,plan,edit,personal} from './v22/fixtures.mjs';
import {captureResources,resourceAdapters,historicalCatalogue,historicalWorkspace,pdfProvenance} from '../dist-offline/app/history/adapters.js';
import {advanceHistory,prepareWorkspaceHistory,assertProjection} from '../dist-offline/app/history/engine.js';
import {emptyHistory} from '../dist-offline/app/history/model.js';
import {validateHistory,validateResourceSnapshot,HISTORY_LIMITS} from '../dist-offline/app/history/validation.mjs';
import {semanticDiff} from '../dist-offline/app/history/diff.js';
import {compose,current} from '../dist-offline/app/core/workspace.js';
import {activeSession} from '../dist-offline/app/core/workspace-slots.js';
import {openReadingTarget} from '../dist-offline/app/core/reading-navigation.js';
import {resolveTarget} from '../dist-offline/app/references/targets.js';
import {resolveStudy} from '../dist-offline/app/companion/tree.js';
import {saveReadingState,restoreReadingState} from '../dist-offline/app/core/saved-states.js';
import {makeBackup,readBackup,unzipBounded,zipFiles} from '../src/storage/archives.mjs';
import {loadSchemas} from '../src/core/packs.mjs';
import {sha256,stable} from '../src/core/validation.mjs';
import {writeHistoryFiles,readHistoryFiles} from '../src/history/backup.mjs';
const schemas=await loadSchemas(n=>fs.readFile('src/content/schemas/'+n,'utf8'));
const clone=structuredClone;
const keys={'notebook-page':'notebook-page:page.atlas.welcome','notebook-tree':'notebook-tree:project.atlas.guide',article:'article:page.v22.article',qcm:'qcm:page.v22.qcm',cheatsheet:'cheatsheet:page.cheatsheet.azure-data-factory',pdf:'pdf:doc.atlas.pdf'};
function modify(s,type){if(type==='notebook-tree')s.project.title+=' revised';else if(type==='qcm')s.page.qcm.questions[0].prompt+=' Revised?';else if(type==='cheatsheet')s.page.cheatsheet.pages[0].blocks[0].text+=' revised';else if(type==='pdf'){s.document.title+=' revised';s.page.title=s.document.title;}else s.page.blocks.push({id:s.page.id+'.new',type:'markdown',text:'New bounded explanation.'});}
test('V22 baseline covers six adapters, preserves existing state and is idempotent',async()=>{const source=authoredFixtures(),snapshot=stable(source),ws=await prepareWorkspaceHistory(built,source,{source:'migration'});assert.equal(stable(source),snapshot);assert.equal(ws.history.revisions.length,captureResources(compose(built,source),source).length);assert.deepEqual(new Set(ws.history.revisions.map(r=>r.resourceType)),new Set(Object.keys(keys)));const again=await prepareWorkspaceHistory(built,ws,{source:'migration'});assert.deepEqual(again.history,ws.history);assert.equal(again.personal,source.personal);assert.equal(again.assets,source.assets);await validateHistory(again.history);});
test('V22 baseline interrupted after a batch resumes with no duplicates',async()=>{const ws=authoredFixtures(),resources=captureResources(compose(built,ws),ws);const partial=await advanceHistory(emptyHistory(),resources.slice(0,17),{source:'migration'});assert.equal(partial.meta.initialized,false);const resumed=await advanceHistory(partial,resources,{source:'migration'},true);assert.equal(resumed.revisions.length,resources.length);assert.equal(new Set(resumed.heads.map(h=>h.resourceKey)).size,resources.length);assert(resumed.revisions.every(r=>r.number===1&&r.parentRevisionId===null));});
for(const [type,key]of Object.entries(keys)){
 test('V22 '+type+' manual revision, no-op, current/pinned read and restore-as-new',async()=>{const {api,backend}=await setup();const initial=api.getResource(key),old=backend.state.history.revisions.find(r=>r.revisionId===initial.head.revisionId),oldJson=stable(old);await backend.manual(ws=>{const s=clone(initial.snapshot);modify(s,type);resourceAdapters[type].project(ws.overlays,compose(built,ws),s);});assert.equal(api.getResource(key).head.number,2);assert.equal(stable(old),oldJson);assert.deepEqual(api.getResource(key,old.revisionId).snapshot,initial.snapshot);await backend.manual(()=>{});assert.equal(api.getResource(key).head.number,2);const ws=backend.state,c=compose(built,ws),p=clone(ws.personal);const oldTarget=api.getResource(key,old.revisionId).target;openReadingTarget(p,c,ws.overlays,oldTarget,'here',ws);assert.equal(current(activeSession(p).panes[0].views[0]).historyRevisionId,old.revisionId);assert.equal(resolveTarget(c,ws,oldTarget).exact,true);await backend.reviewedMutation(next=>resourceAdapters[type].project(next.overlays,compose(built,next),old.snapshot),{source:'restore',summary:'Restore old',forceResourceKey:key,restoredFromRevisionId:old.revisionId});assert.equal(api.getResource(key).head.number,3);assert.deepEqual(api.getResource(key).snapshot,old.snapshot);assert.equal(backend.state.history.revisions.at(-1).restoredFromRevisionId,old.revisionId);await assertProjection(compose(built,backend.state),backend.state);});
}
test('V22 missing and mismatched historical target fail closed',async()=>{const {api,backend}=await setup(),r=api.getResource(keys.article),t={...r.target,historyRevisionId:'revision.missing'};assert.equal(api.resolveTarget(t).available,false);await assert.rejects(api.navigateAgentTarget(t),/missing/);const other=api.getResource(keys.qcm).head.revisionId;assert.equal(api.resolveTarget({...r.target,historyRevisionId:other}).available,false);assert.throws(()=>api.getResource(keys.article,other),/another resource/);});
test('V22 version-aware A/B locations and workspace checkpoint preserve heads',async()=>{const {api,backend}=await setup(),key=keys['notebook-page'],v1=api.getResource(key).head.revisionId;const e=plan([edit(api,key,s=>modify(s,'notebook-page'))]);await api.stage(e);await api.accept(e.id);await api.compareRevisions(key,v1);const s=activeSession(backend.state.personal);assert.equal(s.revisionCompareMode,'changes');assert.equal(s.panes.length,2);assert.equal(current(s.panes[0].views.find(v=>v.id===s.panes[0].active)).historyRevisionId,v1);assert.equal(current(s.panes[1].views.find(v=>v.id===s.panes[1].active)).historyRevisionId,undefined);const before=stable(backend.state.history);saveReadingState(backend.state.personal,1,'Pinned state');const id=backend.state.personal.savedStates.entries.at(-1).id;await api.setAgentCompareState({enabled:true,mode:'a',pane:'A'});restoreReadingState(backend.state.personal,id);assert.equal(stable(backend.state.history),before);});
test('V22 semantic Notebook block add/remove/edit and tree move/reorder/rename',()=>{const a={page:basePage('page.diff','Original')},b=clone(a);b.page.title='New title';b.page.blocks[0].text='Changed explanation.';b.page.blocks.push({id:'block.add',type:'markdown',text:'Added'});let d=semanticDiff('notebook-page',a,b);assert(d.some(e=>e.kind==='add'));assert(d.some(e=>e.kind==='rename'));assert(d.some(e=>e.words?.some(w=>w.kind==='remove')));assert(semanticDiff('notebook-page',b,a).some(e=>e.kind==='remove'));const ta={project:{id:'p',title:'P',icon:'book',description:'',nodes:[{id:'n1',title:'N1',children:[{id:'n2',title:'N2'}]},{id:'n3',title:'N3'}]}};const tb=clone(ta);tb.project.nodes[0].children=[];tb.project.nodes[1].children=[{id:'n2',title:'Renamed'}];tb.project.nodes.reverse();d=semanticDiff('notebook-tree',ta,tb);for(const kind of ['move','rename','reorder'])assert(d.some(e=>e.kind===kind));});
test('V22 semantic Article/Cheatsheet/QCM diffs retain typed paths and stable IDs',async()=>{const {api}=await setup();for(const type of ['article','cheatsheet','qcm']){const a=api.getResource(keys[type]).snapshot,b=clone(a);modify(b,type);const d=semanticDiff(type,a,b);assert(d.length);assert(d.some(e=>e.entityId));assert(!d.some(e=>/svg/.test(e.path)));}});
test('V22 PDF outline, byte provenance and metadata revision are separate',async()=>{const {api,backend}=await setup(),key=keys.pdf,old=api.getResource(key),snapshot=clone(old.snapshot);snapshot.companion.categories[0].title+=' edited';await backend.manual(ws=>resourceAdapters.pdf.project(ws.overlays,compose(built,ws),snapshot));const next=api.getResource(key);assert.notEqual(next.snapshot.pdfProvenance.metadataRevision,old.snapshot.pdfProvenance.metadataRevision);assert.equal(next.snapshot.document.sha256,old.snapshot.document.sha256);assert(semanticDiff('pdf',old.snapshot,next.snapshot).some(d=>d.path.includes('companion.categories')));const historicalWs=historicalWorkspace(backend.state,old.head.revisionId);assert.deepEqual(resolveStudy(old.snapshot.document,historicalWs).companion,old.snapshot.companion);const external=api.listResources({type:'pdf',limit:100}).items.find(r=>r.resourceId.startsWith('doc.pdfatlas.'));const d=api.getResource(external.resourceKey).snapshot.document;const p=pdfProvenance(d);assert.equal(p.commit,'fa5e83f7825cdc837078f87c5e130cb012332195');assert.notEqual(p.commit,p.sha256);const bad=clone(d);bad.source.url=bad.source.url.replace(p.commit,'main');assert.throws(()=>pdfProvenance(bad),/immutable/);});
test('V22 backup schema 4 shards round trip content, heads and review history',async()=>{const {api,backend}=await setup();const cs=plan([edit(api,keys.article,s=>modify(s,'article'))]);await api.stage(cs);await api.accept(cs.id);const backup=await makeBackup(backend.state,built,assetResolver);assert.equal(backup.snapshot.schemaVersion,4);const files=(await unzipBounded(backup.bytes)).files;assert([...files.keys()].some(x=>x.endsWith('history/index.json')));const restored=(await readBackup(files,schemas)).workspace;assert.deepEqual(restored.history,backend.state.history);await assertProjection(compose(built,restored),restored);assert.equal(restored.history.reviews.at(-1).status,'accepted');});
for(const version of [2,3])test('V22 legacy backup schema '+version+' initializes only valid baseline revisions',async()=>{const ws=authoredFixtures();if(version===3){const {backend}=await setup();ws.personal=backend.state.personal;}const b=await makeBackup(ws,built,assetResolver);const files=(await unzipBounded(b.bytes)).files,key=[...files.keys()].find(x=>x.endsWith('backup.json')),json=JSON.parse(new TextDecoder().decode(files.get(key)));json.schemaVersion=version;files.set(key,new TextEncoder().encode(JSON.stringify(json)));const legacy=(await readBackup(files,schemas)).workspace;assert.equal(legacy.history,undefined);const next=await prepareWorkspaceHistory(built,legacy,{source:'migration'});assert(next.history.revisions.every(r=>r.number===1&&r.source==='migration'));await assertProjection(compose(built,next),next);});
for(const [label,corrupt]of [
 ['hash',h=>{h.revisions[0].snapshot.page.title='tampered';}],
 ['duplicate revision',h=>h.revisions.push(clone(h.revisions[0]))],
 ['parent',h=>{h.revisions[0].parentRevisionId='revision.missing';}],
 ['head',h=>{h.heads[0].number=9;}],
 ['provenance',h=>{const r=h.revisions.find(r=>r.resourceType==='pdf');r.snapshot.pdfProvenance.sha256='0'.repeat(64);}],
])test('V22 history corruption rejected: '+label,async()=>{const {backend}=await setup(),h=clone(backend.state.history);corrupt(h);await assert.rejects(validateHistory(h));});
test('V22 current source/head mismatch rejected before restore',async()=>{const {backend}=await setup(),ws=clone(backend.state);ws.overlays.pages['page.v22.article'].page.title='Uncommitted tamper';await assert.rejects(assertProjection(compose(built,ws),ws),/head mismatch/);});
test('V22 missing historical local PDF byte asset rejects restore',async()=>{const {backend}=await setup();await assert.rejects(validateHistory(backend.state.history,[],true),/historical PDF asset/);});
test('V22 historic PDF asset not current remains included in full backup',async()=>{const {backend}=await setup(),old=backend.state.history.revisions.find(r=>r.resourceId==='doc.atlas.pdf');const a=await assetResolver(old.snapshot.document.assetKey);backend.state.assets.push(a);await backend.manual(ws=>{const d=clone(old.snapshot);d.document.source={kind:'https',url:'https://example.org/reviewed.pdf'};delete d.document.assetKey;d.document.packId='review.fixture';d.companion=null;d.pdfProvenance=pdfProvenance(d.document);resourceAdapters.pdf.project(ws.overlays,compose(built,ws),d);});const backup=await makeBackup(backend.state,built,assetResolver),restored=(await readBackup((await unzipBounded(backup.bytes)).files,schemas)).workspace;assert(restored.assets.some(x=>x.key===a.key));assert(restored.history.revisions.some(r=>r.snapshot.document?.assetKey===a.key));});
test('V22 history shard index hash and duplicate paths fail closed',async()=>{const {backend}=await setup(),files=new Map(),pointer=await writeHistoryFiles(files,backend.state.history);const converted=new Map([...files].map(([k,v])=>[k,new TextEncoder().encode(v)]));const raw=JSON.parse(files.get(pointer.indexPath));raw.hash='0'.repeat(64);converted.set(pointer.indexPath,new TextEncoder().encode(JSON.stringify(raw)));await assert.rejects(readHistoryFiles(converted,'',pointer,[]),/hash mismatch/);raw.revisionShards.push(raw.revisionShards[0]);converted.set(pointer.indexPath,new TextEncoder().encode(JSON.stringify(raw)));await assert.rejects(readHistoryFiles(converted,'',pointer,[]),/duplicate/);});
test('V22 explicit limits block instead of pruning',async()=>{const {backend}=await setup();const h=clone(backend.state.history);h.heads[0].number=HISTORY_LIMITS.perResource;const resources=captureResources(compose(built,backend.state),backend.state);resources.find(r=>r.resourceKey===h.heads[0].resourceKey).snapshot.page.title+=' changed';await assert.rejects(advanceHistory(h,resources,{source:'manual'}),/history is full/);assert.equal(h.revisions.length,backend.state.history.revisions.length);});

test('V22 emergency backup appends only to its detached copy and remains restore-coherent',async()=>{
 const {backend}=await setup(),live=backend.state,initialHistory=stable(live.history);const snapshot=clone(live);snapshot.overlays.pages['page.v22.article'].page.blocks[0].text+=' Unsaved edit after browser failure';
 const {prepareEmergencySnapshot}=await import('../dist-offline/app/history/engine.js');const recovery=await prepareEmergencySnapshot(built,snapshot);
 assert.equal(stable(snapshot.history),initialHistory);assert.equal(recovery.history.revisions.length,live.history.revisions.length+1);assert.equal(recovery.history.revisions.at(-1).source,'manual');await assertProjection(compose(built,recovery),recovery);
 const backup=await makeBackup(recovery,built,assetResolver),restored=(await readBackup((await unzipBounded(backup.bytes)).files,schemas)).workspace;await assertProjection(compose(built,restored),restored);
});
