import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {blankWorkspace,newView,navigate,current,travel,compose,toggleCompare,locations,applyOperation,makeMarkdownPage,searchCatalog} from '../dist/app/core/workspace.js';
import {collectionTarget,collectionItems,filterCollection} from '../dist/app/core/collections.js';
import {prepareLocalPdf,emptyPdfMetadata,duplicatePdfImports,PDF_MAX_BYTES,PDF_TARGET_BYTES} from '../dist/app/core/pdf-library.js';
import {exportPrivatePdfLibrary} from '../src/core/export-pdf-library.mjs';
import {validateState} from '../src/storage/state-validation.mjs';
import {loadSchemas,readWorkspace,planImport} from '../src/core/packs.mjs';
import {sha256} from '../src/core/validation.mjs';
import {unzipBounded,makeBackup,readBackup,zipFiles} from '../src/storage/archives.mjs';
const schemas=await loadSchemas(n=>fs.readFile('src/content/schemas/'+n,'utf8'));
const built=JSON.parse(await fs.readFile('dist/content.json','utf8'));
const bytes=new Uint8Array(await fs.readFile('content/packs/atlas.reader-guide/assets/atlas-reader-fixture.pdf'));
// A second, still-valid synthetic revision; the SHA is deliberately different.
const privateBytes=new Uint8Array([...bytes,...new TextEncoder().encode('\n% atlasnote-1.1-local-fixture\n')]);
const metadata=()=>({...emptyPdfMetadata(),title:'Private synthetic architecture PDF',summary:'Offline test reference',language:'fr',documentType:'cheatsheet',domains:'Data Engineering, Cloud Architecture',technologies:'Spark, Databricks',source:'linkedin',pageCount:'3'});
function workspace(){const ws=blankWorkspace();ws.overlays.projects.push({id:'project.local.11',title:'Study library',icon:'book',description:'Synthetic only',nodes:[{id:'folder.local.root',title:'Reference',children:[]}]});return ws;}
async function local(ws=workspace(),projectId='project.local.11',parent='folder.local.root'){
 const result=await prepareLocalPdf(compose(built,ws),ws,privateBytes,metadata(),projectId,parent,'Deep folder');
 assert(!result.duplicate);ws.overlays=result.overlays;ws.assets.push(result.asset);return {ws,...result,c:compose(built,ws)};
}
const all={type:'all',language:'',domain:'',technology:'',text:'',sort:'tree'};

test('1.1 empty picker navigation produces cursor zero and a valid portable session',()=>{const ws=workspace(),pane=ws.personal.session.panes[0];let v=newView();assert.deepEqual(v.history,[]);v=navigate(v,'page.atlas.welcome');assert.equal(v.cursor,0);v=navigate(v,'page.atlas.layouts');assert.equal(v.cursor,1);assert.equal(current(travel(v,-1)).pageId,'page.atlas.welcome');pane.views=[v,newView()];pane.active=v.id;assert(validateState(ws,schemas));});
test('1.1 folder routes retain real tree IDs without inventing content pages',()=>{const ws=workspace(),c=compose(built,ws),v=newView('folder.local.root');current(v).collectionId='folder.local.root';ws.personal.session.panes[0].views=[v];ws.personal.session.panes[0].active=v.id;assert(validateState(ws,schemas));assert.equal(collectionTarget(c,'folder.local.root').title,'Reference');assert(!c.pages.some(p=>p.id==='folder.local.root'));current(v).collectionId='other';assert.throws(()=>validateState(ws,schemas),/collection navigation identity/);});
test('1.1 Compare preserves source pane byte-for-byte, opens empty active picker, retains 66% ratio',()=>{const s=workspace().personal.session,v=newView('page.atlas.layouts');v.english=false;current(v).presentation='book';current(v).anchor={blockId:'block.atlas.layouts.1',unit:'u.1',offset:42,viewportOffset:18.5};s.panes[0].views=[v];s.panes[0].active=v.id;s.ratio=66;const before=structuredClone(s.panes[0]);toggleCompare(s);assert.deepEqual(s.panes[0],before);assert.equal(s.activePane,s.panes[1].id);assert.deepEqual(s.panes[1].views,[]);toggleCompare(s);assert.deepEqual(s.panes[0],before);assert.equal(s.ratio,66);toggleCompare(s);assert.equal(s.ratio,66);});
test('1.1 two intentional copies retain different PDF modes, physical anchors, English and history',()=>{const s=workspace().personal.session;s.panes[0].views=[newView('page.atlas.pdf')];s.panes[0].active=s.panes[0].views[0].id;toggleCompare(s);const v=newView('page.atlas.pdf');s.panes[1].views=[v];s.panes[1].active=v.id;Object.assign(current(v),{pdfMode:'spread',pdfPage:3,rotation:90,zoom:1.25,anchor:{pdfPage:3,pdfRevision:'a'.repeat(64)}});v.english=false;assert.equal(current(s.panes[0].views[0]).pdfMode,'single');assert.equal(current(s.panes[0].views[0]).pdfPage,1);assert.notEqual(s.panes[0].views[0].english,v.english);const expected=structuredClone(s.panes[1]);toggleCompare(s);assert.deepEqual(s.panes[0],expected);});
test('1.1 nested local PDF intake is atomic, exact, private, conservative and facet-rich',async()=>{const original=workspace(),snapshot=structuredClone(original),r=await prepareLocalPdf(compose(built,original),original,privateBytes,metadata(),'project.local.11','folder.local.root','Deep folder');assert.deepEqual(original,snapshot);assert.deepEqual(r.asset.bytes,privateBytes);assert.equal(r.document.sha256,await sha256(privateBytes));assert.equal(r.document.visibility,'private');assert.equal(r.document.rights.status,'reference-only');assert.equal(r.document.language,'fr');assert.equal(r.document.pageCount,3);assert(r.page.tags.includes('source:linkedin'));assert(r.page.tags.includes('domain:cloud-architecture'));assert(r.page.tags.includes('tech:databricks'));});
test('1.1 local duplicate filename-independent SHA intake returns the existing record',async()=>{const r=await local(),before=structuredClone(r.ws),duplicate=await prepareLocalPdf(r.c,r.ws,privateBytes,{...metadata(),title:'Different filename'},'project.local.11');assert.equal(duplicate.duplicate.id,r.document.id);assert.deepEqual(r.ws,before);});
test('1.1 duplicate built-in SHA is also detected rather than copied into local storage',async()=>{const ws=workspace(),result=await prepareLocalPdf(compose(built,ws),ws,bytes,metadata(),'project.local.11');assert(result.duplicate);assert.equal(result.duplicate.sha256,await sha256(bytes));});
test('1.1 PDF intake rejects bad signature, excessive bytes, unknown placement and silently promoted rights',async()=>{const ws=workspace(),c=compose(built,ws);await assert.rejects(prepareLocalPdf(c,ws,new Uint8Array([1]),metadata(),'project.local.11'),/Not PDF/);const large=new Uint8Array(PDF_MAX_BYTES+1);large.set(new TextEncoder().encode('%PDF-'));await assert.rejects(prepareLocalPdf(c,ws,large,metadata(),'project.local.11'),/20 MB/);await assert.rejects(prepareLocalPdf(c,ws,privateBytes,metadata(),'no-such-project'),/existing notebook/);await assert.rejects(prepareLocalPdf(c,ws,privateBytes,{...metadata(),rights:'permission'},'project.local.11'),/never grants/);assert.equal(PDF_TARGET_BYTES,12*1024*1024);assert.equal(PDF_MAX_BYTES,20*1024*1024);});
test('1.1 invalid page count, URL and language are rejected before addition',async()=>{for(const patch of [{pageCount:'2.5'},{sourceUrl:'javascript:alert(1)'},{language:'French'}]){const ws=workspace();await assert.rejects(prepareLocalPdf(compose(built,ws),ws,privateBytes,{...metadata(),...patch},'project.local.11'));assert.equal(ws.overlays.documents.length,0);}});
test('1.1 mixed collection is direct-child projection with one canonical PDF placement',async()=>{const r=await local(),p=makeMarkdownPage('Zebra note','Modeling');p.tags=['domain:data-engineering','tech:sql','lang:en'];r.ws.overlays.pages[p.id]={page:p};r.ws.overlays.operations.push({kind:'add',nodeId:'node.test.note',projectId:'project.local.11',parentId:r.parentId,node:{id:'node.test.note',title:p.title,pageId:p.id}});const c=compose(built,r.ws),items=collectionItems(c,r.ws.overlays,r.parentId);assert.deepEqual(items.map(x=>x.type),['pdf','note']);assert.equal(collectionItems(c,r.ws.overlays,'folder.local.root').length,1);assert.equal(items[0].document.pageCount,3);assert.equal(items[0].language,'fr');assert.equal(items[0].summary,metadata().summary);assert.equal(locations(c).get(r.page.id).ancestors.at(-1),r.parentId);});
test('1.1 collection filters language/domain/technology/text/type and title sorting compose correctly',async()=>{const r=await local(),items=collectionItems(r.c,r.ws.overlays,r.parentId);for(const filter of [{type:'pdf'},{language:'fr'},{domain:'data-engineering'},{technology:'spark'},{text:'synthetic architecture'},{sort:'title'}])assert.equal(filterCollection(items,{...all,...filter}).length,1);assert.equal(filterCollection(items,{...all,type:'note'}).length,0);assert.equal(filterCollection(items,{...all,language:'no'}).length,0);assert.equal(filterCollection(items,{...all,technology:'sql'}).length,0);assert.equal(filterCollection(items,{...all,text:'not present'}).length,0);const reversed=[{...items[0],page:{...items[0].page,title:'Zebra'}},{...items[0],page:{...items[0].page,title:'Alpha'}}];assert.equal(filterCollection(reversed,all)[0].page.title,'Zebra');assert.equal(filterCollection(reversed,{...all,sort:'title'})[0].page.title,'Alpha');});
test('1.1 archived collection leaves are hidden without deleting metadata or PDF bytes',async()=>{const r=await local(),node=locations(r.c).get(r.page.id).nodeId;r.ws.overlays.archived.push(node);assert.equal(collectionItems(r.c,r.ws.overlays,r.parentId).length,0);assert.equal(r.c.documents.find(d=>d.id===r.document.id).sha256,r.document.sha256);assert.deepEqual(r.ws.assets[0].bytes,privateBytes);});
test('1.1 PDF move preserves page/document/revision and search follows title, tags and path',async()=>{const r=await local(),nodeId=locations(r.c).get(r.page.id).nodeId;r.ws.overlays.operations.push({kind:'move',nodeId,projectId:'project.local.11',parentId:'folder.local.root'});const c=compose(built,r.ws);assert.equal(locations(c).get(r.page.id).ancestors.at(-1),'folder.local.root');assert.deepEqual(c.documents.find(d=>d.id===r.document.id),r.document);for(const q of ['synthetic architecture','tech:databricks','Reference'])assert(searchCatalog(c,q).pages.some(p=>p.page.id===r.page.id||p.id===r.page.id));});
test('1.1 same SHA in incoming private libraries is blocked but identical reimport is not',async()=>{const r=await local();assert.equal(duplicatePdfImports(r.c,[{documents:[r.document]}]).length,0);assert.equal(duplicatePdfImports(r.c,[{documents:[{...r.document,id:'another.document',pageId:'another.page'}]}]).length,1);});
test('1.1 actual backup parser recovers exact private bytes, folder, theme, two panes, remarks and revision bookmark',async()=>{const r=await local(),s=r.ws.personal.session,v=newView(r.page.id);s.panes[0].views=[v];s.panes[0].active=v.id;s.theme='academic';s.ratio=62;toggleCompare(s);s.panes[1].views=[newView()];s.panes[1].active=s.panes[1].views[0].id;r.ws.personal.notes[r.page.id]={pageId:r.page.id,text:'PERSONAL_SENTINEL',updatedAt:1,anchor:{pdfPage:2,pdfRevision:r.document.sha256},revision:r.document.sha256};r.ws.personal.bookmarks.push({id:'bookmark.test.11',pageId:r.page.id,title:'Physical page 2',anchor:{pdfPage:2,pdfRevision:r.document.sha256},createdAt:1});assert(validateState(r.ws,schemas));const backup=await makeBackup(r.ws,built,async key=>{const a=built.assets.find(a=>a.key===key);return a?{...a,bytes:new Uint8Array(await fs.readFile('dist/'+a.path))}:undefined;}),restored=(await readBackup((await unzipBounded(backup.bytes)).files,schemas)).workspace;assert.deepEqual(restored.personal,r.ws.personal);assert.deepEqual(restored.overlays,r.ws.overlays);assert.deepEqual(restored.assets[0].bytes,privateBytes);});
test('1.1 private PDF export is accepted by actual readWorkspace and excludes all personal and teaching state',async()=>{const r=await local();r.ws.personal.notes[r.page.id]={pageId:r.page.id,text:'PERSONAL_SENTINEL_DO_NOT_EXPORT',updatedAt:1};r.ws.overlays.pages[r.page.id].page.blocks=[{id:'block.private.teaching',type:'markdown',text:'TEACHING_SENTINEL_DO_NOT_EXPORT'}];const c=compose(built,r.ws),out=await exportPrivatePdfLibrary(c,async key=>r.ws.assets.find(a=>a.key===key)),files=(await unzipBounded(out.bytes)).files,parsed=await readWorkspace(files,schemas);assert.equal(parsed.packs[0].manifest.visibility,'private');assert.equal(parsed.packs[0].documents[0].id,r.document.id);assert.equal(parsed.packs[0].documents[0].pageId,r.page.id);assert.deepEqual(parsed.assets[0].bytes,privateBytes);assert.deepEqual(parsed.packs[0].pages[0].blocks,[]);for(const b of files.values()){const t=new TextDecoder().decode(typeof b==='string'?new TextEncoder().encode(b):b);assert(!t.includes('PERSONAL_SENTINEL_DO_NOT_EXPORT'));assert(!t.includes('TEACHING_SENTINEL_DO_NOT_EXPORT'));}const plan=planImport(compose(built,blankWorkspace()).packs,parsed.packs,blankWorkspace().overlays);assert.deepEqual(plan.conflicts,[]);assert.equal(planImport(plan.candidate,parsed.packs,blankWorkspace().overlays).unchanged.length,1);assert.equal(planImport(c.packs,parsed.packs,r.ws.overlays).conflicts.length>0,true,'source ownership must not be overwritten');});
test('1.1 local PDFs filed under public notebooks export into safe context IDs and import into a default fresh app',async()=>{const ws=blankWorkspace(),c=compose(built,ws),project=c.projects[0];const r=await local(ws,project.id,''),before=structuredClone(r.ws);const out=await exportPrivatePdfLibrary(r.c,async key=>r.ws.assets.find(a=>a.key===key)),parsed=await readWorkspace((await unzipBounded(out.bytes)).files,schemas);assert.deepEqual(planImport(c.packs,parsed.packs,blankWorkspace().overlays).conflicts,[]);assert.notEqual(parsed.packs[0].projects[0].id,project.id);assert.equal(parsed.packs[0].pages[0].id,r.page.id);assert.deepEqual(r.ws,before);});
test('1.1 private PDF export refuses missing and corrupt local bytes',async()=>{const r=await local();await assert.rejects(exportPrivatePdfLibrary(r.c,async()=>undefined),/Missing private PDF bytes/);await assert.rejects(exportPrivatePdfLibrary(r.c,async()=>({...r.asset,bytes})),/checksum/);});
test('1.1 template builder runs offline; actual reader accepts it and retains required mappings',async()=>{execFileSync('python',['templates/pdf-library/tools/build_atlas_library.py','--root','templates/pdf-library'],{stdio:'pipe'});const file='templates/pdf-library/out/atlas-pdf-library.zip',parsed=await readWorkspace((await unzipBounded(new Uint8Array(await fs.readFile(file)))).files,schemas);assert.equal(parsed.validation.pages,2);assert.equal(parsed.packs[0].documents.length,2);assert.equal(parsed.assets.length,2);assert.equal(parsed.packs[0].documents[0].language,'en');assert(parsed.packs[0].pages.some(p=>p.tags.includes('tech:microsoft-fabric')));assert.deepEqual(planImport(compose(built,blankWorkspace()).packs,parsed.packs,blankWorkspace().overlays).conflicts,[]);});
test('1.1 template PDF tamper and missing bytes are rejected by actual ZIP reader',async()=>{const files=(await unzipBounded(new Uint8Array(await fs.readFile('templates/pdf-library/out/atlas-pdf-library.zip')))).files,key=[...files.keys()].find(k=>k.endsWith('.pdf'));const tamper=new Map(files),changed=files.get(key).slice();changed[changed.length-2]^=1;tamper.set(key,changed);await assert.rejects(readWorkspace(tamper,schemas),/hash|SHA|checksum/i);const missing=new Map(files);missing.delete(key);await assert.rejects(readWorkspace(missing,schemas),/Missing|missing/);});
test('1.1 synthetic 137-page 685-term scale preserves IDs, glossary references and additive private PDF composition',async()=>{const ws=workspace(),pack={manifest:{id:'atlas.synthetic.scale',version:'1.0.0',visibility:'private',requires:[]},projects:[{id:'project.synthetic.scale',title:'Synthetic scale',icon:'book',description:'Generated, not the supplied private corpus',nodes:[]}],pages:[],glossary:[],documents:[],hash:'e'.repeat(64),migration:[],assetKeys:[]};for(let i=0;i<137;i++){const p={id:'page.synthetic.'+i,title:'Synthetic scale '+i,summary:'ScaleFixture '+i,blocks:[{id:'block.synthetic.'+i,type:'markdown',text:'Synthetic source only.'}],tags:[],terms:[],related:[],sources:[]};pack.pages.push(p);pack.projects[0].nodes.push({id:'node.synthetic.'+i,title:p.title,pageId:p.id});for(let j=0;j<5;j++){const id='term.synthetic.'+i+'.'+j;pack.glossary.push({id,label:'Scale term '+i+'.'+j,definition:'Synthetic definition',pageIds:[p.id]});p.terms.push(id);}}ws.imports=[pack];const before=structuredClone(pack),r=await local(ws);assert.equal(r.c.pages.filter(p=>p.id.startsWith('page.synthetic.')).length,137);assert.equal(r.c.glossary.filter(t=>t.id.startsWith('term.synthetic.')).length,685);assert.deepEqual(ws.imports[0],before);assert(searchCatalog(r.c,'ScaleFixture 136').pages.length>0);});
