import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {blankWorkspace,newView,compose,toggleCompare} from '../dist-offline/app/core/workspace.js';
import {migratePersonal,activeSession,selectWorkspace,categoryMatches} from '../dist-offline/app/core/workspace-slots.js';
import {saveReadingState,restoreReadingState} from '../dist-offline/app/core/saved-states.js';
import {recordDocumentVisit,documentBlockMatches,relatedPageOverlay} from '../dist-offline/app/core/document-context.js';
import {pdfNavigationSections} from '../dist-offline/app/core/pdf-navigation.js';
import {searchPdfText,searchOpenPdf,registerPdfTextSearch} from '../dist-offline/app/pdf/text-search.js';
import {categoryPageRows} from '../dist-offline/app/companion/tree.js';
import {READER_COMPANION} from '../dist-offline/app/companion/sample.js';
import {validatePersonal} from '../src/storage/personal-validation.mjs';
import {validateState} from '../src/storage/state-validation.mjs';
import {makeBackup,readBackup,unzipBounded} from '../src/storage/archives.mjs';
import {loadSchemas,readWorkspace} from '../src/core/packs.mjs';
import {readFiles} from '../tools/fs.mjs';
import {stepPhysicalPage} from '../src/pdf/physical-pages.mjs';
import {createWheelPager} from '../src/pdf/wheel-navigation.mjs';
import {validateInterviewSet,questionToPage,interviewProject,SQL_PROGRESSION,INTERVIEW_STYLES} from '../src/interview/content.mjs';
const copy=structuredClone;
const schemas=await loadSchemas(n=>fs.readFile('src/content/schemas/'+n,'utf8'));
const source=await readWorkspace(await readFiles('content'),schemas);
const built={packs:source.packs,groups:source.workspace.groups,assets:source.assets,releaseId:'125-unit'};
const interview=JSON.parse(await fs.readFile('content/interviews/questions.json','utf8'));
function setup(){const w=blankWorkspace();w.personal=migratePersonal(w.personal);const s=activeSession(w.personal),v=newView('page.interview.sql-q1');s.panes[0].views=[v];s.panes[0].active=v.id;s.screen='reader';return w;}
const catalogue=compose(built,setup());

test('1.2.5 per-pane visibility remains independent in every workspace, save, undo and backup',async()=>{
 const w=setup(),p=w.personal,s=p.session;toggleCompare(s);s.panes[0].readerChromeCollapsed=true;s.panes[1].readerChromeCollapsed=false;
 const expected=copy(s),save=saveReadingState(p,'all');selectWorkspace(p,2);activeSession(p).panes[0].readerChromeCollapsed=false;
 p.session.panes[0].readerChromeCollapsed=false;restoreReadingState(p,save);assert.deepEqual(p.session,expected);
 recordDocumentVisit(p,'page.interview.sql-q1',5);p.notes['page.interview.sql-q1']={pageId:'page.interview.sql-q1',text:'I missed the output grain.',updatedAt:9};
 const assets=new Map(source.assets.map(a=>[a.key,a]));const backup=await makeBackup(w,built,async key=>assets.get(key));
 const restored=(await readBackup((await unzipBounded(backup.bytes)).files,schemas)).workspace;
 assert.deepEqual(restored.personal,p);assert.equal(restored.personal.session.panes[0].readerChromeCollapsed,true);assert.equal(restored.personal.session.panes[1].readerChromeCollapsed,false);
});
test('1.2.5 legacy personal state needs no history migration or new global controls setting',()=>{const w=setup();delete w.personal.documentVisits;const before=copy(w);validatePersonal(w.personal);assert.deepEqual(w,before);assert(!Object.hasOwn(w.personal.session,'readerChromeCollapsed'));});
test('1.2.5 visits have bounded unique recency, stable first-open time and monotonic clocks',()=>{
 const p=setup().personal;recordDocumentVisit(p,'page.a',30);recordDocumentVisit(p,'page.b',40);recordDocumentVisit(p,'page.a',20);
 assert.deepEqual(p.documentVisits[0],{pageId:'page.a',firstOpenedAt:30,lastOpenedAt:30});
 for(let i=0;i<65;i++)recordDocumentVisit(p,'page.'+i,100+i);assert.equal(p.documentVisits.length,50);assert.equal(p.documentVisits[0].pageId,'page.64');validatePersonal(p);
});
for(const [name,visits] of Object.entries({duplicate:[{pageId:'page.a',firstOpenedAt:1,lastOpenedAt:1},{pageId:'page.a',firstOpenedAt:1,lastOpenedAt:2}],chronology:[{pageId:'page.a',firstOpenedAt:2,lastOpenedAt:1}],timestamp:[{pageId:'page.a',firstOpenedAt:1,lastOpenedAt:Infinity}],identifier:[{pageId:'../private',firstOpenedAt:1,lastOpenedAt:1}],overlong:Array.from({length:51},(_,n)=>({pageId:'page.'+n,firstOpenedAt:1,lastOpenedAt:1}))}))test('1.2.5 invalid document visits rejected before restore: '+name,()=>{const p=setup().personal;p.documentVisits=visits;assert.throws(()=>validatePersonal(p));});
test('1.2.5 workspace restore leaves current history and interview reflections alone',()=>{const p=setup().personal,id=saveReadingState(p,1);recordDocumentVisit(p,'page.interview.sql-q2',10);p.notes['page.interview.sql-q1']={pageId:'page.interview.sql-q1',text:'Check fan-out',updatedAt:10};const before=copy({v:p.documentVisits,n:p.notes});restoreReadingState(p,id);assert.deepEqual({v:p.documentVisits,n:p.notes},before);});
test('1.2.5 scoped search finds code and nested sections only in the supplied document',()=>{const p=catalogue.pages.find(p=>p.id==='page.interview.sql-q1');assert(documentBlockMatches(p,'GROUP BY').some(x=>x.id.endsWith('.code')));assert.equal(documentBlockMatches(p,'QA-ANCHOR-BRAVO').length,0);assert.equal(documentBlockMatches(p,'  ').length,0);assert(documentBlockMatches(p,'reasoning').length>0);});
test('1.2.5 explicit related links are non-destructive overlays and retain earlier edits/base hash',async()=>{const w=setup(),p=catalogue.pages.find(p=>p.id==='page.interview.sql-q1'),before=copy(p);const linked=await relatedPageOverlay(catalogue,w.overlays,p.id,'page.atlas.pdf');assert(linked.page.related.includes('page.atlas.pdf'));assert.deepEqual(p,before);w.overlays.pages[p.id]={...linked,page:{...linked.page,title:'My own title'}};const removed=await relatedPageOverlay(catalogue,w.overlays,p.id,'page.atlas.pdf',true);assert.equal(removed.baseHash,linked.baseHash);assert.equal(removed.page.title,'My own title');assert(!removed.page.related.includes('page.atlas.pdf'));await assert.rejects(relatedPageOverlay(catalogue,w.overlays,p.id,p.id));});
test('1.2.5 edited native interview content, related PDF link and remarks survive verified backup',async()=>{const w=setup(),id='page.interview.sql-q1';w.overlays.pages[id]=await relatedPageOverlay(catalogue,w.overlays,id,'page.atlas.pdf');w.overlays.pages[id].page.title='Personal SQL revision';w.personal.notes[id]={pageId:id,text:'My reflection stays private.',updatedAt:10};recordDocumentVisit(w.personal,id,10);validateState(w,schemas);const assets=new Map(source.assets.map(a=>[a.key,a]));const backup=await makeBackup(w,built,async k=>assets.get(k));const restored=(await readBackup((await unzipBounded(backup.bytes)).files,schemas)).workspace;assert.deepEqual(restored.overlays,w.overlays);assert.deepEqual(restored.personal,w.personal);});
function projectionFixture(){const document={id:'doc.spark',pageId:'page.spark'};const leaf={id:'node.pdf.spark',title:'Apache Spark: 30 concepts',pageId:document.pageId};const subject={id:'node.spark',title:'Apache Spark',children:[leaf]};const domain={id:'node.de',title:'Data Engineering',children:[subject]};const project={id:'project.pdfatlas',title:'PDF Atlas',nodes:[{id:'node.wrapper',title:'PDF Atlas',children:[domain]}]};return {project,document,leaf};}
test('1.2.5 PDF projection removes wrapper taxonomy without mutating metadata, IDs or actions',()=>{const {project,document,leaf}=projectionFixture(),before=copy(project),out=pdfNavigationSections([project],[document],new Set());assert.deepEqual(out.map(x=>x.title),['Data Engineering']);assert.equal(out[0].subjects[0].title,'Apache Spark');const entry=out[0].subjects[0].entries[0];assert.equal(entry.node,leaf);assert.equal(entry.project,project);assert.equal(entry.document,document);assert(entry.path.includes('PDF Atlas'));assert.deepEqual(project,before);});
for(const hidden of ['node.de','node.spark','node.pdf.spark','page.spark','project.pdfatlas'])test('1.2.5 projected PDF respects archived '+hidden,()=>{const {project,document}=projectionFixture();assert.equal(pdfNavigationSections([project],[document],new Set([hidden])).length,0);});
test('1.2.5 PDF projection preserves explicit notebook filtering and PDF category topic granularity',()=>{const {project,document}=projectionFixture();assert.equal(pdfNavigationSections([project],[document],new Set(),new Set([project.id])).length,0);const rows=categoryPageRows(READER_COMPANION.categories[0],READER_COMPANION);assert(rows.filter(r=>r.page===2).length>=2);assert(rows.every(r=>Number.isInteger(r.page)&&!r.children));});
for(const [page,total,size,dir] of [[3,9,4,-1],[8,8,4,1],[2,8,2,-1],[8,8,2,1]])test(`1.2.5 terminal wheel retains selected page ${page} in group ${size}`,()=>assert.equal(stepPhysicalPage(page,total,dir,size),page));
test('1.2.5 wheel latch consumes one completed momentum burst, slow next gesture still progresses',()=>{const gate=createWheelPager(),event={mode:'single',top:false,bottom:true,deltaY:30};assert.equal(gate({...event,now:0}),0);assert.equal(gate({...event,now:350}),0);assert.equal(gate({...event,now:700}),1);assert.equal(gate.isLatched(),true);for(let now=720;now<1200;now+=20)assert.equal(gate({...event,now}),0);assert.equal(gate.isLatched(),true);assert.equal(gate({...event,now:1500}),0);assert.equal(gate.isLatched(),false);assert.equal(gate({...event,now:1850}),0);assert.equal(gate({...event,now:2200}),1);});
for(const mode of ['single','spread','grid'])test('1.2.5 slow-wheel accumulation remains available in '+mode,()=>{const gate=createWheelPager();const results=[0,350,700].map(now=>gate({deltaY:30,now,mode,top:false,bottom:true}));assert.deepEqual(results,[0,0,1]);});
test('1.2.5 PDF text search uses physical pages, plain excerpts and aborts before further work',async()=>{const calls=[],controller=new AbortController();const pdf={numPages:3,getPage:async n=>{calls.push(n);return {getTextContent:async()=>({items:[{str:n===2?'alpha <script>literal</script> beta':'other'}]})};}};const result=await searchPdfText(pdf,'alpha',controller.signal);assert.deepEqual(result.hits.map(h=>h.page),[2]);assert(result.hits[0].excerpt.includes('<script>'));assert.deepEqual(calls,[1,2,3]);controller.abort();await assert.rejects(searchPdfText(pdf,'alpha',controller.signal),{name:'AbortError'});assert.equal(calls.length,3);});
test('1.2.5 Context searches only the permitted engine for the exact workspace/pane/document',async()=>{const signal=new AbortController().signal;const cleanup=registerPdfTextSearch(1,'a','doc.a',async()=>({hits:[{page:2,excerpt:'local'}],total:2,searched:2,hasText:true}));assert.equal((await searchOpenPdf(1,'a','doc.a','x',signal)).hits[0].page,2);for(const args of [[2,'a','doc.a'],[1,'b','doc.a'],[1,'a','doc.b']])await assert.rejects(searchOpenPdf(...args,'x',signal),/Open this PDF/);cleanup();await assert.rejects(searchOpenPdf(1,'a','doc.a','x',signal));});
test('1.2.5 replaced PDF search registration is not removed by earlier unmount',async()=>{const signal=new AbortController().signal;const old=registerPdfTextSearch(1,'a','doc.a',async()=>({hits:[]}));const latest=registerPdfTextSearch(1,'a','doc.a',async()=>({hits:[{page:3}]}));old();assert.equal((await searchOpenPdf(1,'a','doc.a','x',signal)).hits[0].page,3);latest();});
test('1.2.5 interview set contains >=3 each style and generates exactly the reviewed native pack',()=>{validateInterviewSet(interview);for(const style of INTERVIEW_STYLES)assert(interview.questions.filter(q=>q.style===style).length>=3);const pack=source.packs.find(p=>p.manifest.id==='atlas.interview-samples');assert.equal(pack.pages.length,15);for(const q of interview.questions)assert.deepEqual(pack.pages.find(p=>p.id==='page.interview.'+q.id),questionToPage(q));assert.deepEqual(pack.projects,[interviewProject(interview.questions)]);});
test('1.2.5 seven interview categories and deeper topic nesting stay native and filter as Job',()=>{const project=interviewProject(interview.questions);assert.equal(project.nodes.length,7);assert(categoryMatches(project.id,'job'));assert(project.nodes.find(n=>n.title==='SQL').children.some(n=>n.children.some(n=>n.children?.some(n=>n.pageId))));});
test('1.2.5 canonical Q1-Q5 reasoning sequence and future harder families are retained',()=>{assert.deepEqual(SQL_PROGRESSION.map(x=>x.step),[1,2,3,4,5,6,7,8]);const sql=interview.questions.filter(q=>q.style==='SQL');assert.deepEqual(sql.map(q=>q.id),['sql-q1','sql-q2','sql-q3','sql-q4','sql-q5']);assert.equal(sql[0].prompt,'Classic SQL screener: filter to PAID orders in 2026 and return total net_amount per customer. What clauses do you need, and what is the output grain?');assert.equal(sql[1].followUps[0],'What happens if one customer has multiple matching dimension rows before you SUM revenue?');assert(sql[2].prompt.includes('second-highest distinct salary'));assert(sql[3].prompt.includes('automatically faster'));assert(sql[4].followUps[0].includes('both LAG and a self-join'));assert.deepEqual(SQL_PROGRESSION.slice(5).map(x=>x.family),['Compositional SQL','Temporal / relational logic','Optimization reasoning']);});
test('1.2.5 coding variants teach one dictionary pattern with alternatives, complexity and followups',()=>{const questions=interview.questions.filter(q=>q.style==='Coding');assert.equal(new Set(questions.map(q=>q.pattern)).size,1);assert(questions.every(q=>q.example.language==='python'&&q.alternatives.length&&q.complexity&&q.followUps.length));assert(new Set(questions.map(q=>q.example.code)).size===3);});
for(const mutate of [x=>x.questions[0].style='Game',x=>x.questions.push(copy(x.questions[0])),x=>x.questions[0].reasoning=[],x=>x.questions.find(q=>q.style==='Coding').alternatives=[]])test('1.2.5 invalid interview authoring model rejected '+mutate.toString(),()=>{const data=copy(interview);mutate(data);assert.throws(()=>validateInterviewSet(data));});

test('1.2.5 actual public PDF Atlas pack projects directly to Data Engineering / Apache Spark',()=>{const original=copy(catalogue.projects);const sections=pdfNavigationSections(catalogue.projects,catalogue.documents,new Set());assert(!sections.some(s=>s.title==='PDF Atlas'));const domain=sections.find(s=>s.title==='Data Engineering');assert(domain);const subject=domain.subjects.find(s=>s.title==='Apache Spark');assert.equal(subject.entries.length,2);assert(subject.entries.some(e=>e.document.pageId==='page.pdfatlas.spark-concepts'));assert.deepEqual(catalogue.projects,original);});

// Only the intended active-document reopen timestamp is permitted to differ.
test("1.2.5 runtime persistence assertion rejects unrelated mutations", async()=>{
 const {spawnSync}=await import("node:child_process");
 const result=spawnSync(process.env.PYTHON??"python",["tests/persistence_assertions_test.py"],{encoding:"utf8"});
 assert.equal(result.status,0,result.stderr||result.stdout);
});
