import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {blankPersonal,blankWorkspace,newView,current} from '../dist-offline/app/core/workspace.js';
import {migratePersonal,selectWorkspace,activeSession} from '../dist-offline/app/core/workspace-slots.js';
import {saveReadingState,restoreReadingState,renameReadingState,deleteReadingState,latestStateSave,STATE_SAVE_LIMITS} from '../dist-offline/app/core/saved-states.js';
import {validatePersonal} from '../src/storage/personal-validation.mjs';
import {makeBackup,readBackup,unzipBounded} from '../src/storage/archives.mjs';
import {loadSchemas} from '../src/core/packs.mjs';
import {createWheelPager} from '../src/pdf/wheel-navigation.mjs';
import {repairAbsentPersonalOptionals} from '../dist-offline/app/core/personal-state.js';
import {resolveStudy,studyTreeKey,directCategoryPages} from '../dist-offline/app/companion/tree.js';
import {READER_COMPANION} from '../dist-offline/app/companion/sample.js';
const copy=structuredClone;
function personal(){const p=migratePersonal(blankPersonal());for(const n of [1,2,3,4,5]){selectWorkspace(p,n);const s=activeSession(p),v=newView('page.atlas.pdf');current(v).pdfPage=n;current(v).anchor={pdfPage:n,pdfRevision:'a'.repeat(64),pdfOffset:n/10};s.panes=[{id:'left',views:[v],active:v.id,readerChromeCollapsed:n%2===0}];s.screen='reader';s.categoryFilter=n===2?'cloud':null;s.pdfTreeExpanded=['["doc","revision","document",""]'];s.ratio=40+n;s.theme=n===3?'slate':'fluent';}p.activeWorkspaceSlot=2;p.notes.note={pageId:'page.atlas.pdf',text:'Keep current notes',updatedAt:42};p.ratings['page.atlas.pdf']='green';p.bookmarks=[{id:'bookmark.original',pageId:'page.atlas.pdf',title:'Reading bookmark',createdAt:1}];return p;}
function sessions(p){return copy({session:p.session,workspaceSlots:p.workspaceSlots,activeWorkspaceSlot:p.activeWorkspaceSlot});}
function content(p){return copy({notes:p.notes,ratings:p.ratings,bookmarks:p.bookmarks});}
const schemas=await loadSchemas(n=>fs.readFile('src/content/schemas/'+n,'utf8'));
const built=JSON.parse(await fs.readFile('dist-offline/content.json','utf8'));
async function asset(key){const a=built.assets.find(x=>x.key===key);return a?{...a,bytes:new Uint8Array(await fs.readFile('dist-offline/'+a.path))}:undefined;}

test('1.2.3 old personal state loads without an empty saves module being injected',()=>{const p=blankPersonal(),before=copy(p),m=migratePersonal(p);validatePersonal(m);assert(!Object.hasOwn(m,'savedStates'));assert.deepEqual(p,before);});
test('1.2.3 workspace save freezes every session field without modifying the live session',()=>{const p=personal(),before=sessions(p),id=saveReadingState(p,2,'Focus on partitions',100);assert.deepEqual(sessions(p),before);const e=latestStateSave(p,2);assert.equal(e.id,id);assert.deepEqual(e.session,p.workspaceSlots[2]);activeSession(p).panes[0].views[0].history[0].pdfPage=1;assert.equal(e.session.panes[0].views[0].history[0].pdfPage,2);validatePersonal(p);});
test('1.2.3 all save captures five distinct sessions and the active workspace',()=>{const p=personal(),expected=sessions(p);saveReadingState(p,'all','End of day',100);const e=latestStateSave(p,'all');assert.deepEqual({session:e.session,workspaceSlots:e.workspaceSlots,activeWorkspaceSlot:e.activeWorkspaceSlot},expected);assert.notEqual(e.workspaceSlots[2],p.workspaceSlots[2]);});
test('1.2.3 single restore targets its original slot and leaves the other four byte-equivalent',()=>{const p=personal(),id=saveReadingState(p,2),saved=copy(p.workspaceSlots[2]);p.activeWorkspaceSlot=4;p.workspaceSlots[2].theme='academic';p.workspaceSlots[3].categoryFilter='norsk';const other=copy([p.session,p.workspaceSlots[3],p.workspaceSlots[4],p.workspaceSlots[5]]);restoreReadingState(p,id);assert.deepEqual(p.workspaceSlots[2],saved);assert.equal(p.activeWorkspaceSlot,2);assert.deepEqual([p.session,p.workspaceSlots[3],p.workspaceSlots[4],p.workspaceSlots[5]],other);});
test('1.2.3 all restore restores the complete session layout, not shared content',()=>{const p=personal(),expected=sessions(p),id=saveReadingState(p,'all');p.session.theme='slate';p.workspaceSlots[3].panes=[];p.notes.note.text='New work must not disappear';p.ratings['page.atlas.pdf']='orange';p.bookmarks.push({id:'bookmark.new',pageId:'page.atlas.pdf',title:'Later',createdAt:2});const data=content(p);p.workspaceSlots[3]=blankPersonal().session;restoreReadingState(p,id);assert.deepEqual(sessions(p),expected);assert.deepEqual(content(p),data);});
test('1.2.3 restoring a save creates an independent undo point, not a new manual save',()=>{const p=personal(),id=saveReadingState(p,2,'Checkpoint',100);p.workspaceSlots[2].theme='slate';const before=copy(p.workspaceSlots[2]);restoreReadingState(p,id,200);assert.deepEqual(p.savedStates.safety[2].session,before);assert.equal(p.savedStates.entries.length,1);assert.equal(latestStateSave(p,2).id,id);const undoId=p.savedStates.safety[2].id;restoreReadingState(p,undoId,300);assert.deepEqual(p.workspaceSlots[2],before);assert.equal(p.savedStates.restoreRevision,2);assert.notEqual(p.savedStates.safety[2].id,undoId);});
test('1.2.3 all-workspace undo returns the pre-restore layout and active slot',()=>{const p=personal(),id=saveReadingState(p,'all');p.activeWorkspaceSlot=5;p.session.theme='lavender';p.workspaceSlots[4].leftOpen=false;const before=sessions(p);restoreReadingState(p,id);restoreReadingState(p,p.savedStates.safety.all.id);assert.deepEqual(sessions(p),before);});
test('1.2.3 all restore preserves exact uninitialized-slot absence',()=>{const p=migratePersonal(blankPersonal()),expected=sessions(p),id=saveReadingState(p,'all');selectWorkspace(p,5);restoreReadingState(p,id);assert.deepEqual(sessions(p),expected);assert.deepEqual(p.workspaceSlots,{});});
test('1.2.3 an inactive unused workspace can be saved without altering active workspace',()=>{const p=migratePersonal(blankPersonal());saveReadingState(p,4);assert.equal(p.activeWorkspaceSlot,1);assert.deepEqual(p.workspaceSlots,{});restoreReadingState(p,latestStateSave(p,4).id);assert.equal(p.activeWorkspaceSlot,4);assert.deepEqual(p.workspaceSlots[4],blankPersonal().session);});
test('1.2.3 repeated saves never nest the saved-state store in snapshots',()=>{const p=personal();for(let n=0;n<12;n++)saveReadingState(p,n%2?'all':2);for(const e of p.savedStates.entries){assert(!Object.hasOwn(e,'savedStates'));assert(!Object.hasOwn(e.session,'savedStates'));assert(!Object.hasOwn(e,'notes'));}validatePersonal(p);});
test('1.2.3 manual saves have a per-scope cap and are never silently pruned',()=>{const p=personal();for(let n=0;n<20;n++)saveReadingState(p,2,'Save '+n,n);const before=copy(p);assert.throws(()=>saveReadingState(p,2),/20 saves/);assert.deepEqual(p,before);saveReadingState(p,3);deleteReadingState(p,latestStateSave(p,2).id);saveReadingState(p,2);assert.equal(p.savedStates.entries.filter(e=>e.scope==='workspace'&&e.slot===2).length,20);});
test('1.2.3 mini history is bounded and chronological by action insertion',()=>{const p=personal(),id=saveReadingState(p,1,'Title',1);for(let n=0;n<40;n++)renameReadingState(p,id,'Title '+n,'Next step '+n,n+2);assert.equal(p.savedStates.history.length,30);assert.equal(p.savedStates.history[0].title,'Title 39');assert.equal(p.savedStates.history[0].action,'rename');assert.equal(latestStateSave(p,1).createdAt,1);});
test('1.2.3 rename/progress note and delete preserve sessions and reading bookmarks',()=>{const p=personal(),expected=sessions(p),data=content(p),id=saveReadingState(p,1);renameReadingState(p,id,'SQL recap','Next: window functions');assert.equal(latestStateSave(p,1).note,'Next: window functions');deleteReadingState(p,id);assert.equal(latestStateSave(p,1),undefined);assert.deepEqual(sessions(p),expected);assert.deepEqual(content(p),data);});
test('1.2.3 the quick restore chooses the newest manual save, never an undo snapshot',()=>{const p=personal(),a=saveReadingState(p,1,'A',10),b=saveReadingState(p,1,'B',20);restoreReadingState(p,a,30);assert.equal(latestStateSave(p,1).id,b);renameReadingState(p,a,'Renamed A','',40);assert.equal(latestStateSave(p,1).id,b);});
test('1.2.3 saves with equal timestamps still use last inserted as latest',()=>{const p=personal();saveReadingState(p,1,'A',1);const b=saveReadingState(p,1,'B',1);assert.equal(latestStateSave(p,1).id,b);});
test('1.2.3 a missing restore ID cannot mutate state',()=>{const p=personal(),before=copy(p);assert.throws(()=>restoreReadingState(p,'missing'));assert.deepEqual(p,before);});
for(const scope of [0,6,NaN,'1','wrong'])test('1.2.3 invalid save scope '+scope+' is rejected atomically',()=>{const p=personal(),before=copy(p);assert.throws(()=>saveReadingState(p,scope));assert.deepEqual(p,before);});
for(const [title,note] of [['',''],['A'.repeat(121),''],['Title','x'.repeat(501)]])test('1.2.3 invalid save metadata is rejected without pruning',()=>{const p=personal(),id=saveReadingState(p,1),before=copy(p);assert.throws(()=>renameReadingState(p,id,title,note));assert.deepEqual(p,before);});
const corruptions={
 'nested invalid active view':p=>{p.savedStates.entries[0].session.panes[0].active='wrong';},
 'nested invalid PDF page':p=>{p.savedStates.entries[0].session.panes[0].views[0].history[0].pdfPage=0;},
 'fractional workspace':p=>{p.savedStates.entries[0].slot=2.5;},
 'unknown saved schema':p=>{p.savedStates.schemaVersion=9;},
 'embedded recursive store':p=>{p.savedStates.entries[0].session.savedStates={};},
 'duplicate save':p=>{p.savedStates.entries.push(copy(p.savedStates.entries[0]));},
 'mismatched undo scope':p=>{p.savedStates.safety.all={...copy(p.savedStates.entries[0]),id:'save.other'};},
 'invalid restoration revision':p=>{p.savedStates.restoreRevision=-1;},
 'excess history':p=>{p.savedStates.history=Array.from({length:31},(_,n)=>({...p.savedStates.history[0],id:'e.'+n}));},
 'unknown field':p=>{p.savedStates.externalUpload='https://example.invalid';},
 'nonfinite timestamp':p=>{p.savedStates.entries[0].createdAt=Infinity;},
 'unsafe structural key':p=>{p.savedStates.entries[0].session=JSON.parse('{"__proto__":{"polluted":true}}');},
 'duplicate PDF tree disclosures':p=>{p.savedStates.entries[0].session.pdfTreeExpanded=['x','x'];}
};
for(const [label,mutate] of Object.entries(corruptions))test('1.2.3 saved-state validation rejects '+label,()=>{const p=personal();saveReadingState(p,2);mutate(p);assert.throws(()=>validatePersonal(p));assert.equal({}.polluted,undefined);});
test('1.2.3 all snapshot with missing active numbered workspace is rejected',()=>{const p=personal();saveReadingState(p,'all');delete p.savedStates.entries[0].workspaceSlots[2];assert.throws(()=>validatePersonal(p),/active slot missing/);});
test('1.2.3 complete backup ZIP preserves saves, undo points, progress notes and activity exactly',async()=>{const ws=blankWorkspace();ws.personal=personal();const a=saveReadingState(ws.personal,2);renameReadingState(ws.personal,a,'Morning Spark','Next: deployment modes');saveReadingState(ws.personal,'all');ws.personal.workspaceSlots[2].theme='slate';restoreReadingState(ws.personal,a);const expected=copy(ws.personal);const backup=await makeBackup(ws,built,asset),roundtrip=await readBackup((await unzipBounded(backup.bytes)).files,schemas);assert.deepEqual(roundtrip.workspace.personal,expected);assert.equal(roundtrip.schemaVersion,3);});
test('1.2.3 invalid snapshot is rejected when importing a full backup before any write',async()=>{const ws=blankWorkspace();ws.personal=personal();saveReadingState(ws.personal,2);const backup=await makeBackup(ws,built,asset),{files}=await unzipBounded(backup.bytes),data=JSON.parse(new TextDecoder().decode(files.get('backup.json')));data.workspace.personal.savedStates.entries[0].session.panes[0].views[0].history[0].zoom=999;files.set('backup.json',new TextEncoder().encode(JSON.stringify(data)));await assert.rejects(readBackup(files,schemas),/zoom/);});
test('1.2.3 saved PDF anchors with absent optional values remain exactly JSON representable',()=>{const p=personal();saveReadingState(p,1);p.savedStates.entries[0].session.panes[0].views[0].history[0].anchor.pdfRevision=undefined;const fixed=repairAbsentPersonalOptionals(p);assert.deepEqual(fixed,JSON.parse(JSON.stringify(fixed)));assert.equal(p.savedStates.entries[0].session.panes[0].views[0].history[0].anchor.pdfRevision,undefined);});
function wheel(overrides={}){return {deltaY:30,deltaX:0,deltaMode:0,now:0,mode:'single',top:false,bottom:true,...overrides};}
test('1.2.3 slow 30px ticks separated by 350ms turn at the edge',()=>{const pager=createWheelPager();assert.equal(pager(wheel()),0);assert.equal(pager(wheel({now:350})),0);assert.equal(pager(wheel({now:700})),1);});
test('1.2.3 opposite small ticks cannot inherit accumulated downward movement',()=>{const pager=createWheelPager();pager(wheel({deltaY:60}));assert.equal(pager(wheel({now:400,deltaY:-30,top:true,bottom:false})),0);});
test('1.2.3 old abandoned edge ticks expire',()=>{const pager=createWheelPager();pager(wheel({deltaY:60}));assert.equal(pager(wheel({now:1800})),0);});
test('1.2.3 returning to mid-page discards stale edge ticks',()=>{const pager=createWheelPager();pager(wheel({deltaY:60}));pager(wheel({now:300,bottom:false}));assert.equal(pager(wheel({now:600})),0);});
test('1.2.3 a sustained high-frequency burst advances once only',()=>{const pager=createWheelPager();let turns=0;for(let n=0;n<300;n++)turns+=pager(wheel({now:n*10,deltaY:30}));assert.equal(turns,1);});
test('1.2.3 invalid wheel inputs cannot poison the next gesture',()=>{const pager=createWheelPager();assert.equal(pager(wheel({deltaY:NaN})),0);assert.equal(pager(wheel({deltaY:100,now:300})),1);});
test('1.2.3 study projection is revision-bound and never mutates canonical metadata',()=>{const ws=blankWorkspace(),d=built.packs.flatMap(p=>p.documents).find(d=>d.id==='doc.atlas.pdf'),before=copy(ws);assert.equal(resolveStudy(d,ws).companion.documentId,d.id);assert.equal(resolveStudy({...d,sha256:'b'.repeat(64)},ws).companion,undefined);assert.deepEqual(ws,before);});
test('1.2.3 projection keys cannot alias punctuation in document/category identifiers',()=>{assert.notEqual(studyTreeKey({id:'a:b',sha256:'x'},'category','c'),studyTreeKey({id:'a',sha256:'x'},'category','b:c'));});
test('1.2.3 category page links deduplicate physical pages without confusing concept indexes',()=>{const cat={id:'reading',title:'Reading',pageRefs:[1,1,2],pageRanges:[[2,3]]};assert.deepEqual(directCategoryPages(cat,READER_COMPANION),[1,2,3]);});

test('1.2.3 timestamps outside the browser Date range are rejected atomically',()=>{const p=personal(),before=copy(p);assert.throws(()=>saveReadingState(p,1,'Invalid date',8640000000000001));assert.deepEqual(p,before);saveReadingState(p,1);p.savedStates.history[0].createdAt=8640000000000001;assert.throws(()=>validatePersonal(p));});
