/** Synthetic capacity/performance diagnostic. Pure snapshots, never IndexedDB proof.
 * Intentionally does not claim 25k compaction or a browser capacity recovery pass.
 */
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';
import {demoWorkspace,provenance} from './v23/fixtures.mjs';
import {blankWorkspace} from '../dist-offline/app/core/workspace.js';import {advanceHistory} from '../dist-offline/app/history/engine.js';
import {validateHistory,HISTORY_LIMITS} from '../dist-offline/app/history/validation.mjs';import {makeHistoryArchive,verifyHistoryArchive,planCompaction} from '../dist-offline/app/durability/archive.mjs';
import {sha256,stable} from '../dist-offline/app/core/validation.mjs';
const out=process.env.ATLAS_EVIDENCE??'docs/evidence/v23/capacity';await fs.mkdir(out,{recursive:true});
const demo=await demoWorkspace(),base=structuredClone(demo.history.revisions.find(r=>r.resourceType==='notebook-page'&&r.resourceId==='demo.v23.notebook'));
base.snapshot.page.blocks=[];base.snapshot.page.related=[];delete base.snapshot.assetRefs;delete base.changeSetId;delete base.sourceDetail;const results=[];
async function history(count,per=2000){const h={schemaVersion:1,meta:{...demo.history.meta,epoch:100},heads:[],revisions:[],reviews:[]};let group=-1,snapshot,contentHash,id;
 for(let i=0;i<count;i++){if(Math.floor(i/per)!==group){group=Math.floor(i/per);id='stress.v23.page.'+group;snapshot=structuredClone(base.snapshot);snapshot.page.id=id;contentHash=await sha256(stable(snapshot));}
 const number=i%per+1,r={...base,revisionId:'stress.revision.'+i,resourceId:id,resourceKey:'notebook-page:'+id,number,parentRevisionId:number===1?null:'stress.revision.'+(i-1),snapshot,contentHash,summary:'Synthetic forced revision '+i};h.revisions.push(r);if(number===per||i===count-1)h.heads.push({kind:'head',schemaVersion:1,resourceKey:r.resourceKey,revisionId:r.revisionId,number:r.number,contentHash});}return h;}
async function check(name,fn){const at=performance.now();try{results.push({name,status:'PASS',detail:await fn(),durationMs:Math.round(performance.now()-at)});}catch(e){results.push({name,status:'FAIL',error:e.stack,durationMs:Math.round(performance.now()-at)});}console.log(results.at(-1).status,name);await fs.writeFile(out+'/results.json',JSON.stringify({scope:'Pure synthetic validation/plans; all destructive browser recovery BLOCKED',results},null,2));}
const h=await history(2000),last=h.revisions.at(-1),resource={resourceKey:last.resourceKey,resourceType:last.resourceType,resourceId:last.resourceId,snapshot:structuredClone(last.snapshot)};resource.snapshot.page.title+=' next';
await check('O: per-resource limit blocks next normal authored edit with zero input mutation',async()=>{await validateHistory(h);const before=await sha256(stable(h));await assert.rejects(()=>advanceHistory(h,[resource],{source:'manual'}),/history is full/);assert.equal(await sha256(stable(h)),before);return {liveRevisions:2000};});
await check('O/X: 2000-revision archive verification and pure capacity projection',async()=>{const ws={...blankWorkspace(),history:h},start=performance.now(),a=await makeHistoryArchive(ws,provenance,()=>undefined,{retain:2}),generated=performance.now();await verifyHistoryArchive(a.bytes);const verified=performance.now();const p=await planCompaction(ws,a,[],[{...resource,snapshot:last.snapshot}]),planned=performance.now(),next=await advanceHistory(p.workspace.history,[resource],{source:'manual'});await validateHistory(next);assert.equal(next.heads[0].number,2001);assert.equal(next.revisions.length,3);assert.equal(a.revisions.length,1998);assert.equal(new Set([...a.revisions,...next.revisions].map(r=>r.revisionId)).size,2001);return {archiveBytes:a.bytes.length,generationMs:Math.round(generated-start),verificationMs:Math.round(verified-generated),purePlanMs:Math.round(planned-verified),...p.preview,revisionIds:undefined,reviewIds:undefined,assetKeys:undefined,scope:'No transaction executed; deletion disabled'};});
await check('O: total 25000-revision limit safely rejects the next edit',async()=>{const many=await history(25000);await validateHistory(many);const r=many.revisions.at(-1),target={resourceKey:r.resourceKey,resourceId:r.resourceId,resourceType:r.resourceType,snapshot:structuredClone(r.snapshot)};target.snapshot.page.title+=' next';await assert.rejects(()=>advanceHistory(many,[target],{source:'manual'}),/history is full/);assert.equal(many.revisions.length,25000);return {liveRevisions:25000,perResourceMaximum:2000};});
await check('O: review 500-row boundary is validated; row 501 is safely rejected',async()=>{const small=await history(1);small.reviews=Array.from({length:500},(_,i)=>({kind:'review',schemaVersion:1,id:'stress.review.'+i,status:'rejected',createdAt:1,decidedAt:2,plan:{schemaVersion:1,kind:'atlas-agent-changeset',id:'stress.review.'+i,source:'synthetic',createdAt:1,operations:[]}}));await validateHistory(small);small.reviews.push({...small.reviews[0],id:'stress.review.500',plan:{...small.reviews[0].plan,id:'stress.review.500'}});await assert.rejects(()=>validateHistory(small),/History count limit/);return {validated:500,rejected:501};});
await check('O: 64 MiB structured bound is unchanged and rejects overflow without pruning',async()=>{assert.equal(HISTORY_LIMITS.bytes,64*1024*1024);const oversized=await history(1);oversized.reviews=[{kind:'review',schemaVersion:1,id:'stress.bytes',status:'rejected',createdAt:1,decidedAt:2,plan:{schemaVersion:1,kind:'atlas-agent-changeset',id:'stress.bytes',operations:[]},reason:'x'.repeat(HISTORY_LIMITS.bytes)}];await assert.rejects(()=>validateHistory(oversized),/byte limit/);assert.equal(oversized.reviews[0].reason.length,HISTORY_LIMITS.bytes);return {scope:'Overflow short-circuit only; a valid near-byte-limit archive is NOT certified'};});
results.push({name:'O: actual committed recovery at every capacity boundary',status:'BLOCKED',reason:'No destructive compactor ships and no browser fault matrix passed. Only the per-resource pure plan was exercised; total/byte/review end-to-end recovery remains unverified.'});await fs.writeFile(out+'/results.json',JSON.stringify({scope:'Synthetic pure functions, not real IndexedDB',results},null,2));process.exitCode=results.some(r=>r.status==='FAIL')?1:2;
