import React,{useState} from '../vendor/react.mjs';
import {Modal} from '../components/Modal.js';
import {getAgentInterface} from './service.js';
import {ChangeList} from '../history/HistoryUI.js';
import {downloadJSON} from '../content-hub/content.js';
import type {Workspace} from '../core/model.js';
/** Human review is an ordinary UI operation. No provider, SDK or credential is
 * built into this surface and no endpoint silently accepts a plan. */
export function AgentReviewDialog({workspace,resourceKey,onClose}:{workspace:Workspace;resourceKey?:string;onClose:()=>void}){
 const api=getAgentInterface(),[text,setText]=useState(''),[preview,setPreview]=useState<any>(undefined),[selected,setSelected]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[includePersonal,setIncludePersonal]=useState(false),[reviewOffset,setReviewOffset]=useState(0),[activeId,setActiveId]=useState<string|undefined>(undefined);
 const reviews=api.getReviews(reviewOffset,25),active=workspace.history?.reviews.find(r=>r.id===activeId);
 const run=async(fn:()=>any)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 function inspect(value:unknown,ids?:string[]){const result=api.preview(value,ids);setPreview(result);setSelected(result.operations.map(o=>o.id));return result;}
 function loadReview(id:string){setError('');setActiveId(id);const row=workspace.history?.reviews.find(r=>r.id===id);if(!row)return;setText(JSON.stringify(row.plan,null,2));try{inspect(row.plan);}catch(e){setPreview(undefined);setError((e as Error).message);}}
 return <Modal title="Agent Review" onClose={onClose} wide><div className="agent-review"><p className="eyebrow">PROVIDER-NEUTRAL / REVIEW BEFORE APPLYING</p><p>Export bounded context to your chosen tool, then import its typed ChangeSet. Preview is read-only. Stage saves the proposal only; acceptance rechecks live revision identities and commits the selected operations together.</p><div className="button-row"><button onClick={()=>downloadJSON(api.getAgentCapabilities(),'atlasnote-agent-capabilities.json')}>Export capabilities</button><button onClick={()=>void run(()=>downloadJSON(api.getAgentContext({resourceKeys:resourceKey?[resourceKey]:[],includeHistory:true,includePersonal}),'atlasnote-agent-context.json'))}>Export context</button><label className="inline-check"><input type="checkbox" checked={includePersonal} onChange={e=>setIncludePersonal(e.target.checked)}/>Include personal excerpts</label></div><p className="secondary">{resourceKey??'No active resource selected; context contains workspace summary and capabilities only.'} No API key, provider request or remote fetch is performed.</p>
 <label className="field"><span>ChangeSet JSON</span><textarea aria-label="ChangeSet JSON" className="json-editor" rows={9} value={text} onChange={e=>{setText(e.target.value);setPreview(undefined);setActiveId(undefined);}} placeholder='{"schemaVersion":1,"kind":"atlas-agent-changeset",...}'/></label><div className="button-row"><label className="history-file">Import ChangeSet JSON<input type="file" accept=".json,application/json" aria-label="Import ChangeSet JSON" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{if(f.size>1024*1024)throw Error('ChangeSet exceeds 1 MiB');const value=await f.text();setText(value);setActiveId(undefined);inspect(value);});}}/></label><button disabled={busy||!text} onClick={()=>void run(()=>inspect(text))}>Preview ChangeSet</button><button disabled={busy||!preview||!!activeId} onClick={()=>void run(async()=>{await api.stage(preview.plan);setActiveId(preview.plan.id);})}>Stage for review</button></div>{error&&<p className="history-error" role="alert">{error}</p>}
 {preview&&<section aria-label="Proposed operations"><h2>{preview.plan.summary??'Proposed changes'}</h2><p>{preview.operations.length} operations. Changes below describe the full preview; use Preview selection to recalculate a subset before accepting.</p>{preview.plan.operations.map((op:any)=><label key={op.id} className="agent-operation" data-operation-id={op.id}><input type="checkbox" checked={selected.includes(op.id)} disabled={busy||active?.status==='accepted'||active?.status==='rejected'} onChange={e=>setSelected(ids=>e.target.checked?[...ids,op.id]:ids.filter(id=>id!==op.id))}/><span><strong>{op.kind}</strong><code>{op.resourceKey??'Personal / workspace state'}</code><small>{op.rationale}</small></span>{op.resourceKey&&op.baseRevisionId&&<button onClick={()=>void run(()=>api.compareRevisions(op.resourceKey,op.baseRevisionId))}>Open base / current</button>}</label>)}<div className="button-row"><button disabled={!selected.length||busy} onClick={()=>void run(()=>{const subset=api.preview(preview.plan,selected);setPreview({...subset,plan:preview.plan});})}>Preview selection</button></div>{preview.changes.map((change:any)=><details className="agent-change-group" key={change.resourceKey} open><summary>{change.resourceKey}</summary><ChangeList changes={change.entries??[]}/></details>)}{!preview.changes.length&&<p>No authored content will change; this is a draft, personal, semantic-reference or navigation proposal.</p>}</section>}
 {active&&<div className="agent-decision" data-review-id={active.id} data-review-status={active.status}><strong>{active.id} / {active.status}</strong>{active.reason&&<p role="status">{active.reason}</p>}<div className="button-row"><button className="primary" disabled={busy||active.status!=='staged'||!selected.length||!preview} onClick={()=>void run(async()=>{await api.accept(active.id,selected);setPreview(undefined);})}>Accept selected operations</button><button disabled={busy||!['staged','stale'].includes(active.status)} onClick={()=>void run(async()=>{await api.reject(active.id);setPreview(undefined);})}>Reject ChangeSet</button></div></div>}
 <section className="agent-audit"><h2>Review history</h2>{reviews.items.map(row=><button key={row.id} data-review-id={row.id} onClick={()=>loadReview(row.id)}><strong>{row.id}</strong><span>{row.status}</span><time>{new Date(row.createdAt).toLocaleString()}</time></button>)}{!reviews.total&&<p>No staged proposals. Only accepted content operations advance resource heads.</p>}<div className="button-row"><button disabled={!reviewOffset} onClick={()=>setReviewOffset(n=>Math.max(0,n-25))}>Newer reviews</button><button disabled={reviewOffset+25>=reviews.total} onClick={()=>setReviewOffset(n=>n+25)}>Older reviews</button></div></section></div></Modal>;
}
