import type {ResourceSnapshot,ResourceType} from '../history/model.js';
import type {ResourceTarget,ReadingDestination} from '../core/reading-types.js';
import type {StructuralOperation} from '../core/model.js';
import type {TaxonomyRef} from '../content-hub/model.js';
export type StateClass='revision'|'review'|'personal'|'workspace'|'semantic-reference'|'navigation';
export type OperationPayloads={
 'resource.create':{resourceType:ResourceType;snapshot:ResourceSnapshot};
 'resource.update':{resourceType:ResourceType;snapshot:ResourceSnapshot};
 'resource.draft':{resourceType:ResourceType;snapshot:ResourceSnapshot};
 'resource.restoreAsNewRevision':{revisionId:string};
 'taxonomy.assign':{taxonomy:TaxonomyRef|null};
 'notebook.tree.createNode':{operation:StructuralOperation};
 'notebook.tree.renameNode':{operation:StructuralOperation};
 'notebook.tree.moveNode':{operation:StructuralOperation;destinationBaseRevisionId?:string};
 'notebook.tree.reorderNode':{operation:StructuralOperation};
 'resource.link.add':{label:string;target:ResourceTarget};
 'resource.link.update':{index:number;label:string;target:ResourceTarget};
 'resource.link.remove':{index:number};
 'reference.add':{source:ResourceTarget;target:ResourceTarget;sourceRevision:string;targetRevision:string;kind:'link'|'context'|'related';label?:string;note?:string};
 'reference.remove':{id:string};
 'concept.assignment.propose':{batch:unknown};
 'concept.create':{id:string;subject:import('../content-hub/model.js').SubjectKey;label:string;aliases?:string[];parentId?:string;assignTo?:ResourceTarget;note?:string};
 'bookmark.add':{target:ResourceTarget;title:string};
 'bookmark.remove':{id:string};
 'readLater.add':{target:ResourceTarget;title:string};
 'readLater.remove':{id:string};
 'capture.create':{kind:'link'|'task'|'note';text:string;url?:string;taxonomy?:TaxonomyRef;target?:ResourceTarget};
 'capture.update':{id:string;text:string;status?:'inbox'|'open'|'done'|'archived';taxonomy?:TaxonomyRef};
 'workspace.navigate':{target:ResourceTarget;destination:ReadingDestination};
 'workspace.compare':{enabled:boolean;mode?:'changes'|'side-by-side'|'a'|'b';pane?:'A'|'B'};
 'pdf.metadata.update':{resourceType:'pdf';snapshot:ResourceSnapshot};
 'pdf.revision.propose':{resourceType:'pdf';snapshot:ResourceSnapshot};
};
export type AgentOperation={[K in keyof OperationPayloads]:{id:string;kind:K;resourceKey?:string;baseRevisionId?:string|null;baseFingerprint?:string;payload:OperationPayloads[K];rationale?:string}}[keyof OperationPayloads];
export type AgentChangeSet={schemaVersion:1;kind:'atlas-agent-changeset';id:string;createdAt:number;source:string;summary?:string;operations:AgentOperation[]};
export type AgentScope={resourceKeys?:string[];includePersonal?:boolean;includeHistory?:boolean};
