import {ID} from '../core/validation.mjs';
import {strictKeys,jsonSafe,HISTORY_LIMITS,validateResourceSnapshot} from '../history/validation.mjs';
import {validateReadingTarget} from '../storage/reading-validation.mjs';
import {validateTaxonomy} from '../content-hub/validation.mjs';
import {operationRegistry} from './registry.js';
import type {AgentChangeSet} from './model.js';
function text(v:any,max:number,label:string){if(typeof v!=='string'||!v.trim()||v.length>max)throw Error(label+' is required and bounded');}
/** This validates data only. Snippets are inert canonical content, never execution. */
export function validateChangeSet(input:unknown):AgentChangeSet {
 const data=typeof input==='string'?(new TextEncoder().encode(input).length<=HISTORY_LIMITS.changeSetBytes?JSON.parse(input):(()=>{throw Error('ChangeSet exceeds 1 MiB');})()):input;jsonSafe(data);const p=data as AgentChangeSet;
 strictKeys(p,['schemaVersion','kind','id','createdAt','source','summary','operations'],'ChangeSet');if(p.schemaVersion!==1||p.kind!=='atlas-agent-changeset')throw Error('Unsupported ChangeSet schema');if(typeof p.id!=='string'||!ID.test(p.id))throw Error('Invalid ChangeSet ID');if(!Number.isSafeInteger(p.createdAt)||p.createdAt<0||p.createdAt>8640000000000000)throw Error('Invalid ChangeSet timestamp');text(p.source,200,'Source');if(p.summary!==undefined)text(p.summary,2000,'Summary');
 if(!Array.isArray(p.operations)||p.operations.length<1||p.operations.length>HISTORY_LIMITS.operations)throw Error('Select 1-50 bounded operations');const ids=new Set();
 const unsafe=(v:any,key='')=>{if(typeof v==='string'){if(/<\s*(?:script|iframe|object|embed|style|link|meta)\b|\bon\w+\s*=\s*["']/i.test(v))throw Error('Active HTML is not allowed in an agent proposal');if(['url','src','sourceUrl'].includes(key)&&/^(?:javascript|data|file|vbscript):/i.test(v))throw Error('Unsafe agent URL');}else if(v&&typeof v==='object')for(const [k,x]of Object.entries(v))unsafe(x,k);};unsafe(p);
 for(const op of p.operations){strictKeys(op,['id','kind','resourceKey','baseRevisionId','baseFingerprint','payload','rationale'],'operation');if(typeof op.id!=='string'||!ID.test(op.id)||ids.has(op.id))throw Error('Invalid/duplicate operation ID');ids.add(op.id);const def=operationRegistry[op.kind];if(!def)throw Error('Unsupported or forbidden agent operation: '+op.kind);strictKeys(op.payload,def.payloadFields,'payload '+op.kind);for(const k of def.required)if(!Object.hasOwn(op.payload,k))throw Error('Missing payload field '+k);const payload:any=op.payload;
  if(op.rationale!==undefined)text(op.rationale,2000,'Rationale');
  if(def.base==='revision'||def.base==='new'){if(typeof op.resourceKey!=='string'||!/^[-a-z]+:[A-Za-z0-9][A-Za-z0-9._-]{0,119}$/.test(op.resourceKey))throw Error('Exact resourceKey required');if(def.base==='new'){if(op.baseRevisionId!==null)throw Error('Create requires explicit null base revision');}else if(typeof op.baseRevisionId!=='string'||!ID.test(op.baseRevisionId))throw Error('Exact baseRevisionId required');}
  else if(typeof op.baseFingerprint!=='string'||!/^[a-f0-9]{16}$/.test(op.baseFingerprint))throw Error('Exact state baseFingerprint required');
  if(Object.hasOwn(payload,'snapshot')){validateResourceSnapshot(payload.resourceType,payload.snapshot);if(!def.resourceTypes.includes(payload.resourceType))throw Error('Unsupported action/resource combination');const id=payload.snapshot.document?.id??payload.snapshot.page?.id??payload.snapshot.project?.id;if(op.resourceKey!==payload.resourceType+':'+id)throw Error('Operation/snapshot identity mismatch');}
  for(const k of ['target','source'])if(payload[k])validateReadingTarget(payload[k]);if(payload.taxonomy!==undefined&&!(op.kind==='taxonomy.assign'&&payload.taxonomy===null))validateTaxonomy(payload.taxonomy);
  if(Object.hasOwn(payload,'operation')){strictKeys(payload.operation,['kind','nodeId','projectId','parentId','node','title','delta'],'Notebook operation');const expected={'notebook.tree.createNode':'add','notebook.tree.renameNode':'rename','notebook.tree.moveNode':'move','notebook.tree.reorderNode':'order'}[op.kind];if(payload.operation.kind!==expected||typeof payload.operation.nodeId!=='string'||!ID.test(payload.operation.nodeId))throw Error('Notebook operation kind/identity mismatch');if(['add','move'].includes(expected??'')&&(typeof payload.operation.projectId!=='string'||!ID.test(payload.operation.projectId)))throw Error('Notebook destination project required');if(payload.operation.parentId!==undefined&&(typeof payload.operation.parentId!=='string'||!ID.test(payload.operation.parentId)))throw Error('Invalid Notebook destination folder');if(expected==='add'&&(!payload.operation.node||payload.operation.node.id!==payload.operation.nodeId))throw Error('New Notebook node identity mismatch');if(expected==='rename'&&!Object.hasOwn(payload.operation,'title'))throw Error('Notebook rename requires title');if(expected==='order'&&!Object.hasOwn(payload.operation,'delta'))throw Error('Notebook reorder requires delta');if(payload.operation.title!==undefined)text(payload.operation.title,200,'Node title');if(payload.operation.delta!==undefined&&(!Number.isSafeInteger(payload.operation.delta)||Math.abs(payload.operation.delta)>10000))throw Error('Invalid Notebook reorder delta');}
  if(op.kind==='workspace.navigate'&&!['here','tab','pane',1,2,3,4,5].includes(payload.destination))throw Error('Invalid ReadingDestination');if(op.kind==='workspace.compare'&&(typeof payload.enabled!=='boolean'||payload.mode!==undefined&&!['changes','side-by-side','a','b'].includes(payload.mode)||payload.pane!==undefined&&!['A','B'].includes(payload.pane)))throw Error('Invalid Compare proposal');
  if(payload.revisionId!==undefined&&(typeof payload.revisionId!=='string'||!ID.test(payload.revisionId)))throw Error('Invalid historical revision ID');if(payload.destinationBaseRevisionId!==undefined&&(typeof payload.destinationBaseRevisionId!=='string'||!ID.test(payload.destinationBaseRevisionId)))throw Error('Invalid destination base revision');if(payload.status!==undefined&&!['inbox','open','done','archived'].includes(payload.status))throw Error('Invalid capture status');
  if(payload.title!==undefined)text(payload.title,500,'Title');if(payload.label!==undefined)text(payload.label,200,'Label');if(payload.text!==undefined)text(payload.text,100000,'Text');if(payload.note!==undefined)text(payload.note,2000,'Note');if(payload.id!==undefined&&(typeof payload.id!=='string'||!ID.test(payload.id)))throw Error('Invalid payload ID');if(op.kind==='reference.add'&&(!/^[a-f0-9]{16}$/.test(payload.sourceRevision)||!/^[a-f0-9]{16}$/.test(payload.targetRevision)))throw Error('Exact source/target semantic revision required');if(op.kind==='reference.add'&&!['link','context','related'].includes(payload.kind))throw Error('Unsupported semantic reference kind');if(op.kind==='capture.create'&&!['link','task','note'].includes(payload.kind))throw Error('Unsupported capture kind');
  if(payload.index!==undefined&&(!Number.isSafeInteger(payload.index)||payload.index<0||payload.index>49))throw Error('Invalid link index');
 }
 return structuredClone(p);
}
