import React,{useEffect,useRef,useState} from '../vendor/react.mjs';
import type {Block,Page,View} from '../core/model.js';
import {visibleTableColumns,tableOptionsKey,tableChoiceKey,tableLayout,tableChoice,tableFields,organizeTableRows,TABLE_LAYOUTS,TABLE_PALETTES} from './table-columns.js';
import {Inline,parseMarkdown} from './markdown.js';import {Icon} from '../components/Icon.js';import {safeUrl} from '../core/validation.mjs';
let mermaidPromise:Promise<any>|null=null;let mermaidQueue=Promise.resolve();
export function Mermaid({code,onReady}:any){const [svg,setSvg]=useState(''),[error,setError]=useState('');const id=useRef('mermaid-'+crypto.randomUUID().replaceAll('-',''));useEffect(()=>{let alive=true;if(!mermaidPromise)mermaidPromise=import('../vendor/mermaid-loader.mjs').then(m=>{m.default.initialize({startOnLoad:false,securityLevel:'strict',suppressErrorRendering:true,theme:'neutral',flowchart:{htmlLabels:false},fontFamily:'Arial, sans-serif',maxTextSize:50000});return m.default;});mermaidQueue=mermaidQueue.catch(()=>{}).then(async()=>{try{if(code.length>50000)throw Error('Diagram exceeds the size limit');if(/%%\{\s*(init|config)\s*:/i.test(code))throw Error('Embedded renderer configuration is not allowed');const m=await mermaidPromise;const r=await m.render(id.current,code);if(alive){setSvg(r.svg);setTimeout(()=>onReady?.(),30);}}catch(e){if(alive)setError((e as Error).message);}});return()=>{alive=false;};},[code]);return error?<div className="render-error"><strong>Diagram could not be rendered</strong><p>{error}</p><pre>{code}</pre></div>:svg?<div className="mermaid-figure" data-mermaid-ready="true" dangerouslySetInnerHTML={{__html:svg}}/>:<div className="diagram-loading">Rendering diagram...</div>;}
export function Code({code,language,title,id}:any){const lang=String(language||'text').toLowerCase(),grammar=window.Prism?.languages[lang];return <div className="code-block"><div className="code-header"><span>{title||lang}</span><button data-action="copy-code" data-block={id} data-snippet={code} title="Copy whole code snippet"><Icon name="copy" size={14}/> Copy</button></div><pre><code className={'language-'+lang}>{String(code).split('\n').map((line,i)=>grammar?<span className="code-line" key={i} dangerouslySetInnerHTML={{__html:window.Prism.highlight(line||' ',grammar,lang)}}/>:<span className="code-line" key={i}>{line||' '}</span>)}</code></pre></div>;}
function Table({columns,rows,page,view,id,print=false}:any){
 const interactive=page?.tags.includes('csv-table')&&id&&!print,visible=interactive?visibleTableColumns(page.id,columns,view.revealed):columns.map((_:string,i:number)=>i),open=interactive&&view.revealed[tableOptionsKey(page.id,id)],layout=interactive?tableLayout(page.id,view.revealed):'table';
 const fields=tableFields(columns),sort=interactive?tableChoice(page.id,view.revealed,'sort'):'source',group=interactive?tableChoice(page.id,view.revealed,'group'):'none',organizeOpen=interactive&&view.revealed[tableChoiceKey(page.id,'menu','organize')],groups=organizeTableRows(columns,rows,sort,group);
 const layouts={table:'Table',pairs:'NO / EN',lines:'Lines',cards2:'2 columns',cards3:'3 columns',dictionary:'Dictionary',tiles:'Tiles'};
 const palette=interactive?tableChoice(page.id,view.revealed,'palette'):'black',palettes={black:'Black',ocean:'Ocean',forest:'Forest',paper:'Warm paper'},paletteOpen=interactive&&view.revealed[tableChoiceKey(page.id,'menu','palette')];
 const presets=[['compact','Reading'],['alphabet','Alphabet'],...(fields.category>=0||fields.type>=0?[['themes','Categories']]:[]),...(fields.relations.length?[['relations','Synonyms / opposites']]:[]),...(fields.grammar.length?[['grammar','Grammar']]:[])];
 return <div data-csv-palette={interactive?palette:undefined} className={'table-wrap csv-layout-'+layout+(interactive?' csv-interactive':'')}>
  {interactive&&<div className="table-column-tools">
   <button className="text-button" data-action="table-options" data-block={id} aria-expanded={!!open}>Columns</button>
   <div role="group" aria-label="Table reading layout">{TABLE_LAYOUTS.map(mode=><button key={mode} className="text-button" data-action="table-layout" data-block={id} data-snippet={mode} aria-pressed={layout===mode}>{layouts[mode]}</button>)}</div>
   <button className="text-button" data-action="table-organize" data-block={id} aria-expanded={!!organizeOpen}>Views & sort</button>
   <button className="text-button" data-action="table-colors" data-block={id} aria-expanded={!!paletteOpen}>Colors</button>
   {paletteOpen&&<div role="group" aria-label="Table color palette">{TABLE_PALETTES.map(mode=><button key={mode} className="text-button csv-color-choice" data-action="table-palette" data-block={id} data-snippet={mode} aria-pressed={palette===mode}><span aria-hidden="true" className={'csv-swatch csv-swatch-'+mode}/>{palettes[mode]}</button>)}</div>}
   {open&&<div role="group" aria-label="Visible table columns">{columns.map((c:string,i:number)=><button key={i} className="text-button" data-action="table-column" data-block={id} data-snippet={String(i)} aria-pressed={visible.includes(i)} disabled={visible.length===1&&visible.includes(i)}>{c}</button>)}</div>}
   {organizeOpen&&<div className="table-organization">
    <div role="group" aria-label="Ready-made table views"><span>Views</span>{presets.map(([mode,label])=><button key={mode} className="text-button" data-action="table-preset" data-block={id} data-snippet={mode}>{label}</button>)}</div>
    <div role="group" aria-label="Sort this page"><span>Sort this page</span>{[['source','Original'],['norsk','Norsk A–Z'],['english','English A–Z'],['reverse','Norsk Z–A']].map(([mode,label])=><button key={mode} className="text-button" data-action="table-sort" data-block={id} data-snippet={mode} aria-pressed={sort===mode}>{label}</button>)}</div>
    <div role="group" aria-label="Group this page"><span>Group</span>{[['none','None'],['letter','A · B · C'],...(fields.category>=0?[['category','Theme']]:[]),...(fields.type>=0?[['type','Word class']]:[])].map(([mode,label])=><button key={mode} className="text-button" data-action="table-group" data-block={id} data-snippet={mode} aria-pressed={group===mode}>{label}</button>)}</div>
    <small>Reading preferences for this page. Empty synonyms or opposites stay empty.</small>
   </div>}
  </div>}
  <table><thead><tr>{visible.map((i:number)=><th key={i}><Inline text={columns[i]}/></th>)}</tr></thead><tbody>{groups.flatMap(g=>[
   ...(g.title?[<tr className="csv-group-row" key={'group-'+g.title}><th colSpan={visible.length} scope="rowgroup">{g.title}</th></tr>]:[]),
   ...g.items.map(({row,index})=><tr key={index} data-source-row={index}>{visible.map((j:number)=><td key={j} data-column={j} data-label={columns[j]}><Inline text={row[j]??''}/></td>)}</tr>)
  ])}</tbody></table>
 </div>;
}
function List({items,ordered=false}:any){const Tag=ordered?'ol':'ul';return <Tag>{items.map((s:string,i:number)=><li key={i}><Inline text={s}/></li>)}</Tag>;}
export function Source({source}:any){return <span className="provenance">Source: {source?.url&&safeUrl(source.url)?<a href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a>:source?.title}{source?.publisher?' - '+source.publisher:''}{source?.note?' - '+source.note:''}</span>;}
function ImageFigure({block,url,onReady}:any){const remote=safeUrl(block.src),[load,setLoad]=useState(!remote),[failed,setFailed]=useState(false);return <figure>{remote&&!load?<div className="external-placeholder"><Icon name="link"/><p>Official/reference image hosted externally. Loading contacts the source website.</p><button onClick={()=>setLoad(true)} data-action="load-image" data-block={block.id}>Load reference image</button></div>:failed||!url?<div className="render-error">Image unavailable. The source reference is retained.</div>:<img src={url} alt={block.alt??block.caption} loading="eager" referrerPolicy="no-referrer" onLoad={onReady} onError={()=>setFailed(true)}/>}<figcaption><Inline text={block.caption}/><Source source={block.source}/></figcaption><button className="text-button" data-action="enlarge" data-block={block.id}>Open figure</button></figure>;}
export function ContentUnits({page,view,resolveAsset,onReady,print=false}: {page:Page;view:View;resolveAsset:(path:string,page:Page)=>string|undefined;onReady?:()=>void;print?:boolean}){
 const nodes:any[]=[];let serial=0;
 function unit(b:Block,kind:string,content:any,index=0,offset=0){const key=b.id+'.'+index;nodes.push(<div key={key} className={'content-unit unit-'+kind} data-block-id={b.id} data-unit={key} data-offset={offset} data-kind={kind} data-keep-next={b.layout?.keepWithNext||undefined} data-break-before={b.layout?.pageBreakBefore||undefined}>{content}</div>);}
 function walk(blocks:Block[],depth=0){for(const b of blocks){switch(b.type){case 'section':{const collapsed=!print&&(view.collapsed[b.id]??b.collapsed??false),Tag=depth===0?'h2':'h3';unit(b,'heading',<Tag><button className="section-toggle" data-action="section" data-block={b.id} aria-expanded={!collapsed}><Icon name={collapsed?'chevron':'down'} size={16}/><span>{b.title}</span></button></Tag>);if(!collapsed)walk(b.children,depth+1);break;}
 case 'markdown':{let offset=0;parseMarkdown(b.text).forEach((p,i)=>{let content:any;if(p.kind==='paragraph')content=<p><Inline text={p.text!}/></p>;else if(p.kind==='heading'){const Tag=p.level!<=2?'h3':'h4';content=<Tag><Inline text={p.text!}/></Tag>;}else if(p.kind==='code')content=<Code code={p.text} language={p.language} id={b.id}/>;else if(p.kind==='table')content=<Table columns={p.columns} rows={p.rows}/>;else content=<List items={p.items} ordered={p.ordered}/>;unit(b,p.kind,content,i,offset);offset+=(p.text?.length??p.items?.length??p.rows?.length??0)+1;});break;}
 case 'callout':unit(b,'callout',<aside className={'callout '+(b.tone??'info')}><strong>{b.title}</strong><p><Inline text={b.text}/></p></aside>);break;
 case 'list':unit(b,'list',<List items={b.items} ordered={b.ordered}/>);break;
 case 'table':unit(b,'table',<Table columns={b.columns} rows={b.rows} page={page} view={view} id={b.id} print={print}/>);break;
 case 'code':unit(b,'code',<Code code={b.code} language={b.language} title={b.title} id={b.id}/>);if(b.explanation)unit(b,'paragraph',<p className="code-explanation"><Inline text={b.explanation}/></p>,1);if(b.output)unit(b,'code',<Code code={b.output} title="Expected output - not executed" language="text" id={b.id}/>,2);break;
 case 'bilingual':unit(b,'bilingual',<div className={'bilingual '+(!view.english?'no-english':'')}><div className="language-cell" lang="nb"><span className="language-label">NO</span><p><Inline text={b.no}/></p></div>{view.english&&<div className="language-cell english" lang="en"><span className="language-label">EN</span><p><Inline text={b.en}/></p></div>}{b.hint&&<small className="language-hint">{b.hint}</small>}</div>);break;
 case 'question':{const visible=!!view.revealed[b.id];unit(b,'question',<div className="question"><div className="eyebrow">REFLECT</div><strong><Inline text={b.question}/></strong>{!print&&<button className="text-button" data-action="answer" data-block={b.id} aria-expanded={visible}>{visible?'Hide answer':'Reveal answer'}</button>}{visible&&<div className="answer"><Inline text={b.answer}/>{b.followUp&&<p><strong>Follow-up:</strong> {b.followUp}</p>}</div>}</div>);break;}
 case 'image':unit(b,'figure',<ImageFigure block={b} url={resolveAsset(b.src,page)} onReady={onReady}/>);break;
 case 'diagram':unit(b,'figure',b.format==='mermaid'&&b.code?<figure><Mermaid code={b.code} onReady={onReady}/><figcaption><Inline text={b.caption}/><Source source={b.source}/></figcaption><button className="text-button" data-action="enlarge" data-block={b.id}>Open figure</button></figure>:<ImageFigure block={{...b,src:b.src,alt:b.caption}} url={b.src?resolveAsset(b.src,page):undefined} onReady={onReady}/>);break;
 case 'link':unit(b,'link',<a className="linked-card" href={'#/page/'+encodeURIComponent(b.pageId)} data-page={b.pageId}><Icon name="link"/><span><strong>{b.label??b.pageId}</strong>{b.description&&<small>{b.description}</small>}</span><Icon name="right" size={15}/></a>);break;
 case 'resource-link':unit(b,'link',<div className="resource-linked-card">{b.target.kind==='url'?<a href={b.target.url} target="_blank" rel="noopener noreferrer">{b.label}</a>:<button className="linked-card" data-action="resource-link" data-block={b.id}><Icon name="link"/><span><strong>{b.label}</strong><small>{b.target.kind}{b.description?' / '+b.description:''}</small></span></button>}<button data-action="resource-actions" data-block={b.id} aria-label={'Actions for '+b.label}>...</button></div>);break;
 case 'separator':unit(b,'separator',<hr/>);break;
 case 'page_break':unit(b,'page_break',<div className="page-break-label">Page break</div>);break;
 default:unit(b,'paragraph',<p className="render-error">Unsupported block retained. Export the source to recover it.</p>);
 }serial++;}}
 walk(page.blocks);return <>{nodes}</>;
}
