import React,{useState,useMemo,useEffect} from '../vendor/react.mjs';
import type {Catalogue,Workspace} from '../core/model.js';
import type {ResourceTarget} from '../core/reading-types.js';
import type {Concept,SuggestionBatch} from './model.js';
import {Modal} from '../components/Modal.js';
import {ResourcePicker} from '../content-hub/ResourcePicker.js';
import {downloadJSON} from '../content-hub/content.js';
import {SUBJECTS} from '../content-hub/model.js';
import {store} from '../storage/database.js';
import {uid} from '../core/workspace.js';
import {knowledgeOf,saveConcept,deprecateConcept,removeConcept,assignConcept,unassignConcept,linkReference,unlinkReference,markReviewed,createReferenceIndex,reviewQueue} from './knowledge.js';
import {targetKey,resolveTarget} from './targets.js';
import {referenceReviewExport,referenceReviewMarkdown,previewSuggestions,stageSuggestions,decideSuggestions,discardCompletedReviews} from './review.js';
export function KnowledgeEditor({catalogue:c,workspace:ws,target,onClose,notify}:{catalogue:Catalogue;workspace:Workspace;target?:ResourceTarget;onClose:()=>void;notify:(message:string,error?:boolean)=>void}){
 const k=knowledgeOf(ws.personal),[tab,setTab]=useState('links'),[source,setSource]=useState<ResourceTarget|undefined>(target),[destination,setDestination]=useState<ResourceTarget|undefined>(undefined),[label,setLabel]=useState(''),[note,setNote]=useState(''),[kind,setKind]=useState<'link'|'context'|'related'>('link'),[conceptId,setConceptId]=useState(''),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const [edit,setEdit]=useState(''),[conceptLabel,setConceptLabel]=useState(''),[subject,setSubject]=useState<Concept['subject']>('it'),[aliases,setAliases]=useState(''),[parent,setParent]=useState('concept.it'),[related,setRelated]=useState<string[]>([]),[replacement,setReplacement]=useState('');
 const [importText,setImportText]=useState(''),[preview,setPreview]=useState<SuggestionBatch|null>(null),[selected,setSelected]=useState<string[]>([]),[exportKeys,setExportKeys]=useState<string[]>(target?[targetKey(c,target)]:[]),[queueText,setQueueText]=useState(''),[queueLimit,setQueueLimit]=useState(20);
 useEffect(()=>{setExportKeys(source?[targetKey(c,source)]:[]);},[source?targetKey(c,source):'']);
 const index=useMemo(()=>createReferenceIndex(c,ws),[c,ws.personal.knowledge,ws.personal.dashboardItems,ws.overlays]);
 const queue=useMemo(()=>reviewQueue(c,ws,index),[c,index]);
 const exportable=useMemo(()=>{const rows=[...(source?[resolveTarget(c,ws,source)]:[]),...queue],seen=new Set<string>();return rows.filter(r=>{if(seen.has(r.key)||!r.exact||!r.available)return false;seen.add(r.key);return true;});},[c,index,source?targetKey(c,source):'']);
 async function run(fn:(p:import('../core/model.js').Personal)=>void,message:string){setError('');setSuccess('');try{await store.personal(fn);setSuccess(message);notify(message);}catch(e){setError((e as Error).message);}}
 function loadConcept(id:string){setEdit(id);const c=k.concepts.find(c=>c.id===id);setConceptLabel(c?.label??'');setSubject(c?.subject??'it');setAliases(c?.aliases.join('\n')??'');setParent(c?.primaryParentId??(id?'':'concept.it'));setRelated(c?.relatedConceptIds??[]);setReplacement(c?.replacedById??'');setError('');}
 function save(){const old=k.concepts.find(c=>c.id===edit);const id=old?.id??uid('concept');const data={id,label:conceptLabel,subject,aliases:aliases.split(/[\n,]/).map(x=>x.trim()).filter(Boolean),relatedConceptIds:related,...(parent?{primaryParentId:parent}:{}),...(old?.deprecated?{deprecated:true}:{}),...(old?.replacedById?{replacedById:old.replacedById}:{})};void run(p=>{saveConcept(p,data);},'Concept saved without changing Notebook folders.').then(()=>{if(store.state.personal.knowledge?.concepts.some(c=>c.id===id))setEdit(id);});}
 const selectedResource=source?resolveTarget(c,ws,source):undefined;
 const assignments=source?k.assignments.filter(a=>targetKey(c,a.target)===targetKey(c,source)):[],edges=source?k.edges.filter(e=>targetKey(c,e.source)===targetKey(c,source)):[];
 function exportReview(markdown=false){try{const chosen=exportable.filter(r=>exportKeys.includes(r.key)).map(r=>r.target),value=referenceReviewExport(c,store.state,chosen);if(!markdown)downloadJSON(value,'atlas-reference-review.json');else {const url=URL.createObjectURL(new Blob([referenceReviewMarkdown(value)],{type:'text/markdown'})),a=document.createElement('a');a.href=url;a.download='atlas-reference-review.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}setSuccess('Review package downloaded locally. No AI request was sent.');}catch(e){setError((e as Error).message);}}
 function prepare(){setError('');setPreview(null);try{const next=previewSuggestions(c,store.state,importText);setPreview(next);setSuccess('Validated preview. No concepts or references have changed.');}catch(e){setError((e as Error).message);}}
 const stale=(p:typeof k.proposals[number])=>p.semanticRevision!==k.revision||resolveTarget(c,ws,p.target).revision!==p.targetRevision||!!p.source&&resolveTarget(c,ws,p.source).revision!==p.sourceRevision;
 return <Modal title="Knowledge references" onClose={onClose} wide><div className="knowledge-editor">
 <p className="secondary">Local semantic index / revision {k.revision}. It does not own your Notebook folders.</p>
 <div className="dialog-tabs">{[['links','Exact links'],['concepts','Concept Index'],['review','Review & AI handoff']].map(([id,title])=><button key={id} aria-pressed={tab===id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{title}</button>)}</div>
 {error&&<p className="error-message" role="alert">{error}</p>}{success&&<p role="status">{success}</p>}
 {tab==='links'&&<>
 <div className="reference-scope"><strong>{selectedResource?.title??'Choose the source resource'}</strong><span>{selectedResource?.detail??'No exact target selected'}</span>{selectedResource?.warning&&<p role="alert">{selectedResource.warning}</p>}</div>
 <details><summary>Choose a different source / exact section</summary><ResourcePicker catalogue={c} workspace={ws} onChange={t=>{if(t)setSource(t);}}/></details>
 <section><h3>Concept assignments</h3><label>Concept<select aria-label="Concept to link" value={conceptId} onChange={e=>setConceptId(e.target.value)}><option value="">Choose a concept</option>{k.concepts.filter(c=>!c.deprecated).map(c=><option key={c.id} value={c.id}>{c.label} / {c.subject}</option>)}</select></label><label>Reference note<textarea aria-label="Reference note" rows={2} value={note} onChange={e=>setNote(e.target.value)} maxLength={2000}/></label><button disabled={!source||!conceptId} onClick={()=>void run(p=>{assignConcept(p,c,store.state,conceptId,source!,note);},'Concept linked to the exact resource.')}>Link concept to this target</button><button className="text-button" onClick={()=>{loadConcept('');setTab('concepts');}}>Create a concept</button>
 {assignments.map(a=><div className="knowledge-record" key={a.id}><span>{k.concepts.find(c=>c.id===a.conceptId)?.label??a.conceptId}{a.targetRevision!==selectedResource?.revision?' / content changed':''}</span><button aria-label={'Remove concept assignment '+a.id} onClick={()=>void run(p=>unassignConcept(p,a.id),'Assignment removed. Source content unchanged.')}>Unlink</button></div>)}
 </section><section><h3>Explicit reference from this target</h3><ResourcePicker catalogue={c} workspace={ws} onChange={(t,l)=>{setDestination(t);setLabel(l);}}/>
 <label>Link label<input aria-label="Reference label" value={label} maxLength={200} onChange={e=>setLabel(e.target.value)}/></label><label>Relationship kind<select aria-label="Reference relationship" value={kind} onChange={e=>setKind(e.target.value)}><option value="link">Link</option><option value="related">Related</option><option value="context">Context</option></select></label>
 <button disabled={!source||!destination} onClick={()=>void run(p=>{linkReference(p,c,store.state,source!,destination!,kind,label,note);},'Exact reference added. Its backlink is derived automatically.')}>Add exact reference</button>
 {edges.map(e=><div className="knowledge-record" key={e.id}><span>{resolveTarget(c,ws,e.target).title} / {resolveTarget(c,ws,e.target).detail} / {e.kind}</span><button onClick={()=>void run(p=>unlinkReference(p,e.id),'Reference removed without deleting either resource.')}>Remove link</button></div>)}
 </section><button disabled={!source} onClick={()=>void run(p=>markReviewed(p,c,store.state,source!),'Current source revision marked reviewed.')}>Mark this target reviewed</button>
 </>}
 {tab==='concepts'&&<div className="concept-editor-layout"><div><h3>Stable Concept Index</h3><button onClick={()=>loadConcept('')}>New concept</button><label>Find / edit concept<select aria-label="Edit concept" value={edit} onChange={e=>loadConcept(e.target.value)}><option value="">New concept</option>{k.concepts.map(c=><option key={c.id} value={c.id}>{c.label} / {c.subject}{c.deprecated?' / deprecated':''}</option>)}</select></label><p className="secondary">Renaming or reparenting retains this stable ID. Related concepts do not change the primary parent.</p>{edit&&<code>{edit}</code>}</div><div>
 <label>Label<input aria-label="Concept label" value={conceptLabel} maxLength={160} onChange={e=>setConceptLabel(e.target.value)}/></label><label>Subject<select aria-label="Concept subject" value={subject} onChange={e=>{setSubject(e.target.value);setParent('concept.'+e.target.value);}}>{SUBJECTS.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>
 <label>Primary parent<select aria-label="Concept parent" value={parent} onChange={e=>setParent(e.target.value)}><option value="">No primary parent</option>{k.concepts.filter(c=>c.subject===subject&&c.id!==edit&&!c.deprecated).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>
 <label>Aliases (one per line)<textarea aria-label="Concept aliases" rows={3} value={aliases} onChange={e=>setAliases(e.target.value)}/></label><details><summary>Related concepts ({related.length})</summary><div className="related-concept-options">{k.concepts.filter(c=>c.id!==edit&&!c.deprecated).map(c=><label className="inline-check" key={c.id}><input type="checkbox" checked={related.includes(c.id)} onChange={e=>setRelated(e.target.checked?[...related,c.id]:related.filter(id=>id!==c.id))}/>{c.label}</label>)}</div></details><button className="primary" disabled={!conceptLabel.trim()} onClick={save}>Save concept</button>
 {edit&&<details><summary>Deprecate / safe removal</summary><label>Replacement concept<select aria-label="Replacement concept" value={replacement} onChange={e=>setReplacement(e.target.value)}><option value="">Keep deprecated without replacement</option>{k.concepts.filter(c=>c.id!==edit&&!c.deprecated).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label><button onClick={()=>void run(p=>{deprecateConcept(p,edit,replacement||undefined);},'Concept deprecated; existing links and aliases are preserved.')}>Deprecate, preserve links</button><button onClick={()=>void run(p=>removeConcept(p,edit),'Unlinked concept removed.').then(()=>{if(!store.state.personal.knowledge?.concepts.some(c=>c.id===edit))loadConcept('');})}>Remove only if unlinked</button></details>}
 </div></div>}
 {tab==='review'&&<>
 <h3>Needs reference review</h3><p>Select up to 50 exact targets. Exports include source fingerprints, snippets and concept revision {k.revision}, not complete private libraries.</p><input aria-label="Search reference review resources" value={queueText} onChange={e=>setQueueText(e.target.value)} placeholder="Filter titles and sections"/>
 <div className="review-targets">{exportable.filter(r=>(r.title+' '+r.detail).toLocaleLowerCase().includes(queueText.toLocaleLowerCase())).slice(0,queueLimit).map(r=><label className="inline-check" key={r.key}><input type="checkbox" checked={exportKeys.includes(r.key)} onChange={e=>setExportKeys(e.target.checked?[...exportKeys,r.key]:exportKeys.filter(k=>k!==r.key))}/><span>{r.title}<small>{r.group} / {r.detail||'Document'}</small></span></label>)}</div>{queueLimit<exportable.length&&<button onClick={()=>setQueueLimit(x=>x+30)}>Show more review resources</button>}
 <div className="button-row"><button onClick={()=>exportReview()}>Export reference review JSON</button><button onClick={()=>exportReview(true)}>Export reference review Markdown</button></div>
 <h3>Import suggestions for review</h3><p>No automatic AI calls. Import is validated atomically; stale revisions, missing targets and unknown concepts are rejected.</p>
 <label>Suggestion JSON file<input aria-label="Reference suggestion file" type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>512*1024){setError('Suggestion file exceeds 512 KiB.');return;}setImportText(await f.text());setPreview(null);}}/></label>
 <label>Suggestion JSON<textarea className="json-editor" aria-label="Reference suggestion JSON" value={importText} rows={8} onChange={e=>{setImportText(e.target.value);setPreview(null);}}/></label><button onClick={prepare}>Preview suggestions</button>
 {preview&&<section className="suggestion-preview" aria-label="Validated reference suggestions"><strong>{preview.suggestions.length} valid suggestions / revision {preview.semanticRevision}</strong>{preview.suggestions.map(s=><p key={s.id}>{s.type==='assignment'?'Concept '+k.concepts.find(c=>c.id===s.conceptId)?.label:'Reference'} → {resolveTarget(c,ws,s.target).title} / {resolveTarget(c,ws,s.target).detail}<small>{s.reason}</small></p>)}<button onClick={()=>void run(p=>stageSuggestions(p,c,store.state,preview),'Suggestions staged. Review and accept selected rows explicitly.').then(()=>setPreview(null))}>Stage validated suggestions</button></section>}
 <h3>Review decisions</h3>{k.proposals.map(p=><div key={p.id} className="suggestion-row" data-suggestion-id={p.id}><label className="inline-check"><input type="checkbox" disabled={p.status!=='proposed'} checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/><span>{p.type==='assignment'?k.concepts.find(c=>c.id===p.conceptId)?.label:'Explicit reference'} → {resolveTarget(c,ws,p.target).title}<small>{resolveTarget(c,ws,p.target).detail}</small><small>{p.reason} {p.confidence!==undefined?' / confidence '+p.confidence:''}</small><strong>{p.status}{p.status==='proposed'&&stale(p)?' / stale, export again':''}</strong></span></label>{p.status==='proposed'&&<div className="button-row"><button disabled={stale(p)} onClick={()=>void run(personal=>decideSuggestions(personal,c,store.state,[p.id],'accept'),'Suggestion accepted.')}>Accept</button><button onClick={()=>void run(personal=>decideSuggestions(personal,c,store.state,[p.id],'reject'),'Suggestion rejected; content unchanged.')}>Reject</button></div>}</div>)}
 <div className="button-row"><button disabled={!selected.length} onClick={()=>void run(p=>decideSuggestions(p,c,store.state,selected,'accept'),'Selected suggestions accepted atomically.').then(()=>setSelected([]))}>Accept selected</button><button disabled={!selected.length} onClick={()=>void run(p=>decideSuggestions(p,c,store.state,selected,'reject'),'Selected suggestions rejected.').then(()=>setSelected([]))}>Reject selected</button></div><details><summary>Completed review history / semantic change log</summary><button onClick={()=>downloadJSON(k.proposals,'atlas-reference-decisions.json')}>Export review decisions</button><button onClick={()=>void run(p=>discardCompletedReviews(p),'Completed review rows cleared; accepted links remain.')}>Clear completed review rows</button>{k.audit.slice().reverse().slice(0,30).map(a=><p key={a.id}><small>r{a.revision} / {new Date(a.at).toLocaleString()} / {a.action}</small></p>)}</details>
 </>}
 </div></Modal>;
}
