import type {ResourceTarget} from '../core/reading-types.js';
import type {SubjectKey} from '../content-hub/model.js';
export type Concept={id:string;subject:SubjectKey;label:string;aliases:string[];primaryParentId?:string;relatedConceptIds:string[];deprecated?:boolean;replacedById?:string;createdAt:number;updatedAt:number};
export type ConceptAssignment={id:string;conceptId:string;target:ResourceTarget;targetRevision:string;note?:string;createdAt:number};
export type ReferenceEdge={id:string;source:ResourceTarget;target:ResourceTarget;sourceRevision:string;targetRevision:string;kind:'link'|'context'|'related';label?:string;note?:string;createdAt:number};
export type Suggestion={id:string;type:'assignment'|'reference';conceptId?:string;source?:ResourceTarget;target:ResourceTarget;sourceRevision?:string;targetRevision:string;kind?:ReferenceEdge['kind'];reason:string;confidence?:number;note?:string};
export type SuggestionBatch={schemaVersion:1;kind:'atlas-reference-suggestions';semanticRevision:number;suggestions:Suggestion[]};
export type ReviewedSuggestion=Suggestion&{batchId:string;semanticRevision:number;status:'proposed'|'accepted'|'rejected'|'stale';importedAt:number;reviewedAt?:number};
export type KnowledgeState={schemaVersion:1;revision:number;concepts:Concept[];assignments:ConceptAssignment[];edges:ReferenceEdge[];reviews:{target:ResourceTarget;revision:string;reviewedAt:number}[];proposals:ReviewedSuggestion[];audit:{id:string;revision:number;action:string;at:number;ids:string[]}[]};
export type ReferenceExplorerState={target?:ResourceTarget;conceptId?:string;returnViewId?:string};
