/** Optional React-PDF adapter. Network dependencies and real worker tests were
 * BLOCKED in the build environment. This source is NOT in the offline release.
 * Worker, CMaps and WASM are copied from the wrapper's resolved PDF.js package.
 */
import React,{useState,useEffect,useMemo,useRef} from 'react';
import {Document,Page,Outline,pdfjs} from 'react-pdf';
import 'react-pdf/dist/Page/AnnotationLayer.css';
import 'react-pdf/dist/Page/TextLayer.css';
import type {DocumentEntry,Location} from '../core/model';
import {clampPage,spreadPages,combinedRotation} from '../pdf/physical-pages.mjs';
import './pdf.css';
pdfjs.GlobalWorkerOptions.workerSrc=new URL('pdf-assets/pdf.worker.min.mjs',document.baseURI).href;
const options={isEvalSupported:false,cMapUrl:new URL('pdf-assets/cmaps/',document.baseURI).href,cMapPacked:true,wasmUrl:new URL('pdf-assets/wasm/',document.baseURI).href};
type PDF=Awaited<ReturnType<typeof pdfjs.getDocument>['promise']>;
type Props={document:DocumentEntry;location:Location;onLocation:(l:Location)=>void;url?:string;requestExternal:()=>void};
function PhysicalPage({pdf,n,width,rotation,root,virtual,onVisible}:{pdf:PDF;n:number;width:number;rotation:number;root:HTMLDivElement|null;virtual:boolean;onVisible:(n:number)=>void}){
 const ref=useRef<HTMLDivElement>(null),[near,setNear]=useState(!virtual),[size,setSize]=useState({ratio:1.414,intrinsic:0});
 useEffect(()=>{if(!virtual){setNear(true);return;}const observer=new IntersectionObserver(entries=>{setNear(entries[0].isIntersecting);},{root,rootMargin:'900px 0px'});if(ref.current)observer.observe(ref.current);return()=>observer.disconnect();},[virtual,root]);
 useEffect(()=>{let alive=true;if(near)pdf.getPage(n).then(p=>{if(!alive)return;const v=p.getViewport({scale:1,rotation:combinedRotation(p.rotate,rotation)});setSize({ratio:v.height/v.width,intrinsic:p.rotate});}).catch(()=>{});return()=>{alive=false;};},[near,pdf,n,rotation]);
 useEffect(()=>{if(!virtual)return;const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting)onVisible(n);},{root,rootMargin:'-10% 0px -75% 0px',threshold:0});if(ref.current)observer.observe(ref.current);return()=>observer.disconnect();},[root,virtual,n,onVisible]);
 const dpr=Math.max(0.5,Math.min(window.devicePixelRatio||1,2,Math.sqrt(5000000/(width*width*size.ratio))));
 return <section ref={ref} className="physical-page" data-physical-page={n} style={{width,minHeight:Math.ceil(width*size.ratio)+28}} aria-label={'Physical PDF page '+n}>
  <div className="physical-label">Page {n}</div>{near?<Page pageNumber={n} width={width} rotate={combinedRotation(size.intrinsic,rotation)} devicePixelRatio={dpr} renderAnnotationLayer renderTextLayer error={<p role="alert">This physical page could not be rendered. The original PDF remains available.</p>} loading={<p>Rendering page {n}...</p>}/>:<div className="pdf-placeholder" style={{height:width*size.ratio}}>Page {n}</div>}
 </section>;
}
export function PdfEngine({document:doc,location:loc,onLocation,url,requestExternal}:Props){
 const [pdf,setPDF]=useState<PDF|null>(null),[error,setError]=useState(''),[workerOK,setWorkerOK]=useState(false),[loading,setLoading]=useState('Opening PDF...'),[retry,setRetry]=useState(0),[outline,setOutline]=useState(false),[query,setQuery]=useState(''),[hits,setHits]=useState<{page:number;excerpt:string}[]>([]),[findStatus,setFindStatus]=useState(''),[password,setPassword]=useState(''),[passwordReason,setPasswordReason]=useState(''),[width,setWidth]=useState(700),[pageInput,setPageInput]=useState(String(loc.pdfPage));
 const passwordCallback=useRef<((value:string)=>void)|null>(null),host=useRef<HTMLDivElement>(null),job=useRef(0),locationRef=useRef(loc),onLocationRef=useRef(onLocation);locationRef.current=loc;onLocationRef.current=onLocation;
 const source=useMemo(()=>url?[{url}]:null,[url]);
 useEffect(()=>{let alive=true;fetch(new URL('pdf-assets/engine.json',document.baseURI),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('PDF worker metadata missing');return r.json();}).then(meta=>{if(meta.pdfjs!==pdfjs.version)throw Error('PDF worker version does not match React-PDF: '+meta.pdfjs+' vs '+pdfjs.version);if(alive)setWorkerOK(true);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[]);
 useEffect(()=>{setPDF(null);setError('');setHits([]);setFindStatus('');setPassword('');setPasswordReason('');passwordCallback.current=null;job.current++;return()=>{job.current++;passwordCallback.current=null;};},[doc.id,doc.sha256,url,retry]);
 useEffect(()=>{setPageInput(String(loc.pdfPage));},[loc.pdfPage]);
 useEffect(()=>{const el=host.current;if(!el)return;const ro=new ResizeObserver(()=>setWidth(el.clientWidth));ro.observe(el);return()=>ro.disconnect();},[url]);
 const setPage=(n:number)=>{const page=clampPage(n,pdf?.numPages??n);onLocationRef.current({...locationRef.current,pdfPage:page,anchor:{pdfPage:page,pdfRevision:doc.sha256}});if(locationRef.current.pdfMode==='continuous')requestAnimationFrame(()=>host.current?.querySelector<HTMLElement>('[data-physical-page="'+page+'"]')?.scrollIntoView({block:'start',behavior:'auto'}));};
 const seen=useMemo(()=>{let last=0;return (n:number)=>{if(last===n)return;last=n;const l=locationRef.current;if(l.pdfMode==='continuous'&&l.pdfPage!==n)onLocationRef.current({...l,pdfPage:n,anchor:{pdfPage:n,pdfRevision:doc.sha256}});};},[doc.id,doc.sha256]);
 const count=pdf?.numPages??0,page=clampPage(loc.pdfPage,count||1),paired=loc.pdfMode==='spread'&&width>=650,pages=loc.pdfMode==='continuous'?Array.from({length:count},(_,i)=>i+1):paired?spreadPages(page,count,loc.cover):[page];
 const pageWidth=Math.max(150,Math.floor((width-56-(paired?20:0))/(paired?2:1)*loc.zoom));
 async function find(){const text=query.trim().toLocaleLowerCase();const currentJob=++job.current;setHits([]);if(!pdf||!text){setFindStatus('Enter text present in the PDF.');return;}setFindStatus('Searching selectable PDF text...');const found:{page:number;excerpt:string}[]=[];let characters=0;const limit=Math.min(pdf.numPages,1000);
  try{for(let n=1;n<=limit;n++){if(currentJob!==job.current)return;const p=await pdf.getPage(n),content=await p.getTextContent();const value=content.items.map(item=>'str'in item?item.str:'').join(' ');characters+=value.length;const at=value.toLocaleLowerCase().indexOf(text);if(at>=0)found.push({page:n,excerpt:value.slice(Math.max(0,at-45),at+text.length+100)});if(n%10===0){setFindStatus('Searched '+n+' / '+limit+' pages');setHits([...found]);await new Promise(r=>setTimeout(r,0));}}if(currentJob!==job.current)return;setHits(found);setFindStatus((characters?found.length+' matching pages.':'No selectable text found. This may be an image-only PDF; OCR is not included.')+(limit<pdf.numPages?' Search bounded to the first 1,000 physical pages.':''));}catch(e){if(currentJob===job.current)setFindStatus('Text search failed: '+(e as Error).message);}
 }
 if(!url)return <div className="pdf-engine-empty"><h1>{doc.title}</h1><p>Allow the external PDF host before any document request.</p><code>{doc.source.url}</code><button onClick={requestExternal}>Allow external PDF reference</button></div>;
 return <div className="integrated-pdf">
  <div className="pdf-controls" aria-label="Physical PDF controls"><button disabled={!pdf||page<=1} onClick={()=>setPage(page-(paired?2:1))} aria-label="Previous PDF page">Previous</button><form onSubmit={e=>{e.preventDefault();setPage(Number(pageInput));}}><label>Page <input aria-label="Physical PDF page number" type="number" min="1" max={count||1} value={pageInput} onChange={e=>setPageInput(e.target.value)}/></label><span> / {count||'...'}</span></form><button disabled={!pdf||page>=count} onClick={()=>setPage(page+(paired?2:1))}>Next</button>
   <select aria-label="PDF presentation" value={loc.pdfMode} onChange={e=>onLocation({...loc,pdfMode:e.target.value as Location['pdfMode']})}><option value="single">Single page</option><option value="continuous">Continuous</option><option value="spread">Physical-page spread</option></select>
   <select aria-label="PDF zoom" value={loc.zoom} onChange={e=>onLocation({...loc,zoom:Number(e.target.value)})}>{[0.5,0.75,1,1.25,1.5,2].map(z=><option key={z} value={z}>{z===1?'Fit width':Math.round(z*100)+'%'}</option>)}</select><button onClick={()=>onLocation({...loc,rotation:(loc.rotation+90)%360})}>Rotate 90 degrees</button><button aria-pressed={outline} onClick={()=>setOutline(!outline)}>Outline</button>{loc.pdfMode==='spread'&&<label><input type="checkbox" checked={loc.cover} onChange={e=>onLocation({...loc,cover:e.target.checked})}/> Cover alone</label>}<a href={url} target="_blank" rel="noopener noreferrer">Original PDF</a>
  </div>
  <form className="pdf-find" onSubmit={e=>{e.preventDefault();void find();}}><input aria-label="Find text in PDF" value={query} onChange={e=>{job.current++;setQuery(e.target.value);}} placeholder="Find selectable text..."/><button disabled={!pdf}>Find</button><span role="status">{findStatus}</span></form>
  {hits.length>0&&<details open className="pdf-search-results"><summary>{hits.length} matching physical pages</summary>{hits.map(h=><button key={h.page} onClick={()=>setPage(h.page)}><strong>Page {h.page}</strong> {h.excerpt}</button>)}</details>}
  {loc.pdfMode==='spread'&&!paired&&<p className="pdf-small-note">Narrow canvas: displaying one physical page. Spread preference is retained.</p>}
  {passwordCallback.current&&<form className="pdf-password" onSubmit={e=>{e.preventDefault();const callback=passwordCallback.current;passwordCallback.current=null;callback?.(password);setPassword('');setPasswordReason('');}}><p>{passwordReason} Passwords are used in memory only and are never backed up.</p><label>PDF password<input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)}/></label><button>Unlock PDF</button><button type="button" onClick={()=>{passwordCallback.current=null;setPassword('');setPasswordReason('');setError('Password entry cancelled. The original bytes remain intact.');}}>Cancel</button></form>}
  {error&&<div className="pdf-engine-error" role="alert"><strong>PDF could not be opened</strong><p>{error}</p><button onClick={()=>{setError('');setRetry(x=>x+1);}}>Retry PDF</button><a href={url} target="_blank" rel="noopener noreferrer">Open original</a></div>}
  <div className="pdf-canvas-scroll" ref={host}>
   {workerOK&&!error?<Document key={doc.id+':'+doc.sha256+':'+retry} file={source?.[0]} options={options} externalLinkTarget="_blank" externalLinkRel="noopener noreferrer" onLoadSuccess={async p=>{setPDF(p);setLoading('');const n=clampPage(locationRef.current.pdfPage,p.numPages);onLocationRef.current({...locationRef.current,pdfPage:n,anchor:{pdfPage:n,pdfRevision:doc.sha256}});requestAnimationFrame(()=>{if(locationRef.current.pdfMode==='continuous')host.current?.querySelector<HTMLElement>('[data-physical-page="'+n+'"]')?.scrollIntoView({block:'start'});});}} onLoadError={e=>setError(e.message)} onSourceError={e=>setError(e.message)} onLoadProgress={({loaded,total})=>setLoading(total?'Loading '+Math.round(loaded/total*100)+'%':'Loading PDF bytes...')} onPassword={(callback,reason)=>{passwordCallback.current=callback;setPasswordReason(reason===2?'Incorrect password. Try again.':'This PDF is password protected.');}} onItemClick={({pageNumber})=>{if(pageNumber)setPage(pageNumber);}} loading={<p role="status">{loading}</p>}>
    {outline&&<aside className="pdf-outline"><h3>Document outline</h3><Outline onItemClick={({pageNumber})=>{if(pageNumber)setPage(pageNumber);}} noData={<p>This PDF has no outline.</p>}/></aside>}
    <div className={'pdf-physical-pages '+(paired?'pdf-spread':'')}>{pdf&&pages.map(n=><PhysicalPage key={n} pdf={pdf} n={n} width={pageWidth} rotation={loc.rotation} root={host.current} virtual={loc.pdfMode==='continuous'} onVisible={seen}/>)}</div>
   </Document>:!error&&<p>Checking compatible local PDF worker...</p>}
  </div>
  <div className="pdf-engine-footer">{doc.title} / {paired?pages.join('-'):page} of {count||'...'} physical pages / {doc.sha256?.slice(0,12)??'External reference'}</div>
 </div>;
}
