import React,{useState} from '../vendor/react.mjs';import {Icon,IconButton} from './Icon.js';import {locations,findNode} from '../core/workspace.js';
export function Home({catalogue:c,workspace:ws,onOpen,onCreate,onManage,onSettings,onRestore,onGroup}:any){const [showArchived,setShowArchived]=useState(false);const loc=locations(c),archived=new Set(ws.overlays.archived),projects=c.projects.filter((p:any)=>showArchived||!archived.has(p.id));
 const count=(p:any)=>[...loc.values()].filter(x=>x.project.id===p.id).length;const first=(p:any)=>[...loc.entries()].find(([id,x])=>x.project.id===p.id&&!archived.has(id)&&!x.ancestors.some(id=>archived.has(id)))?.[0];
 const recent=ws.personal.session.panes.flatMap((p:any)=>p.views.flatMap((v:any)=>v.history.slice().reverse())).map((l:any)=>l.pageId).filter((id:string,i:number,a:string[])=>a.indexOf(id)===i).slice(0,4).map((id:string)=>c.pages.find((p:any)=>p.id===id)).filter(Boolean);
 return <main className="home-page"><div className="home-greeting"><div className="eyebrow">YOUR PERSONAL KNOWLEDGE WORKSPACE</div><h1>Make room for a clear thought.</h1><p>A notebook for the things you want to understand, remember and connect.</p></div><div className="home-actions"><button className="primary" onClick={()=>onCreate('project')}><Icon name="plus" size={17}/> New notebook</button><button onClick={()=>onSettings()}><Icon name="upload" size={17}/> Import library</button><button onClick={()=>onGroup()}><Icon name="folder" size={17}/> Manage groups</button><button onClick={()=>onOpen('page.atlas.welcome')}><Icon name="help" size={17}/> Reader guide</button></div>
 {recent.length>0&&<section className="recent-section"><div className="section-label"><h2>Pick up where you left off</h2></div><div className="recent-grid">{recent.map((p:any)=><button className="recent-card" key={p.id} onClick={()=>onOpen(p.id)}><Icon name="page"/><span><strong>{p.title}</strong><small>{loc.get(p.id)?.project.title??'Unfiled page'}</small></span><Icon name="right" size={16}/></button>)}</div></section>}
 <section><div className="section-label"><h2>Your notebooks <span className="count-badge">{projects.length}</span></h2><label className="inline-check"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/> Show archived</label></div><div className="project-grid">{projects.map((p:any)=><article className={'project-card '+(archived.has(p.id)?'archived':'')} key={p.id}><div className="project-card-top"><span className="project-icon large"><Icon name={p.icon} size={23}/></span><IconButton name="more" label={'Manage project '+p.title} onClick={()=>onManage({project:p})}/></div><h3>{p.title}</h3><p>{p.description||'Your own space to organize ideas and reference material.'}</p><div className="project-card-bottom"><span>{count(p)} pages{ws.overlays.projectPrefs[p.id]?.hidden?' / Hidden from sidebar':''}{archived.has(p.id)?' / Archived':''}</span>{archived.has(p.id)?<button className="text-button" onClick={()=>onRestore(p.id)}>Restore</button>:<button className="text-button" onClick={()=>first(p)?onOpen(first(p)):onCreate('page',p)}>Open notebook <Icon name="right" size={15}/></button>}</div></article>)}</div></section>
 {ws.overlays.archived.length>0&&<details className="archive-list"><summary><Icon name="archive" size={16}/> Archived items ({ws.overlays.archived.length})</summary>{ws.overlays.archived.map((id:string)=>{const node=findNode(c.projects,id);return <div className="archive-row" key={id}><span>{c.projects.find((p:any)=>p.id===id)?.title??node?.node.title??c.pages.find((p:any)=>p.id===id)?.title??id}</span><button onClick={()=>onRestore(id)}>Restore</button></div>;})}</details>}
 <div className="home-note"><Icon name="lock" size={19}/><div><strong>Private by default. Portable by choice.</strong><p>Your library and remarks stay in this browser. A workspace backup includes your content, local PDFs, notes and reading state. There is no cloud synchronization.</p><button className="text-button" onClick={()=>onSettings()}>Backup &amp; workspace settings <Icon name="right" size={15}/></button></div></div></main>;}
