import {DocumentInfo} from '../pdf/DocumentInfo.js';
import {makeRemark,pdfAnchor} from '../core/personal-state.js';
import React,{useState,useMemo} from '../vendor/react.mjs';import {Modal} from './Modal.js';import {Icon,IconButton} from './Icon.js';import {Inline} from '../reader/markdown.js';import {searchCatalog,locations} from '../core/workspace.js';import {pageLinks,walkBlocks} from '../core/validation.mjs';import {store} from '../storage/database.js';
import {inExperience} from '../experience/facts.js';import {isAllContent} from '../experience/profile.mjs';
export function TermCard({term:t,onOpen,catalogue:c}:any){return <details className="term-card"><summary>{t.label}{t.translation&&<small>{t.translation}</small>}</summary><p><Inline text={t.definition}/></p>{t.example&&<div className="term-example"><strong>Example</strong><p><Inline text={t.example}/></p></div>}<div className="term-pages">{t.pageIds.map((id:string)=><button className="text-button" key={id} onClick={()=>onOpen(id)}><Icon name="link" size={13}/>{c.pages.find((p:any)=>p.id===id)?.title??id}</button>)}{t.pdfRefs?.flatMap((r:any)=>r.pages.map((n:number)=><button className="text-button" key={r.documentId+':'+n} onClick={()=>onOpen(r.pageId,pdfAnchor(n,r.revision))}><Icon name="pdf" size={13}/>Physical page {n}</button>))}</div></details>;}
export function SearchDialog({catalogue:c,onClose,onOpen,initial='',experience,facts}:any){const scoped=!!experience&&!isAllContent(experience),[scope,setScope]=useState<'experience'|'all'>(scoped?'experience':'all');
 // V3: the Experience filter is applied BEFORE text search, so scoped search does not scan hidden resources.
 const searchable=useMemo(()=>scope==='experience'&&scoped?{...c,pages:c.pages.filter((p:any)=>inExperience(experience,facts?.get(p.id)))}:c,[c,scope,scoped,experience,facts]);
 const [query,setQuery]=useState(initial),[tab,setTab]=useState('all'),results=useMemo(()=>searchCatalog(searchable,query),[searchable,query]),locs=useMemo(()=>locations(c),[c]);return <Modal title="Search your knowledge" onClose={onClose} wide><form className="search-form" onSubmit={e=>{e.preventDefault();if(results.pages[0])onOpen(results.pages[0].page.id,{blockId:results.pages[0].anchor});}}><Icon name="search"/><input autoFocus aria-label="Search all pages and glossary" placeholder="A concept, code token, Norwegian word, or page title..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>Enter</kbd></form>{scoped&&<div className="search-scope" role="group" aria-label="Search scope"><button aria-pressed={scope==='experience'} onClick={()=>setScope('experience')}>This Experience ({experience.name??'Custom'})</button><button aria-pressed={scope==='all'} onClick={()=>setScope('all')}>All library</button></div>}<div className="dialog-tabs">{['all','pages','glossary'].map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t==='all'?'All results':t==='pages'?`Pages (${results.pages.length})`:`Glossary (${results.terms.length})`}</button>)}</div><div className="search-results">{!query.trim()?<div className="empty-state"><Icon name="search" size={28}/><h3>Follow an idea across notebooks</h3><p>Search titles, text, code, folder paths, glossary definitions, translations and examples.</p></div>:<>{tab!=='glossary'&&results.pages.slice(0,60).map(({page,anchor}:any)=><div className="search-result-row" key={page.id}><button className="search-result" onClick={e=>onOpen(page.id,{blockId:anchor},e.ctrlKey||e.metaKey)} onAuxClick={e=>{if(e.button===1){e.preventDefault();onOpen(page.id,{blockId:anchor},true);}}}><Icon name="page"/><span><strong>{page.title}</strong><small>{locs.get(page.id)?.path.join(' / ')}</small><p>{page.summary}</p></span><Icon name="right" size={16}/></button><IconButton name="plus" label={'Open '+page.title+' in new tab'} onClick={()=>onOpen(page.id,{blockId:anchor},true)}/></div>)}{tab!=='pages'&&results.terms.length>0&&<section><h3>Glossary matches</h3>{results.terms.slice(0,80).map(t=><TermCard key={t.id} term={t} catalogue={c} onOpen={onOpen}/>)}</section>}{results.pages.length===0&&results.terms.length===0&&<p className="empty-state">No matches. Try a shorter word or a code token.</p>}{results.pages.length>60&&tab!=='glossary'&&<p className="secondary">Showing 60 of {results.pages.length} page matches. Refine the search.</p>}</>}</div></Modal>;}
export {ContextPanel} from './DocumentContext.js';
