import {DurabilityPanel} from '../durability/DurabilityPanel.js';
import {csvWorkspace} from '../content/csv.mjs';
import {createVerifiedBackup,verifyBackupFile,verifyRecoveryBundle} from '../durability/recovery.js';
import {getBuildIdentity} from '../durability/provenance.js';
import {recordBackupHealth} from '../durability/backup-health.js';
import {attachArchive} from '../durability/registry.js';
import {preflightStorage} from '../durability/storage-health.mjs';
import {HISTORY_LIMITS} from '../history/validation.mjs';
import {activeSession} from '../core/workspace-slots.js';
import {captureWorkspaceSnapshot} from '../storage/workspace-snapshot.js';
import React, { useEffect, useState } from '../vendor/react.mjs';
import {AppearanceControls} from './AppearanceControls.js';
import { Modal, Field } from './Modal.js';
import { Icon } from './Icon.js';
import { store } from '../storage/database.js';
import {captureEmergencyRecovery} from '../durability/emergency.js';
import { unzipBounded, makeBackup, readBackup, download } from '../storage/archives.mjs';
import { readWorkspace, planImport } from '../core/packs.mjs';
import { compose, uid, makeMarkdownPage, applyOperation } from '../core/workspace.js';
import { sha256, assertSafeAsset } from '../core/validation.mjs';
import { schemas } from '../app/load.js';
import { folderOptions } from './EditDialogs.js';
import { THEME_LABELS } from '../core/model.js';
import { PdfIntake } from './PdfIntake.js';
import { duplicatePdfImports } from '../core/pdf-library.js';
import { exportPrivatePdfLibrary } from '../core/export-pdf-library.mjs';
import { exportRepositoryWorkspace } from '../core/export-pack.mjs';
export function SettingsDialog({ built, catalogue: c, assets, initialProject, initialFolder, onClose, onOpen, notify }: any) {
    const [busy, setBusy] = useState(''), [error, setError] = useState(''), [preview, setPreview] = useState<any>(null), [restore, setRestore] = useState<any>(null), [confirmRestore, setConfirmRestore] = useState(false), [usage, setUsage] = useState<any>(null), [persistent,setPersistent]=useState<boolean|null>(null), [backupMessage, setBackupMessage] = useState('');
    const [pdfExportId,setPdfExportId]=useState('atlas.private-pdf-library'),[pdfExportVersion,setPdfExportVersion]=useState('1.0.0');
    useEffect(() => { navigator.storage?.estimate?.().then(setUsage).catch(() => { }); navigator.storage?.persisted?.().then(setPersistent).catch(()=>{}); }, []);
    async function action(label: string, fn: () => Promise<void>) { setBusy(label); setError(''); try {
        await fn();
    }
    catch (e) {
        setError((e as Error).message);
    }
    finally {
        setBusy('');
    } }
    async function requestPersistentStorage(){await action('Requesting browser storage protection...',async()=>{if(!navigator.storage?.persist)throw Error('This browser does not expose persistent-storage permission. Keep verified backups.');const granted=await navigator.storage.persist();setPersistent(granted);notify(granted?'Browser granted persistent storage for this AtlasNote origin. Keep verified backups anyway.':'Browser did not grant persistent storage. AtlasNote still works, but keep verified backups.');});}
    async function importCSV(file:File){setPreview(null);await action('Validating CSV...',async()=>{if(file.size>2_000_000)throw Error('CSV exceeds 2 MB');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer()),title=file.name.replace(/\.(csv|tsv)$/i,''),id='csv.local.'+(await sha256(new TextEncoder().encode(file.name))).slice(0,16),active=compose(built,store.state),old=active.packs.find((p:any)=>p.manifest.id===id),version=old?old.manifest.version.split('.').map((n:string,i:number)=>i===2?Number(n)+1:n).join('.'):'1.0.0',files=csvWorkspace({id,version,title,visibility:'private'},[{id:'words',title,file:file.name,csv:text,folder:'Imported CSV'}]),input=await readWorkspace(files,await schemas()),plan=planImport(active.packs,input.packs,store.state.overlays);await preflightStorage([...files.values()].reduce((total,bytes)=>total+bytes.length,0));setPreview({...input,plan,name:file.name,size:file.size});});}
    async function importLibrary(file: File) { setPreview(null); await action('Validating library...', async () => { await preflightStorage(file.size); const result = await unzipBounded(file);await preflightStorage(result.bytes); if (['backup','complete-recovery','history-archive'].includes(result.transfer?.kind))
        throw Error('This is a workspace backup. Use Restore backup below.'); const input = await readWorkspace(result.files, await schemas(), { allowUnresolved: true }); const active = compose(built, store.state); const plan = planImport(active.packs, input.packs, store.state.overlays); plan.conflicts.push(...duplicatePdfImports(active,input.packs)); setPreview({ ...input, plan, name: file.name, size: result.bytes }); }); }
    async function commitLibrary() { await action('Importing library...', async () => { const current = compose(built, store.state), plan = planImport(current.packs, preview.packs, store.state.overlays); plan.conflicts.push(...duplicatePdfImports(current,preview.packs)); if (plan.conflicts.length) {
        setPreview((p: any) => ({ ...p, plan }));
        throw Error('The workspace changed or has conflicts. Review the preview; nothing was imported.');
    } const changed = preview.packs.filter((p: any) => !plan.unchanged.includes(p.manifest.id)), overlays = structuredClone(store.state.overlays); overlays.groups = structuredClone(overlays.groups ?? built.groups); for (const group of preview.workspace.groups) {
        const old = overlays.groups!.find(g => g.id === group.id);
        if (old)
            old.projectIds = [...new Set([...old.projectIds, ...group.projectIds])];
        else
            overlays.groups!.push(group);
    } for(const pack of changed)for(const project of pack.projects)if(project.id.startsWith('project.csv.local.')){overlays.categories??={};overlays.categories[project.id]='norsk';} await store.importPacks(changed, preview.assets, overlays); setPreview(null); notify(changed.length ? 'Library imported. Your additions and personal state were retained.' : 'This library is already imported. No content changes were needed.'); }); }
    async function backup() { await action('Preparing verified backup...', async () => { const snapshot = await captureWorkspaceSnapshot(); const result = await createVerifiedBackup(snapshot, built, assets.asset, await getBuildIdentity(), await schemas());recordBackupHealth('generated',result.summary,snapshot.history?.meta.epoch??0); download(result.bytes, 'knowledge-atlas-workspace.atlas-backup.zip'); setBackupMessage('Backup generated and offered for download, not proof of retention. It contains current content, live history and audit, needed live historical attachments, remarks, flags, bookmarks and view state. Any external archive dependencies must be kept separately or included using Complete recovery.' + (store.error?' Browser saving failed; this backup captures current in-memory work. Keep this tab open until you verify restoration.':'') + (result.external.length ? ' ' + result.external.length + ' external image references remain links; their remote bytes are not included.' : '')); }); }
    async function previewRestore(file: File) { setRestore(null); setConfirmRestore(false); await action('Validating backup...', async () => { const {transfer}=await unzipBounded(file);if(transfer?.kind==='complete-recovery'){const bundle=await verifyRecoveryBundle(file,built,await schemas());setRestore({...bundle.backup,verifiedArchives:bundle.archives});}else setRestore((await verifyBackupFile(file,built,await schemas())).backup); }); }
    async function commitRestore() { await action('Restoring workspace...', async () => { if (!confirmRestore)
        throw Error('Confirm replacement before restoring'); await store.restore(restore.workspace,assets.asset);for(const archive of restore.verifiedArchives??[])await attachArchive(archive.bytes,store.state.history!); notify('Workspace restored from verified bytes.'); setRestore(null); onClose(); }); }
    return <Modal title="Workspace settings" onClose={onClose} wide><div className="settings-layout"><section className="settings-section"><h3><Icon name="upload"/> Import library</h3><p>Import an Atlas ZIP or a UTF-8 CSV table. Preview the content before committing. CSV tables appear under Norsk / Imported CSV; each page contains up to 40 rows.</p><label className="file-picker secondary-picker">Choose CSV<input aria-label="Import CSV table" type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values" disabled={!!busy} onChange={e=>{const file=e.target.files?.[0];if(file)importCSV(file);e.target.value='';}}/></label><label className="file-picker">Choose library ZIP<input aria-label="Import library ZIP" type="file" accept=".zip" disabled={!!busy} onChange={e => { const f = e.target.files?.[0]; if (f)
        importLibrary(f); e.target.value = ''; }}/></label>{preview && <div className="import-preview"><h4>Review: {preview.name}</h4><div className="preview-stats"><span><strong>{preview.validation.pages}</strong> pages</span><span><strong>{preview.validation.terms}</strong> terms</span><span><strong>{preview.validation.projects}</strong> projects</span></div><p>{preview.plan.addedPages.length} new pages; {preview.plan.changed.length} updated packs; {preview.plan.unchanged.length} unchanged packs; {preview.plan.moves.length} recorded source moves.</p><ul>{preview.packs.map((p: any) => <li key={p.manifest.id}><code>{p.manifest.id}</code> {p.manifest.version} <span className="badge">{p.manifest.visibility}</span></li>)}</ul><p className="privacy-note">This import stays on this device. It does not upload or publish anything. Your existing additions, remarks, ratings, bookmarks and open views are retained.</p>{preview.plan.conflicts.length > 0 ? <div className="error-message"><strong>Import blocked. No changes committed.</strong>{preview.plan.conflicts.map((s: string, i: number) => <p key={i}>{s}</p>)}</div> : <p className="success-message">Stable IDs, dependencies, relationships and attachment checksums passed validation.</p>}<div className="button-row"><button onClick={() => setPreview(null)} disabled={!!busy}>Cancel import</button><button className="primary" disabled={!!busy || !!preview.plan.conflicts.length} onClick={commitLibrary}>Confirm library import</button></div></div>}</section>
 <PdfIntake built={built} catalogue={c} initialProject={initialProject} initialFolder={initialFolder} onClose={onClose} onOpen={onOpen} notify={notify} disabled={!!busy}/>
 <section className="settings-section"><h3><Icon name="download"/> Backup &amp; recovery</h3><p>A workspace backup contains current content, live immutable versions and review records, local bytes needed by live history, your personal state and the exact archive index. Older externalized history still requires its saved archive files. Use Complete recovery below to include those bytes. Public external PDF versions keep their immutable source references, not copied bytes. Keep it private. A content export is not a substitute for this backup.</p><div className="history-storage-summary" data-history-diagnostics><p><strong>{store.state.history?.heads.length??0}</strong> logical resources / <strong>{store.state.history?.revisions.length??0}</strong> immutable revisions / <strong>{store.state.history?.reviews.length??0}</strong> review records.</p><p className="secondary">IndexedDB v3; backup schema 5 (reads 2/3/4/5). History limit: {HISTORY_LIMITS.totalRevisions} revisions in total, {HISTORY_LIMITS.perResource} per resource, 64 MiB structured data. No automatic pruning. Export a full backup before a limit is reached; reaching a limit blocks new content commits rather than deleting history.</p></div><button className="primary" onClick={backup} disabled={!!busy}><Icon name="download"/> Download workspace backup</button>{backupMessage && <p className="success-message">{backupMessage}</p>}<label className="file-picker secondary-picker">Choose backup to restore<input aria-label="Restore workspace backup" type="file" accept=".zip" disabled={!!busy} onChange={e => { const f = e.target.files?.[0]; if (f)
        previewRestore(f); e.target.value = ''; }}/></label>{restore && <div className="import-preview"><h4>Restore preview</h4><p>{restore.workspace.imports.length} pack snapshots, {Object.keys(restore.workspace.personal.notes).length} saved remarks, {restore.workspace.personal.bookmarks.length} bookmarks and {restore.workspace.assets.length} verified attachments; {restore.workspace.history?.revisions.length??0} historical revisions and {restore.workspace.history?.reviews.length??0} review records. Legacy backups initialize a new baseline without fabricating earlier edits.</p><p className="warning-text">Restore replaces this browser's saved workspace, including its personal state. Download a backup of this workspace first. History-enabled restores require the current projection and every stored head to agree; conflicting application source is rejected rather than silently changing a historical snapshot.</p><label className="inline-check"><input type="checkbox" checked={confirmRestore} onChange={e => setConfirmRestore(e.target.checked)}/> I understand that this replaces the current local workspace.</label><div className="button-row"><button onClick={() => setRestore(null)}>Cancel restore</button><button className="primary" onClick={commitRestore} disabled={!confirmRestore || !!busy}>Restore verified backup</button></div></div>}{store.error && <div className="error-message"><p>{store.error}</p><button onClick={() => action('Retrying save...', () => store.retry())}>Retry saving</button><button onClick={() => action('Preparing raw recovery...', async () => { download(JSON.stringify(await captureEmergencyRecovery(), (_k, v) => v instanceof Uint8Array ? { type: 'Uint8Array', bytes: [...v] } : v, 2), 'atlas-raw-recovery.json', 'application/json'); })}>Download raw recovery JSON</button><p className="secondary">Private emergency diagnostic: includes a detached in-memory copy of unsaved work and a separately labelled persisted snapshot. It is not a verified restorable backup.</p></div>}</section>
 <DurabilityPanel built={built} assets={assets} disabled={!!busy}/><section className="settings-section"><h3><Icon name="folder"/> Export content for manual repository work</h3><p>Export canonical pack folders with stable IDs, local edits and attachments. All exported packs are deliberately marked private. Remarks, flags, archived status and reading state belong in your separate workspace backup.</p><button disabled={!!busy} onClick={() => action('Exporting private content workspace...', async () => { const result = await exportRepositoryWorkspace(compose(built, store.state), store.state, assets.asset); download(result.bytes, 'knowledge-atlas-content-workspace.private.zip'); notify(`Exported ${result.pageCount} pages in ${result.packCount} private packs.`); })}>Export private content workspace</button></section>
 <section className="settings-section"><h3><Icon name="pdf"/>Export private PDF library</h3><p>Download only private PDF binaries and metadata as a standard Atlas library ZIP. No publication, credentials or repository fetch. Public demo PDFs, note bodies and personal state are excluded; keep a complete backup separately.</p><Field label="PDF library pack ID"><input value={pdfExportId} onChange={e=>setPdfExportId(e.target.value)}/></Field><Field label="PDF library version"><input value={pdfExportVersion} onChange={e=>setPdfExportVersion(e.target.value)}/></Field><p className="secondary">For a fresh workspace or reviewed source-ownership migration. Reuse this ID and advance the version for changes; conflicting existing IDs are never silently overwritten.</p><button disabled={!!busy} onClick={()=>action('Preparing private PDF library...',async()=>{await store.flush();const result=await exportPrivatePdfLibrary(compose(built,store.state),assets.asset,{id:pdfExportId,version:pdfExportVersion});download(result.bytes,'atlasnote-private-pdf-library.zip');notify(`Exported ${result.documentCount} private PDF document(s). Nothing was uploaded.`);})}>Download private PDF library ZIP</button></section>
 <section className="settings-section"><h3>Appearance &amp; storage</h3><AppearanceControls session={activeSession(store.state.personal)} onChange={patch=>{document.dispatchEvent(new Event('atlas:before-reader-change'));store.personal(p=>Object.assign(activeSession(p),patch));}}/><label className="inline-check"><input type="checkbox" checked={activeSession(store.state.personal).showFlags} onChange={e=>store.personal(p=>{activeSession(p).showFlags=e.target.checked;})}/>Show learning flags</label><Field label="Reading text size"><input type="range" min="14" max="22" step="1" value={activeSession(store.state.personal).fontSize} onChange={e => {document.dispatchEvent(new Event('atlas:before-reader-change'));store.personal(p => { activeSession(p).fontSize = Number(e.target.value); });}}/></Field><p>{usage ? `${Math.round((usage.usage ?? 0) / 1024 / 1024 * 10) / 10} MB used of approximately ${Math.round((usage.quota ?? 0) / 1024 / 1024)} MB available.` : 'Storage is managed by this browser.'} Clearing site data removes local changes.</p><div className="storage-persistence" aria-label="Browser storage protection"><strong>Local storage protection: {persistent===true?'Persistent':persistent===false?'Best effort':'Unknown'}</strong>{persistent===false&&typeof navigator.storage?.persist==='function'&&<button disabled={!!busy} onClick={()=>void requestPersistentStorage()}>Ask browser to protect local data</button>}<small>Browser persistence reduces automatic eviction risk; it is not synchronization or a backup.</small></div><p className="secondary">Hosting-provider access protection; AtlasNote has no app accounts, telemetry, automatic external image fetches or background synchronization.</p></section></div>{busy && <div className="busy-status" role="status">{busy}</div>}{error && <pre className="error-message" role="alert">{error}</pre>}</Modal>;
}
