import React, { useEffect, useState } from '../vendor/react.mjs';
import { Modal, Field } from './Modal.js';
import { Icon } from './Icon.js';
import { store, rawRecovery } from '../storage/database.js';
import { unzipBounded, makeBackup, readBackup, download } from '../storage/archives.mjs';
import { readWorkspace, planImport } from '../core/packs.mjs';
import { compose, uid, makeMarkdownPage, applyOperation } from '../core/workspace.js';
import { sha256, assertSafeAsset } from '../core/validation.mjs';
import { schemas } from '../app/load.js';
import { folderOptions } from './EditDialogs.js';
import { THEME_LABELS } from '../core/model.js';
import { PdfIntake } from './PdfIntake.js';
import { duplicatePdfImports } from '../core/pdf-library.js';
import { exportPrivatePdfLibrary } from '../core/export-pdf-library.mjs';
import { exportRepositoryWorkspace } from '../core/export-pack.mjs';
export function SettingsDialog({ built, catalogue: c, assets, initialProject, initialFolder, onClose, onOpen, notify }: any) {
    const [busy, setBusy] = useState(''), [error, setError] = useState(''), [preview, setPreview] = useState<any>(null), [restore, setRestore] = useState<any>(null), [confirmRestore, setConfirmRestore] = useState(false), [usage, setUsage] = useState<any>(null), [backupMessage, setBackupMessage] = useState('');
    const [pdfExportId,setPdfExportId]=useState('atlas.private-pdf-library'),[pdfExportVersion,setPdfExportVersion]=useState('1.0.0');
    useEffect(() => { navigator.storage?.estimate?.().then(setUsage).catch(() => { }); }, []);
    async function action(label: string, fn: () => Promise<void>) { setBusy(label); setError(''); try {
        await fn();
    }
    catch (e) {
        setError((e as Error).message);
    }
    finally {
        setBusy('');
    } }
    async function importLibrary(file: File) { setPreview(null); await action('Validating library...', async () => { const result = await unzipBounded(file); if (result.transfer?.kind === 'backup')
        throw Error('This is a workspace backup. Use Restore backup below.'); const input = await readWorkspace(result.files, await schemas(), { allowUnresolved: true }); const active = compose(built, store.state); const plan = planImport(active.packs, input.packs, store.state.overlays); plan.conflicts.push(...duplicatePdfImports(active,input.packs)); setPreview({ ...input, plan, name: file.name, size: result.bytes }); }); }
    async function commitLibrary() { await action('Importing library...', async () => { const current = compose(built, store.state), plan = planImport(current.packs, preview.packs, store.state.overlays); plan.conflicts.push(...duplicatePdfImports(current,preview.packs)); if (plan.conflicts.length) {
        setPreview((p: any) => ({ ...p, plan }));
        throw Error('The workspace changed or has conflicts. Review the preview; nothing was imported.');
    } const changed = preview.packs.filter((p: any) => !plan.unchanged.includes(p.manifest.id)), overlays = structuredClone(store.state.overlays); overlays.groups = structuredClone(overlays.groups ?? built.groups); for (const group of preview.workspace.groups) {
        const old = overlays.groups!.find(g => g.id === group.id);
        if (old)
            old.projectIds = [...new Set([...old.projectIds, ...group.projectIds])];
        else
            overlays.groups!.push(group);
    } await store.importPacks(changed, preview.assets, overlays); setPreview(null); notify(changed.length ? 'Library imported. Your additions and personal state were retained.' : 'This library is already imported. No content changes were needed.'); }); }
    async function backup() { await action('Preparing verified backup...', async () => { await store.flush(); const result = await makeBackup(store.state, built, assets.asset); download(result.bytes, 'knowledge-atlas-workspace.atlas-backup.zip'); setBackupMessage('Backup downloaded. It contains local content, attachments, remarks, flags, bookmarks and view state.' + (result.external.length ? ' ' + result.external.length + ' external image references remain links; their remote bytes are not included.' : '')); }); }
    async function previewRestore(file: File) { setRestore(null); setConfirmRestore(false); await action('Validating backup...', async () => { const { files } = await unzipBounded(file); setRestore(await readBackup(files, await schemas())); }); }
    async function commitRestore() { await action('Restoring workspace...', async () => { if (!confirmRestore)
        throw Error('Confirm replacement before restoring'); await store.restore(restore.workspace); notify('Workspace restored from verified bytes.'); setRestore(null); onClose(); }); }
    return <Modal title="Workspace settings" onClose={onClose} wide><div className="settings-layout"><section className="settings-section"><h3><Icon name="upload"/> Import library</h3><p>Import a canonical Atlas ZIP. You will see its content, visibility, ID conflicts and version changes before committing.</p><label className="file-picker">Choose library ZIP<input aria-label="Import library ZIP" type="file" accept=".zip" disabled={!!busy} onChange={e => { const f = e.target.files?.[0]; if (f)
        importLibrary(f); e.target.value = ''; }}/></label>{preview && <div className="import-preview"><h4>Review: {preview.name}</h4><div className="preview-stats"><span><strong>{preview.validation.pages}</strong> pages</span><span><strong>{preview.validation.terms}</strong> terms</span><span><strong>{preview.validation.projects}</strong> projects</span></div><p>{preview.plan.addedPages.length} new pages; {preview.plan.changed.length} updated packs; {preview.plan.unchanged.length} unchanged packs; {preview.plan.moves.length} recorded source moves.</p><ul>{preview.packs.map((p: any) => <li key={p.manifest.id}><code>{p.manifest.id}</code> {p.manifest.version} <span className="badge">{p.manifest.visibility}</span></li>)}</ul><p className="privacy-note">This import stays on this device. It does not upload or publish anything. Your existing additions, remarks, ratings, bookmarks and open views are retained.</p>{preview.plan.conflicts.length > 0 ? <div className="error-message"><strong>Import blocked. No changes committed.</strong>{preview.plan.conflicts.map((s: string, i: number) => <p key={i}>{s}</p>)}</div> : <p className="success-message">Stable IDs, dependencies, relationships and attachment checksums passed validation.</p>}<div className="button-row"><button onClick={() => setPreview(null)} disabled={!!busy}>Cancel import</button><button className="primary" disabled={!!busy || !!preview.plan.conflicts.length} onClick={commitLibrary}>Confirm library import</button></div></div>}</section>
 <PdfIntake built={built} catalogue={c} initialProject={initialProject} initialFolder={initialFolder} onClose={onClose} onOpen={onOpen} notify={notify} disabled={!!busy}/>
 <section className="settings-section"><h3><Icon name="download"/> Backup &amp; recovery</h3><p>A complete workspace backup contains content snapshots, local PDF bytes and your personal state. Keep it private. A content export is not a substitute for this backup.</p><button className="primary" onClick={backup} disabled={!!busy}><Icon name="download"/> Download workspace backup</button>{backupMessage && <p className="success-message">{backupMessage}</p>}<label className="file-picker secondary-picker">Choose backup to restore<input aria-label="Restore workspace backup" type="file" accept=".zip" disabled={!!busy} onChange={e => { const f = e.target.files?.[0]; if (f)
        previewRestore(f); e.target.value = ''; }}/></label>{restore && <div className="import-preview"><h4>Restore preview</h4><p>{restore.workspace.imports.length} pack snapshots, {Object.keys(restore.workspace.personal.notes).length} saved remarks, {restore.workspace.personal.bookmarks.length} bookmarks and {restore.workspace.assets.length} verified attachments.</p><p className="warning-text">Restore replaces this browser's saved workspace, including its personal state. Download a backup of this workspace first. Newer built-in source revisions still take precedence over older imported snapshots.</p><label className="inline-check"><input type="checkbox" checked={confirmRestore} onChange={e => setConfirmRestore(e.target.checked)}/> I understand that this replaces the current local workspace.</label><div className="button-row"><button onClick={() => setRestore(null)}>Cancel restore</button><button className="primary" onClick={commitRestore} disabled={!confirmRestore || !!busy}>Restore verified backup</button></div></div>}{store.error && <div className="error-message"><p>{store.error}</p><button onClick={() => action('Retrying save...', () => store.retry())}>Retry saving</button><button onClick={() => action('Preparing raw recovery...', async () => { download(JSON.stringify(await rawRecovery(), (_k, v) => v instanceof Uint8Array ? { type: 'Uint8Array', bytes: [...v] } : v, 2), 'atlas-raw-recovery.json', 'application/json'); })}>Download raw recovery JSON</button></div>}</section>
 <section className="settings-section"><h3><Icon name="folder"/> Export content for manual repository work</h3><p>Export canonical pack folders with stable IDs, local edits and attachments. All exported packs are deliberately marked private. Remarks, flags, archived status and reading state belong in your separate workspace backup.</p><button disabled={!!busy} onClick={() => action('Exporting private content workspace...', async () => { const result = await exportRepositoryWorkspace(compose(built, store.state), store.state, assets.asset); download(result.bytes, 'knowledge-atlas-content-workspace.private.zip'); notify(`Exported ${result.pageCount} pages in ${result.packCount} private packs.`); })}>Export private content workspace</button></section>
 <section className="settings-section"><h3><Icon name="pdf"/>Export private PDF library</h3><p>Download only private PDF binaries and metadata as a standard Atlas library ZIP. No publication, credentials or repository fetch. Public demo PDFs, note bodies and personal state are excluded; keep a complete backup separately.</p><Field label="PDF library pack ID"><input value={pdfExportId} onChange={e=>setPdfExportId(e.target.value)}/></Field><Field label="PDF library version"><input value={pdfExportVersion} onChange={e=>setPdfExportVersion(e.target.value)}/></Field><p className="secondary">For a fresh workspace or reviewed source-ownership migration. Reuse this ID and advance the version for changes; conflicting existing IDs are never silently overwritten.</p><button disabled={!!busy} onClick={()=>action('Preparing private PDF library...',async()=>{await store.flush();const result=await exportPrivatePdfLibrary(compose(built,store.state),assets.asset,{id:pdfExportId,version:pdfExportVersion});download(result.bytes,'atlasnote-private-pdf-library.zip');notify(`Exported ${result.documentCount} private PDF document(s). Nothing was uploaded.`);})}>Download private PDF library ZIP</button></section>
 <section className="settings-section"><h3>Appearance &amp; storage</h3><Field label="Light theme"><select value={store.state.personal.session.theme} onChange={e => {document.dispatchEvent(new Event('atlas:before-reader-change'));store.personal(p => { p.session.theme = e.target.value; });}}>{Object.entries(THEME_LABELS).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></Field><Field label="Reading text size"><input type="range" min="14" max="22" step="1" value={store.state.personal.session.fontSize} onChange={e => {document.dispatchEvent(new Event('atlas:before-reader-change'));store.personal(p => { p.session.fontSize = Number(e.target.value); });}}/></Field><p>{usage ? `${Math.round((usage.usage ?? 0) / 1024 / 1024 * 10) / 10} MB used of approximately ${Math.round((usage.quota ?? 0) / 1024 / 1024)} MB available.` : 'Storage is managed by this browser.'} Clearing site data removes local changes.</p><button onClick={() => action('Requesting persistent storage...', async () => { const kept = await navigator.storage?.persist?.(); notify(kept ? 'Persistent storage permission granted. Backups are still recommended.' : 'Persistent storage was not granted. Keep regular backups.'); })}>Request persistent storage</button><p className="secondary">No sign-in, telemetry, automatic external image fetches, or background synchronization.</p></section></div>{busy && <div className="busy-status" role="status">{busy}</div>}{error && <pre className="error-message" role="alert">{error}</pre>}</Modal>;
}
