import {loadDurabilityDemo,removeDurabilityDemo} from './demo.js';
import React,{useState,useEffect,useSyncExternalStore} from '../vendor/react.mjs';
import {store,readIntegrityWorkspace} from '../storage/database.js';
import {captureWorkspaceSnapshot} from '../storage/workspace-snapshot.js';
import {storageHealth,requestPersistence,historyCapacity} from './storage-health.mjs';
import {ArchiveManager,readableBytes} from './ArchiveManager.js';
import {checkWorkspaceIntegrity,verifyBackupFile,verifyRecoveryBundle,createRecoveryBundle} from './recovery.js';
import {attachedPayload,subscribeArchives,archiveAttachmentEpoch} from './registry.js';
import {getBuildIdentity} from './provenance.js';
import {readBackupHealth,recordBackupHealth} from './backup-health.js';
import {schemas} from '../app/load.js';
import {download,unzipBounded} from '../storage/archives.mjs';
import {Icon} from '../components/Icon.js';
export function DurabilityPanel({built,assets,disabled=false}:any){
 const ws=useSyncExternalStore(store.subscribe,store.getSnapshot);useSyncExternalStore(subscribeArchives,archiveAttachmentEpoch);
 const [health,setHealth]=useState<any>(null),[backupHealth,setBackupHealth]=useState(readBackupHealth),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[identity,setIdentity]=useState<any>(null);
 useEffect(()=>{void storageHealth().then(setHealth);void getBuildIdentity().then(setIdentity).catch(e=>setError(e.message));},[]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const blocked=disabled||busy;
 return <>
 <section className="settings-section durability-section" aria-label="Storage and recovery health"><h3><Icon name="database"/> Storage &amp; recovery health</h3>
  <p data-save-safety>{store.error?'UNSAVED / Keep this tab open and export an emergency backup.':store.saving?'Pending writes / Closing may lose changes.':'Saved / No pending writes reported.'}</p>
  <p>{health?.estimate.status==='available'?`${readableBytes(health.estimate.usage)} used / ${readableBytes(health.estimate.quota)} estimated origin quota. ${readableBytes(health.estimate.available)} estimated remaining.`:'Quota estimate: '+(health?.estimate.status??'checking')+'. Unknown quota does not imply free space.'}</p>
  <p>Persistence: {health?.persistence.status??'checking'}. Persistence reduces automatic eviction risk; it is not a backup or protection against clearing site data.</p>
  <div className="button-row"><button disabled={blocked} onClick={()=>void run(async()=>setHealth(await storageHealth()))}>Refresh storage health</button><button disabled={blocked} onClick={()=>void run(async()=>{const r=await requestPersistence();setHealth(await storageHealth());setMessage('Persistence request: '+r.status+'. Keep independently verified backups.');})}>Request persistent storage</button></div>
  <details><summary>Capacity thresholds and asset ownership</summary>{historyCapacity(ws.history).map(row=><p key={row.name} data-capacity-level={row.level}>{row.name}: {row.used.toLocaleString()} / {row.limit.toLocaleString()} ({Math.round(row.ratio*100)}%) / {row.level}</p>)}<p>Warnings: 70% watch, 85% high, 95% critical. Limits still block writes rather than deleting history. {ws.assets.length} local assets / {readableBytes(ws.assets.reduce((n,a)=>n+a.bytes.length,0))}. {ws.history?.archives?.length??0} external archive dependencies.</p></details>
  <button data-durability-action="integrity" disabled={blocked||store.saving>0||!!store.error} onClick={()=>void run(async()=>{const snapshot=await readIntegrityWorkspace();setResult(await checkWorkspaceIntegrity(snapshot,built,assets.asset,await schemas(),await getBuildIdentity()));setMessage('Read-only integrity check passed. Nothing was repaired or changed.');})}>Run workspace integrity check</button>
  <label className="file-picker">Verify backup or complete recovery file (without restoring)<input aria-label="Verify backup file" type="file" accept=".zip" disabled={blocked} onChange={e=>{const file=e.target.files?.[0],trusted=e.nativeEvent.isTrusted;e.target.value='';if(file)void run(async()=>{const {transfer}=await unzipBounded(file),verified=transfer?.kind==='complete-recovery'?await verifyRecoveryBundle(file,built,await schemas()):await verifyBackupFile(file,built,await schemas());setResult(verified.summary);if(trusted){recordBackupHealth('reselected',verified.summary,store.state.history?.meta.epoch??0);setBackupHealth(readBackupHealth());}setMessage('Saved file verified without restoring or changing IndexedDB. This proves these file bytes, not permanent external retention.');});}}/></label>
  <button data-durability-action="complete-recovery" disabled={blocked} onClick={()=>void run(async()=>{const snapshot=await captureWorkspaceSnapshot(),bundle=await createRecoveryBundle(snapshot,built,assets.asset,await getBuildIdentity(),await schemas(),id=>attachedPayload(snapshot.history,id));download(bundle.bytes,bundle.manifest.artifactId+'.atlas-recovery.zip');recordBackupHealth('generated',bundle.summary,ws.history?.meta.epoch??0);setBackupHealth(readBackupHealth());setResult(bundle.summary);setMessage('Complete recovery bundle generated and self-verified. Re-select the saved file using Verify before relying on it.'+(store.error?' Browser saving failed: this bundle captures unsaved in-memory work, not a successful database commit. Keep this tab open until you verify restoration.':''));})}>Create complete recovery bundle</button>
  <details><summary>Backup Health (local metadata, not proof of retention)</summary><p>Last generated and validated: {backupHealth.generated?new Date(backupHealth.generated.at).toLocaleString():'not recorded'}.</p><p>Last independently selected and verified: {backupHealth.reselected?new Date(backupHealth.reselected.at).toLocaleString():'not recorded'}.</p>{backupHealth.reselected&&<p>{backupHealth.reselected.epoch===ws.history?.meta.epoch?'No later history epoch recorded.':'History changed since that verification.'} Later personal edits may still require a fresh backup.</p>}<pre>{JSON.stringify(backupHealth,null,2)}</pre></details>
  <details><summary>Exact build identity</summary><pre>{JSON.stringify(identity,null,2)}</pre>{identity?.sourceDirty&&<p className="warning-text">This build contains uncommitted source changes and is not a clean release candidate.</p>}</details>
  <details><summary>Move to another origin, browser or device</summary><p>Create a complete recovery bundle with every archive attached, save it and independently verify it. Keep the old origin intact. Open the target installation, unlock it, choose the recovery file in Restore, and confirm replacement. Run integrity checking and compare counts and hashes. Re-attach the recovery bundle for historical browsing after reload. Retire the old origin only after checking current and archived content, including a private historical PDF.</p></details>
  {result&&<details open><summary>Verification result</summary><pre className="durability-result" data-durability-result>{JSON.stringify(result,null,2)}</pre></details>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">Checking storage and recovery data...</p>}{error&&<p role="alert" className="error-message">{error}</p>}
 </section>
 <ArchiveManager built={built} assets={assets} disabled={blocked}/>
 <section className="settings-section durability-section"><details><summary>Optional V2.3 durability demo data</summary><p>Original synthetic Notebook, Article, Cheatsheet, QCM, tree and two PDF byte variants. Loads only on request. Cleanup keeps edited/referenced content and all historical evidence.</p><div className="button-row"><button data-durability-action="load-demo" disabled={blocked} onClick={()=>void run(async()=>setMessage((await loadDurabilityDemo(built)).message))}>Load V2.3 durability demo data</button><button data-durability-action="remove-demo" disabled={blocked} onClick={()=>void run(async()=>setMessage((await removeDurabilityDemo(built)).message))}>Remove unchanged V2.3 demo data</button></div></details></section>
 <section className="settings-section durability-section" aria-label="Access control"><h3><Icon name="lock"/> Browser access</h3><p>The Netlify gate protects the remotely served application shell, not local disk data. Lock clears only the access cookie, never the workspace. Anyone controlling this unlocked OS/browser profile may still access its local data.</p><form action="/__atlasnote_lock" method="post" onSubmit={e=>{e.preventDefault();const form=e.target as HTMLFormElement;void run(async()=>{if(location.protocol!=='https:')throw Error('This is an ungated local HTTP development origin. Use Netlify HTTPS/Netlify Dev integration to test access control.');document.dispatchEvent(new Event('atlas:before-reader-change'));await store.flush();if(store.unsafeClose)throw Error('Resolve pending or failed writes before locking. Export an emergency backup if saving failed.');form.submit();});}}><button disabled={blocked} data-durability-action="lock">Lock this browser / logout</button></form></section>
 </>;
}
