import {writeBuildIdentity} from './build-identity.mjs';
import {checkAccessBuild} from './check-access-build.mjs';
await checkAccessBuild();
import {checkPdfatlasProvenance} from './check-pdfatlas-provenance.mjs';
await checkPdfatlasProvenance();
import fs from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {compileContent} from './compile-content.mjs';
await fs.rm('dist-offline',{recursive:true,force:true});await fs.mkdir('dist-offline',{recursive:true});
execFileSync(process.execPath,['node_modules/typescript/bin/tsc','--outDir','dist-offline/app'],{stdio:'inherit'});
await fs.cp('src/vendor','dist-offline/app/vendor',{recursive:true,filter:p=>!p.endsWith('.d.mts')});
await fs.cp('src/content/schemas','dist-offline/app/content/schemas',{recursive:true});
await fs.cp('src/styles','dist-offline/styles',{recursive:true});await fs.cp('public','dist-offline',{recursive:true});
await fs.copyFile('LICENSE','dist-offline/LICENSE.txt');
await fs.copyFile('THIRD_PARTY_NOTICES.md','dist-offline/THIRD_PARTY_NOTICES.md');
await fs.cp('docs/licenses','dist-offline/licenses',{recursive:true});
await compileContent('dist-offline');
await fs.writeFile('dist-offline/index.html',`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f5f7fb"><meta name="referrer" content="no-referrer"><title>AtlasNote V2.3</title><link rel="icon" href="./assets/atlas.svg" type="image/svg+xml"><link rel="stylesheet" href="./styles/app.css"></head><body><div id="root"><p class="loading">Opening AtlasNote...</p></div><noscript>AtlasNote needs JavaScript for local storage and reading views. Your library is not sent to a server.</noscript><script src="./app/vendor/jszip.js"></script><script src="./app/vendor/prism.js"></script><script type="module" src="./app/main.js"></script></body></html>`);
await writeBuildIdentity('dist-offline','compatibility');
console.log('Compatibility build complete in dist-offline/. No private library is included.');
