import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import {compileContent} from './compile-content.mjs';
const require=createRequire(import.meta.url);
async function packageRoot(entry,name){let dir=path.dirname(entry);while(dir!==path.dirname(dir)){try{const p=JSON.parse(await fs.readFile(path.join(dir,'package.json'),'utf8'));if(p.name===name)return {dir,p};}catch{}dir=path.dirname(dir);}throw Error('Unable to locate '+name+' package metadata');}
let vite,reactPDF,pdfjs;try{vite=await packageRoot(require.resolve('vite'),'vite');reactPDF=await packageRoot(require.resolve('react-pdf'),'react-pdf');const fromWrapper=createRequire(path.join(reactPDF.dir,'package.json'));pdfjs=await packageRoot(fromWrapper.resolve('pdfjs-dist'),'pdfjs-dist');}catch(e){throw Error('Optional dependencies are unavailable. Run npm run enable:online on a network-enabled computer first. '+e.message);}
await fs.rm('.vite-public',{recursive:true,force:true});await fs.cp('public','.vite-public',{recursive:true});await fs.mkdir('.vite-public/app/vendor',{recursive:true});for(const n of ['jszip.js','prism.js'])await fs.copyFile('src/vendor/'+n,'.vite-public/app/vendor/'+n);await fs.cp('src/content/schemas','.vite-public/app/content/schemas',{recursive:true});await compileContent('.vite-public');await fs.mkdir('.vite-public/pdf-assets',{recursive:true});await fs.copyFile(path.join(pdfjs.dir,'build/pdf.worker.min.mjs'),'.vite-public/pdf-assets/pdf.worker.min.mjs');for(const dir of ['cmaps','wasm','standard_fonts']){try{await fs.cp(path.join(pdfjs.dir,dir),'.vite-public/pdf-assets/'+dir,{recursive:true});}catch(e){if(e.code!=='ENOENT')throw e;}}
await fs.copyFile('LICENSE','.vite-public/LICENSE.txt');await fs.copyFile('THIRD_PARTY_NOTICES.md','.vite-public/THIRD_PARTY_NOTICES.md');await fs.cp('docs/licenses','.vite-public/licenses',{recursive:true});
await fs.writeFile('.vite-public/pdf-assets/engine.json',JSON.stringify({reactPdf:reactPDF.p.version,pdfjs:pdfjs.p.version}));
execFileSync(process.execPath,[path.join(vite.dir,'bin/vite.js'),'build','--config','vite.config.mjs'],{stdio:'inherit'});
console.log('Optional Vite build completed. Run normal-origin PDF and IndexedDB browser tests before release.');
