import React,{useEffect,useState} from '../vendor/react.mjs';
import {isTrustedPdfatlasDocument,fetchTrustedPdf} from './external-policy.js';
import type {DocumentEntry,Location} from '../core/model.js';import {Icon} from '../components/Icon.js';
/** The offline build never mislabels an iframe as an integrated PDF engine.
 * The optional separately installed engine is injected by the Vite online entry. */
export function PdfReader({document:doc,location,onLocation,resolve,fetchBytes}: {document:DocumentEntry;location:Location;onLocation:any;resolve:(key:string)=>string|undefined;fetchBytes:(key:string)=>Promise<Uint8Array>}){
 const [adapter,setAdapter]=useState<any>(null),[error,setError]=useState(''),[consent,setConsent]=useState(false),[show,setShow]=useState(false),[url,setUrl]=useState<string|undefined>(undefined),[externalError,setExternalError]=useState(''),[retry,setRetry]=useState(0);
 const trusted=isTrustedPdfatlasDocument(doc);
 useEffect(()=>{let active=true;if(window.atlasPdfLoader)window.atlasPdfLoader().then(m=>{if(active)setAdapter(()=>m.PdfEngine);}).catch(e=>setError('Optional PDF engine failed to load: '+e.message));return()=>{active=false;};},[]);
 useEffect(()=>{
  const controller=new AbortController();let objectUrl:string|undefined;let active=true;
  setUrl(doc.assetKey?resolve(doc.assetKey):undefined);setShow(false);setConsent(false);setExternalError('');
  if(trusted)fetchTrustedPdf(doc,controller.signal).then(bytes=>{if(!active)return;objectUrl=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));setUrl(objectUrl);setConsent(true);setShow(true);}).catch(e=>{if(active&&e.name!=='AbortError')setExternalError(e.message||'The public PDF host is unavailable.');});
  return()=>{active=false;controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);};
 },[doc.id,doc.sha256,doc.source.url,doc.assetKey,retry]);
 const external=doc.source.kind==='https'||doc.source.kind==='external-link';
 if(trusted&&!url)return <div className="pdf-reader"><div className="pdf-intro"><div className="eyebrow">PUBLIC PDF LIBRARY</div><h1>{doc.title}</h1><p>{doc.pageCount} pages / {doc.language?.toUpperCase()} / {doc.rights.attribution}</p><div className="pdf-external-status" role={externalError?'alert':'status'}><strong>{externalError?'Public PDF could not be opened':'Opening the verified public reference...'}</strong><p>{externalError||'Downloading from the configured public library and checking its original SHA-256. No private workspace data is sent.'}</p><code>{doc.source.url}</code>{externalError&&<button onClick={()=>setRetry(n=>n+1)}>Retry public PDF</button>}<p>This is an external reference. Its bytes are not in your workspace backup unless you import the PDF locally.</p></div></div></div>;
 if(adapter){const Component=adapter;return <Component document={doc} location={location} onLocation={onLocation} url={trusted?url:external?(consent?doc.source.url:undefined):url} requestExternal={()=>setConsent(true)}/>;}
 return <div className={'pdf-reader'+(show?' has-preview':'')}><div className="pdf-intro"><div className="eyebrow">PDF DOCUMENT</div><h1>{doc.title}</h1><p>{doc.rights.attribution}</p>{trusted&&<p className="secondary">Verified public reference / SHA-256 checked / not stored offline</p>}<div className="pdf-engine-notice" role="status"><Icon name="help"/><div><strong>Browser preview only in this offline build</strong><p>The integrated PDF engine is not bundled. Atlas page navigation, selectable-text search, rotation and physical-page spreads are unavailable here. Local PDF bytes are preserved in imports and backups. External references are backed up as metadata only.</p></div></div>{error&&<p role="alert">{error}</p>}
 {external&&!trusted&&!consent?<div className="callout"><p>Opening this PDF contacts its external host. The full URL is shown before any request.</p><code>{doc.source.url}</code><button onClick={()=>{setConsent(true);setUrl(doc.source.url);}}>Allow external PDF reference</button></div>:url?<div className="button-row"><button className="primary" onClick={()=>setShow(v=>!v)}>{show?'Hide browser preview':'Show browser PDF preview'}</button><a className="button" href={url} target="_blank" rel="noopener noreferrer">Open original PDF</a><a className="button" href={url} download={doc.title+'.pdf'}>Download original</a></div>:<div className="callout warning"><strong>PDF bytes are unavailable</strong><p>This document is a reference to a local library file that has not been imported. Import the original PDF through Settings. Atlas does not invent its pages.</p></div>}
 <details className="pdf-metadata"><summary>Document identity &amp; provenance</summary><dl><dt>Visibility</dt><dd>{doc.visibility}</dd><dt>Document ID</dt><dd>{doc.id}</dd><dt>SHA-256 revision</dt><dd><code>{doc.sha256??'External reference - no verified local bytes'}</code></dd><dt>Rights</dt><dd>{doc.rights.status}</dd><dt>Bytes</dt><dd>{doc.bytes??'Not imported'}</dd></dl></details></div>
 {show&&url&&<iframe className="pdf-fallback" src={url} title={'Browser PDF preview: '+doc.title} referrerPolicy="no-referrer"/>}
 </div>;
}
